LICENSE, license.md, readme.md
I chose `LICENSE` over `license.md` since that seems to be in the canonical format.
=> Document that API is unstable and remove duplicate license

internal/unix/types_linux.go, internal/unix/types_other.go, map.go, map_test.go, perf/reader.go, perf/reader_test.go, perf/ring.go, perf/ring_test.go, prog.go, syscalls.go
This PR addresses the issue described in https://github.com/cilium/ebpf/issues/10.
It introduces only one new error variable `errNonLinux`. This error is returned, if unix specific functions are called.
=> use build tags

abi.go, map.go, map_test.go, prog.go, prog_test.go, syscalls.go
BPF maps and programs can be sent around via SCM_RIGHTS, so users should
be able to interact with them.
=> map, program: allow creation from raw FD

.semaphore/semaphore.yml, syscalls.go
The magic number for bpffs doesn't fit in Statfs_t.Type on 32bit arch,
which leads to a compilation error. Looking at the kernel source, the
thing to do is to treat the magic number as unsigned.
Fixes #18
=> fix compilation on 32-bit targets

map.go, map_test.go
MapIterator.Next uses BPF_MAP_GET_NEXT_KEY to iterate a map. However,
there is no guarantee that a lookup makes forward progress through a
map. This is a problem with the kernel API, for which there is
currently no fix.
The problem manifests with heavily modified hashmaps, where the
race between MAP_GET_NEXT_KEY and MAP_LOOKUP_ELEM can lead to the
iterator code retrying an unbounded number of times.
Limit the iterator to MaxElems calls.
Fixes #9
=> map: bound retries when iterating

ptr_32_be.go
Given a 32 bit big endian pointer {01, 02, 03, 04}, it's 64 bit
representation should be {00, 00, 00, 00, 01, 02, 03, 04}. Therefore
the current order of syscallPtr is wrong.
Fixes #17
=> syscalls: fix pointer padding on 32bit big endian arches

.semaphore/semaphore.yml, run-tests.sh
Sockmaps require BPF_STREAM_PARSER to be enabled for the kernel,
which wasn't the case so far. Also run QEMU with two CPUs, so
that the per-CPU marshalling test can run.
=> Update kernels and use 2 CPUs on CI

internal/unix/types_linux.go, perf/reader.go, perf/reader_test.go
This implementation is inspired by the upstream Cilium commit
[ce6244109bd0](http://github.com/cilium/cilium/commit/ce6244109bd0) ("cilium: add Mute/Unmute function for perf RB") by Daniel
Borkmann, to support enabling and disabling perf ringbuffer
notifications at runtime.
On the way, I fixed running the perf unit tests via `sudo go test ./...`.
=> Add support for pausing/resuming perf readers

.semaphore/semaphore.yml, internal/btf/btf_test.go
5.4 is the current LTS, while 5.3 is going to be unsupported soon.
Move testing to 5.4 and run the BTF tests against the new kernel's
builtin BTF.
=> CI: test on 5.4 instead of 5.3

map.go, map_test.go
libbpf based tooling expects map definitions for PerfEventArrays to
have a key and value size of four, while this package has traditionally
required a size of zero. Accept key or value size of four to be
compatible with libbpf.
=> map: allow creating PerfEventArray with key or value size four

internal/ptr.go, map_test.go
The kernel expects any strings to be zero terminated. The pointer conversion
code so far hasn't ensured that this is the case. Unfortunately it's not
possible to test for this reliably, since the behaviour seems to depend on
how the Go runtime copies strings into byte buffers.
Fixes #51
=> internal: zero terminate pointers to a string

elf_reader.go, map.go, prog.go, syscalls.go, syscalls_test.go
Use the symbol used to refer to a map as the default name. Since Linux 5.2
it's also valid to include '.' in a name, so make SanitizeName account for
this.
=> map: populate name from ELF symbol name

.semaphore/semaphore.yml, run-tests.sh
I'm trying to trim some time from our CI builds, without much luck it seems. I've managed to avoid fetching packages over and over, but I suspect that something is messing with the Go build cache. Since we still have plenty of credit on CI this isn't super pressing, so I'm not investigating further.
=> Make CI runs a bit faster

collection.go, internal/btf/btf.go, internal/feature.go, internal/feature_test.go, map.go, map_test.go, perf/reader.go, prog.go, syscalls.go
With the new errors.Is and errors.As functions from Go 1.13 we can remove
the various Is* functions without a loss in flexibility. Instead, we export
sentinel errors and take care to always return them in a wrapped form.
Users that are not yet on Go 1.13 can use the golang.org/x/xerrors package.
=> use sentinel errors instead of functions

internal/btf/btf.go, internal/btf/ext_info.go
Two `xerrors.Errorf` calls with the `%w` verb are missing the error to wrap.
Add it.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
=> btf: wrap errors correctly

internal/errors.go, prog.go, prog_test.go
An earlier change made it so that we'd discard the verifier output
if the user had specified a LogLevel > 0. Fix this and add a test.
Fixes #64
=> program: include verifier output on error when LogLevel > 0

internal/btf/btf_types.go, internal/btf/types.go
This PR started by fixing a simple error message and resulted then in adding the missing `String()` for `btfKind`.
=> btf: add String() for btfKind

internal/unix/types_linux.go, internal/unix/types_other.go, prog.go, prog_test.go
Testing a BPF program can be interrupted if a signal arrives for a
userspace thread while being stuck in the BPF syscall.
BPF_PROG_TEST_RUN returns EINTR in that case, and we are required
to retry.
This has an unfortunate side-effect: benchmark results will be
skewed, because we might have to do more work than was originally
asked of us. The per-run calculation performed by the Go test
harness are therefore unreliable. Document this until we get a
better idea how to fix this.
Updates #24
=> program: retry BPF_PROG_TEST_RUN on EINTR

internal/btf/ext_info.go, types.go
The last use of the constants was removed with commit aaa563ef6a5d4578ae252c89d230713a17b61dfe. And as there is `0xeB9F` already defined, it doesn't need to be defined twice.
=> remove unused and duplicate code

.semaphore/semaphore.yml, readme.md, run-tests.sh
Run tests for each combination of supported Go and kernel version,
and document explicitly supported versions in the readme.
Fixes #37
=> CI: run tests on Go 1.14 and 1.13 and document requirements

prog.go, prog_test.go
If specified in `ProgramSpec` so far `kenelVersion` was just ignored. This attribute is around since 4.1  [2541517c32be](https://github.com/torvalds/linux/commit/2541517c32be).
=> Don't ignore kernelVersion

internal/cpu.go, internal/cpu_test.go, internal/unix/types_linux.go, internal/unix/types_other.go, map.go, perf/reader.go, perf/ring.go
Based on discussion in #58 and prompted by @iAklis and his PRs #78 and #80.
This fixes the behaviour on systems that have one or more CPUs disabled. Previously things would only work if the disabled CPUs were on the end of the range.
It's still not possible to use PerfEventArrays that have more than the total number of CPUs in the system (as suggested by @iAklis), since I'm not sure that's a good idea to do. We also don't deal with CPUs being added or removed after a perf.Reader has been created.
More details in the commit descriptions.
=> Use number of possible CPUs for PerfEventArray.MaxEntries

.semaphore/semaphore.yml, internal/unix/types_other.go, prog_test.go
Use wrappers from github.com/cilium/ebpf/internal/unix to avoid the
following build error when building the tests on non-linux:
```
./prog_test.go:131:14: undefined: "golang.org/x/sys/unix".Gettid
./prog_test.go:148:10: undefined: "golang.org/x/sys/unix".Tgkill
```
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
=> Fix test build on non-linux

example_program_test.go
Inspired by issue https://github.com/cilium/ebpf/issues/83 this PR adds an example on how to attach an eBPF program to a tracepoint. It puts the code sample from @mythi into a complete example.
=> Add tracepoint example

elf_reader_test.go
Split the flag that controls whether libbpf integration tests are
run into a path and a pattern. This makes it easier to run the tests,
since the user doesn't have to know the correct pattern.
Use 'test_*.o' as the default pattern, since that is the most
straighforward at the moment.
=> elf: make libbpf integration tests easier to use

run-tests.sh
limits, because it is not on a paid account. This retrieves the
kernels from cilium, rather than newtools, so the bandwidth
limit is not hit.
Signed-off-by: Nate Sweet <nathanjsweet@pm.me>
=> The newtools ci-kernels project is running into LFS bandwidth

internal/unix/types_linux.go, internal/unix/types_other.go, map_test.go
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
=> Use RLIMIT_MEMLOCK and RLIM_INFINITY consts from x/sys/unix

perf/ring.go, perf/ring_test.go
The mmap buffer is sized in bytes, but needs to be page aligned.
This was correctly derived.
Additionally, with perf_event_open, according to man 2 perf_event_open:
> The mmap size should be 1+2^n pages
This wasn't correctly enforced, and caused the mmap call to fail with
EINVAL for some buffer sizes. For example 8193 bytes would be
incorrectly rounded to 3 pages instead of 4.
Always round up to the nearest power of two number of pages, and add
some tests.
Also allow `watermark == buffer` as this as a source of confusion, 
see https://github.com/cloudflare/xdpcap/issues/39#issuecomment-616382309
=> perf: Fix mmap buffer size calculation

elf_reader_test.go
The integration tests are currently broken. When running them in parallel,
the file variable is captured by the closure in t.Run, and so we only
ever try to load a single file.
Fix this by taking an explicit copy of the filename, and by turning off
parallel tests. This is turn makes the tests fail, since there is plenty
of libbpf stuff that we don't understand.
Related to #92
=> elf: fix libbpf integration tests

internal/unix/types_linux.go, internal/unix/types_other.go, map.go, map_test.go, syscalls.go
If you update a hash map with the flag `UpdateNoExist` you expect an error if the key already exists. This PR exposes this error and let the user of the package handle it properly.
=> Expose EEXIST

asm/opcode.go
For example:
```
var ins asm.Instruction
ins.OpCode = 6
fmt.Printf("%v\n", ins)
// Result: OpCode(0x6)
```
Previously this causes a stack overflow error.
=> asm: support printing unsupported opcode

elf_reader.go, map.go, perf/reader.go, perf/reader_test.go, syscalls.go
Hi all,
While migrating a project off of gobpf, I encountered some issues loading an ELF binary, most of which have been addressed below. There's another part that deals with overwriting the binary's `version` section with the running kernel's `LINUX_VERSION_CODE`, but that I'd like to address in another PR.
The removal of BTF requirements in data sections and the rlimit changes might need some extra test coverage, but please let me know what you think before I get started on that.
I've added a bit more detailed info about the perf event buffer underrun in [the commit that introduced it](https://github.com/ti-mo/ebpf/commit/2cc7e4625e0baab30bfd8be9d5a5c4e6d8012dd2):
> https://elixir.bootlin.com/linux/v5.5.13/source/kernel/events/core.c#L6611 raw->size is used to size the buffer, but …
=> Friendly map create errors, document rlimit and perf ring garbage

map_test.go, types.go
Hi lmb,
I have added a test for LRUCPUHash, LRUCPUHash is PerCPU map that store a distinct value for each CPU, so from userspace we need to see it in the form of an array
=> hasPerCPUValue function add MapType LRUCPUHash

internal/syscall.go, internal/testutils/feature.go, internal/unix/types_linux.go, internal/unix/types_other.go, link/link.go, link/link_test.go, link/program.go, link/program_test.go, link/syscalls.go, link/syscalls_test.go, map.go, prog.go, prog_test.go, syscalls.go, types.go, types_string.go
bpf_link appeared in 5.7 and there is a push to migrate existing BPF hooks to using this infrastructure. For example, bpf_iter is only useable via bpf_link. This PR adds a new subpackage link. It contains low-level APIs to do attaching. I'll submit the higher-level APIs based on `Link` in a follow up to this PR.
```
package link // import "github.com/cilium/ebpf/link"
var ErrNotSupported = internal.ErrNotSupported
func RawAttachProgram(opts RawAttachProgramOptions) error
func RawDetachProgram(opts RawDetachProgramOptions) error
type Link interface{ ... }
type RawAttachProgramOptions struct{ ... }
type RawDetachProgramOptions struct{ ... }
type RawLink struct{ ... }
func AttachRawLink(opts RawLinkOptions) (*RawLink, error)
func LoadPinnedRawLink(fileName string) (*RawLink, error)
type …
```
=> Add support for raw bpf_link

elf_reader.go, elf_reader_test.go, internal/fd.go, link/cgroup.go, link/cgroup_test.go, link/iter.go, link/iter_test.go, link/syscalls.go, link/syscalls_test.go, prog.go, syscalls.go
Use the low-level APIs to construct high-level `Link`s for attaching to cgroups and bpf_iter. Especially the cgroup support is interesting, because it falls back to BPF_PROG_ATTACH after trying bpf_link on older kernel.
New API:
```
var ErrNotSupported = internal.ErrNotSupported
func RawAttachProgram(opts RawAttachProgramOptions) error
func RawDetachProgram(opts RawDetachProgramOptions) error
+type CgroupOptions struct{ ... }
+type Iter struct{ ... }
+    func AttachIter(opts IterOptions) (*Iter, error)
+    func LoadPinnedIter(fileName string) (*Iter, error)
+type IterOptions struct{ ... }
type Link interface{ ... }
+    func AttachCgroup(opts CgroupOptions) (Link, error)
+    func LoadPinnedCgroup(fileName string) (Link, error)
type RawAttachProgramOptions struct{ ... }
type …
```
=> bpf_iter and cgroup support

run-tests.sh
According to [documentation](https://golang.org/cmd/go/#hdr-Testing_flags):
> The command-line package list, if present, must appear before any flag not known to the go test command.
Commit 2e07740 switched go test into "local directory" mode by adding unknown (for go test) flag before package list:
```
/usr/local/bin/go test -coverprofile="$1/coverage.txt" -covermode=atomic -v -elfs "$elfs" ./...
```
Proofs:
- ["github.com/cilium/ebpf/asm" tests started](https://ebpf.semaphoreci.com/jobs/c34fe5c5-53cf-445d-bcbb-6ec122fc6fbf)
- ["github.com/cilium/ebpf/asm" tests not started](https://ebpf.semaphoreci.com/jobs/f730420c-2064-46f2-8527-ae076d30177e)
I'm not sure the current solution is the best, alternatives:
- use environment variable (e.g. `ELFS_DIR`/`ELFS_PATTERN`):
* pros: simple
* cons: …
=> Fixed package list for "go test"

doc.go, link/doc.go, readme.md
We now have support for attaching to some subsystems, so update
the documentation accordingly.
=> doc: mention the link package in documentation

collection.go, collection_test.go, example_program_test.go, example_sock_elf_test.go
Interacting with a CollectionSpec or Collection involves a lot
of boilerplate, since checking that all required programs are
present is cumbersome. It becomes really unwieldy if you're
trying to correctly clean up Programs and Maps on error:
prog := coll.DetachProgram("foo")
if prog == nil {
// error!
}
defer prog.Close() // or maybe only close on error?
map := coll.DetachMap("bar")
// ...
It also means that the names of programs and maps are spread
all over the code base.
Add helpers to CollectionSpec and Collection to simplify to
something like this:
var objs struct{
Program *ebpf.Program `ebpf:"foo"`
Map     *ebpf.Map     `ebpf:"map"`
}
if err := coll.Assign(&objs); err != nil {
// Either foo or bar doesn't exist!
}
These functions will be used as the basis to build a code
generator …
=> collection: add Assign helpers

run-tests.sh
The go test command requires custom flags to be passed at the end of
the invocation. Go 1.15 has become stricter with this, and the test
therefore fails on that version.
=> CI: specify custom test flags last

internal/btf/types.go
Inflates BTF enum values for easier access later since the link between `Spec.rawTypes` and `Spec.types` is difficult to navigate.
=> Inflate BTF enum values

internal/btf/btf_types.go, internal/btf/types.go
This supports bitfield types for Struct & Union. kind_flag indicates whether Fwd is for a struct or union.
In support of #114
=> Add kind_flag support for Struct, Union, and Fwd

asm/instruction.go, asm/opcode.go, linker.go, prog.go
Jumps and calls may have to be fixed up, if their target isn't known
at compile time. This happens when a user uses the asm package to write
"inline" BPF programs, and when using function calls in C derived BPF.
The jump and call targets have to be expressed in units of raw BPF
instructions. Since some asm.Instructions have to be encoded in two
BPF instructions there is no 1:1 mapping. Figuring out the raw
instruction offset therefore involves iterating all instructions
and keeping a running count.
Due to this the fixup currently happens during instruction marshalling.
This is a bit of a hack, but so far allowed to keep the details of raw
instruction offsets contained to the asm package.
With BPF CO-RE this doesn't work too well anymore: the fixup we have to do
is also based on raw BPF …
=> program: move jump and call fixup out of asm package

internal/btf/btf.go, internal/btf/btf_test.go
The current code fails to find any kernel spec because the call to
Sprintf may contain too many or too few arguments. The result then
contains %!s(MISSING), etc. which of course triggers an error when
trying to open the path.
Another problem is that the function tries other filenames if reading
the BTF itself fails for some reason. In that case it will most likely
return ErrNotFound, and the user is none the wiser: we found a BTF
but couldn't load it.
Change the code so that we return any error from the BTF loading itself.
=> btf: fix LoadKernelSpec

cmd/bpf2go/doc.go
We need at least clang 9, since earlier versions don't support
-fdebug-compilation-dir. Without that flag reproducible builds don't work.
=> cmd/bpf2go: document required clang version

collection_test.go, map.go, perf/reader.go, prog.go
Add explicit getters for fields that are currently exported via
ABI() and mark the functions as deprecated. They will be removed
in a follow up PR.
=> map, program: deprecate ABI()

map.go
Add a getter for MapABI.Flags, so that we can deprecate MapABI without
losing access to Flags.
=> map: add a getter for Flags

elf_reader.go, internal/btf/ext_info.go
I noticed that the libbpf integration tests are extremely slow in the VM
compared to running them natively. Looking at a CPU profile shows that
we spend a lot of time in read syscalls. This is because reading from
an ELF section is not buffered.
Instrument the important places to use a buffered reader. The test time
in the VM drops from ~20s to less than one second.
=> use buffered I/O to cut down on read syscalls

internal/btf/btf.go, internal/btf/types.go
CO-RE has the concept of type "flavours", which are used to deal
with changes in kernel data structures. Basically, anything after
three underscores in a type name is ignored for the purpose of
finding a candidate type in the kernel's BTF.
Accomodate this by using the stripped name as the key to the
named type map, and adjusting FindType accordingly.
See https://facebookmicrosites.github.io/bpf/blog/2020/02/19/bpf-portability-and-co-re.html#dealing-with-kernel-version-and-configuration-differences
=> btf: handle type name flavours

cmd/bpf2go/main.go
Go 1.16 will add file embedding via magic comments, which we can use to
store the .o file instead of stuffing it into a global. Move the
compiled object file next to the .go to simplify this in the future.
=> cmd/bpf2go: output ELF .o next to the .go file

abi.go, cmd/bpf2go/tools.go
Remove two functions which are unused after refactoring in b17e4fd67aaf and the removal of `CollectionABI` in b04f777e8ed0.
=> Remove two unused functions

internal/btf/ext_info.go, internal/btf/ext_info_test.go, internal/btf/fuzz.go
Add two targets for go-fuzz, for further experimentation. A short run already found an OOM condition, so I'm sure there is lots more to discover.
=> btf: add go-fuzz targets

internal/btf/types.go, internal/btf/types_test.go
FuncProto.walk currently takes a copy of FuncParam.Type since the
for loop implicitly makes a copy of the FuncParam value:
for _, m := range fp.Params {
m is a copy of the original param, so &m.Type is the address of a
temporary variable. Instead, iterate params using the index and
take the correct address. Also extend the tests to cover this case.
=> btf: avoid Type copy in FuncProto.walk

map.go, prog.go, syscalls.go
map: make RLIMIT_MEMLOCK error more specific
The current check for os.ErrPermission will also return true for EACCES,
which shouldn't trigger the memlock message. It also discards the
underlying error, which might break feature tests, etc.
Move the check and make it specific to EPERM.
program: try to be helpful when RLIMIT_MEMLOCK is too low
One of the most puzzling errors from BPF is EPERM when trying to load
a perfectly legitimate program into the kernel. Most of the time this
means that RLIMIT_MEMLOCK is too low.
Detect this case by checking whether the error from BPF_PROG_LOAD is
EPERM. Since EPERM may indicate other problems as well, only emit the
error mentioning rlimit if the verifier buffer is empty.
=> better error messages when RLIMIT_MEMLOCK is too low

map_test.go, prog_test.go
The tests for NewProgramFromFD and NewMapFromFD create new objects
from an existing map / program. This means that there are now two
internal.FDs for one actual file descriptor, e.g. 9. Since the FD
objects use runtime.SetFinalizer, we will invoke close(9) twice.
For the first call this is acceptable, but the second call to close
may affect a re-used fd 9. The net effect is that other tests start
failing with weird "bad filedescriptor" errors, since the finalizer
callback closed it.
Avoid this by removing the finalizer from  the "cloned" program and
map objects and then explicitly not closing them.
Fixes #168
=> fix spurious test failures due to closed fds

readme.md
Following https://github.com/cilium/ebpf/pull/173#pullrequestreview-537753499
=> readme.md: reference HTML version of Linux kernel BPF docs

elf_reader_test.go, info_test.go, internal/unix/types_linux.go, internal/unix/types_other.go
...and use it in MapSpec.Flags where appropriate.
=> internal/unix: add BPF_F_NO_PREALLOC const

internal/btf/btf.go, internal/feature.go, internal/feature_test.go, internal/unix/types_linux.go, internal/unix/types_other.go, link/syscalls.go, prog.go, syscalls.go
syscalls: simplify nested map feature test
We can detect support for nested maps using a single instead of three
syscalls.
internal: simplify FeatureTest
FeatureTest requires a function that returns `(bool, error)`. The
semantics of when to return what is a bit complicated, and difficult
for contributors to grasp. In essence, we need to represent three
states:
* we know that the feature is available
* we know that the feature is not available
* we don't know either
Switch FeatureTest to a `func() error`. I think this makes it easier
to write accurate tests.
=> Simplify feature tests

internal/btf/types.go, internal/btf/types_test.go
Give types a useful printable representation:
=== RUN   TestType/*btf.Void
types_test.go:121: void#0
=== RUN   TestType/*btf.Int
types_test.go:121: uint16#0[bits=3]
=== RUN   TestType/*btf.Pointer
types_test.go:121: pointer#0[target=#0]
=== RUN   TestType/*btf.Array
types_test.go:121: array#0[type=#0 n=0]
=== RUN   TestType/*btf.Struct
types_test.go:121: struct#0[""]
=== RUN   TestType/*btf.Union
types_test.go:121: union#0[""]
=== RUN   TestType/*btf.Enum
types_test.go:121: enum#0[""]
=== RUN   TestType/*btf.Fwd
types_test.go:121: fwd#0[struct "thunk"]
=== RUN   TestType/*btf.Typedef
types_test.go:121: typedef#0["" #0]
=== RUN   TestType/*btf.Volatile
types_test.go:121: volatile#0[#0]
=== RUN   TestType/*btf.Const
types_test.go:121: const#0[#0]
=== RUN   TestType/*btf.Restrict …
=> btf: add String method to Type

elf_reader.go, internal/btf/btf.go, internal/elf.go
btf: fix out-of-bounds panic
debug/elf doesn't seem to validate that section numbers are valid,
so we can trigger a crash here. Unfortunately I wasn't able to minimize
the crasher, so this change doesn't have an accompanying test.
Found using go-fuzz.
internal: add safe ELF file wrapper
Fuzzing the ELF loader isn't very succesful since it keeps crashing
in debug/elf. Most of the time the culprit is a call to elf.Section.Data().
This method allocates a buffer with a size taken from the ELF, which
can lead to outlandishly large allocations. It's not clear how to validate
elf.Section.Size since the code that creates the section doesn't know
the total length of the ELF.
Instead, add a wrapper that catches panics due to ELF parsing, and turns
them into errors. This isn't a fool proof solution …
=> fixes for ELF reader crashes found using go-fuzz

internal/btf/core.go, internal/btf/core_test.go, internal/btf/types.go, internal/btf/types_test.go
btf: port CO-RE relocation compatibility logic
coreAreTypesCompatible will be used to figure out if a particular target
(aka kernel) type can be substituted for a local type. coreAreMembersCompatible
will be used to figure out if we can relocate a load from a local type with
a load from a target type.
This code is based on Bryce Kahle's CO-RE work and derived from libbpf
under a BSD 2-Clause license.
Updates #114
btf: use a deque instead of a stack
For some of the CO-RE algorithms it's useful to get the first *Type
from the stack, rather than the last one. Implement a deque based on
a resizing ring buffer and use it instead of copyStack.
=> CO-RE: add type / field compatibility logic

link/link.go, link/link_test.go, link/raw_tracepoint.go, link/raw_tracepoint_test.go
link: check program type for raw tracepoints
Return a more useful error message when passing a program with
the wrong type. This is especially useful here because it's
easy to mix up tracepoints and raw tracepoints.
link: allow Update to return ErrNotSupported
Raw tracepoints don't allow updating the program, yet they use
the bpf_link infrastructure. Allow Update to return ErrNotSupported
for that reason.
=> raw tracepoint cleanups

example_sock_elf_test.go
Hi, congratulations on the cool project!
I was taking a look at the examples and (unless I'm missed something :-)), I think I found a bug. The logic for the network byte order conversion of  ETH_P_ALL does not seem to be good in `example_sock_elf_test.go`.
=> Fix little endian conversion of ETH_P_ALL in example

go.mod, go.sum
Changes since v0.5.2:
https://github.com/google/go-cmp/compare/v0.5.2...v0.5.4
=> go.mod: bump github.com/google/go-cmp to v0.5.4

asm/instruction.go, prog.go, prog_test.go
The kernel exposes a tag for each loaded program. This is just the truncated
sha1 hash of the BPF bytecode. We can use this to check whether a loaded
program corresponds to a ProgramSpec, for example to make sure that the
latest version of a program is loaded.
Add a function to asm.Instructions to calculate the tag and a helper to
ProgramSpec to call the function using the native endianness.
=> program: allow calculating the tag for a ProgramSpec

collection.go, collection_test.go
LoadAndAssing currently loads all maps and programs in the CollectionSpec,
whether the user is interested in them or not. This is problematic, since
loading a program requires more privileges than loading a pinned map.
By lazily loading maps and programs we allow the user to reduce the amount
of privileges needed. It also saves work.
Split out from #195
=> collection: lazily load maps and programs in LoadAndAssign

.semaphore/semaphore.yml, internal/btf/btf.go
Test on the new stable 5.10 kernel. Cut down on CI times by not
testing the full Go version x Linux version matrix. Instead,
test the latest kernel on the old Go version only.
=> Test on 5.10

info.go, info_test.go, map.go, prog.go
Currently the only way to access IDs is via Map.FD() and Program.ID().
In our use case this leads to a bunch of extra calls to BPF_OBJ_GET_INFO_BY_FD.
Expose the IDs on the Info structs, and mark the ID() functions as
deprecated. We can remove them in a little bit.
=> info: expose map and program ID

collection.go, internal/btf/btf.go, map.go, map_test.go, prog.go
map, program: delay loading BTF as long as possible
We currently try to load BTF into the kernel even when re-using a pinned
map. Instead, load BTF only when it is really required. This also fixes
"leaking" btf.Handle when directly creating a map with BTF via
NewMapWithOptions.
btf: treat EPERM as unsupported during feature detection
Loading an unprivileged socket filter that has been compiled with
debug info enabled fails since the BTF feature test returns EPERM.
However, the socket filter would work just fine without BTF enabled.
Treat EPERM in the BTF feature test to mean not supported.
This is a two edged sword: EPERM can be a transient condition, e.g.
a process may drop capabilities after executing haveBTF. It's not
clear to me whether this happens in practice. Since the library
will …
=> btf: delay loading and handle EPERM

map.go, map_test.go, marshalers.go, prog.go, types.go
Marshaling and unmarshaling map keys and values is quite complicated:
* Queues allow nil keys
* Some maps allow storing map and program fds
* But looking them up returns map and program IDs, not fds
* We allow passing unsafe.Pointer for "zero copy" lookups
The current implementation isn't careful enough about these
constraints. For example, Map implements BinaryMarshaler which
encodes the map fd as a host endian uint32. This representation
only makes sense when inserting into an ArrayOfMaps or similar.
Since we don't distinguish between keys and values, you can use
a *Map as a key and get the same behaviour, except that the
key ends up being the value of the file descriptor. This doesn't
make a lot of sense.
Add helpers on Map that should be used when marshaling or unmarshaling
keys and …
=> map: distinguish between keys and values when marshaling

map.go
Function IsNotSupported was removed in 3d1ea6a1b7a024a3b7559d3e168267a012646a82.
=> map: fix docu

ARCHITECTURE.md, CONTRUBUTING.md
Describe the high level architecture of the library and explain some
of the choices made so far. The goal is to have a document that only
has to change rarely, so types and files are linked only sparsely.
=> add an ARCHITECTURE.md

go.mod, go.sum, info.go, info_test.go, internal/syscall.go, internal/unix/types_linux.go, internal/unix/types_other.go
BPF can provide kernel internal statistics about how often a program was
called and its runtime in ns.
This PR adds the functionallity to enable the collection of these
statistics and provides a way to fetch them.
=> Statistics

prog.go
BPF_PROG_TEST_RUN returns EINTR if the test is interrupted by a
signal. Therefore we know that BPF_PROG_REST_RUN is supported if
we see EINTR.
Fixes #203
=> program: treat EINTR during BPG_PROG_TEST_RUN as supported

.semaphore/semaphore.yml, go.mod
Go 1.16 is released, so 1.14 is EOL. Bump the minimum version to 1.15 and change CI to use 1.16 by default.
=> Require Go 1.15 and test on 1.16

go.mod, go.sum, map.go, map_test.go
This is an inverse of the Pin method. Also, add a method to get Map's pinned path.
Signed-off-by: Aditi Ghag aditi@cilium.io
=> map: Add a method to Unpin maps

.semaphore/semaphore.yml, elf_reader_test.go, run-tests.sh
Refactor the libbpf integration tests a bit to enable running a single test invocation that generates coverage info. Submit it to coveralls.io since that is what cilium proper seems to be using as well.
=> CI: submit coverage info

internal/unix/types_linux.go, internal/unix/types_other.go, map.go, map_test.go, marshalers.go, syscalls.go, syscalls_test.go, types.go
As of kernel v5.6 batch methods allow for the
fast lookup, deletion, and updating of bpf maps
so that the syscall overhead (repeatedly calling
into any of these methods) can be avoided.
Add support for BatchUpdate, BatchLookup, BatchLookupDelete, and BatchDelete
as well as tests for all of the above.
Signed-off-by: Nate Sweet <nathanjsweet@pm.me>
=> Add BPF Batch Ops Methods

cmd/bpf2go/compile.go
Currently, clang generates invalid opcodes when kernel helper functions
are used in BPF programs and they are compiled without optimizations.
This case is not detected built time so it's better to add safer default
cflags, i.e., with optimizations.
=> bpf2go: add -O2 to default cflags

info_test.go
This PR fixes the stats test, which incorrectly
logged an error instead of failing out of the test
when stats were not enabled. This caused the test
to panic the whole test suite on the next invalid
function call.
Signed-off-by: Nate Sweet <nathanjsweet@pm.me>
=> ci: Fix Stats Test

map.go, map_test.go
When iterating a map, we first issue a GET_NEXT_KEY followed by a
LOOKUP_ELEM syscall. Depending on the map type these two return
different error codes.
A plain array returns ENOENT from GET_NEXT_KEY once you ask for
the key after max_entries-1. It returns ENOENT from LOOKUP_ELEM
when asking for max_entries.
A hash map never returns ENOENT from GET_NEXT_KEY, and sometimes
returns ENOENT from LOOKUP_ELEM if there was a concurrent deletion.
A sockmap returns ENOENT from GET_NEXT_KEY once you ask for the
key after max_entries-1. In contrast to the plain array it may
return ENOENT for any slot that doesn't contain a socket.
MapIterator contains an off by one error in the logic that protects
from forever iterating a hash map that is being modified concurrently.
We only allow max_entries-1 …
=> map: fix iterating empty sockmap

cmd/bpf2go/compile.go
Clang by default probes the kernel it is running on to determine whether
it can enable advanced features like 32 bit operations, which is kind of
similar to -march=native behaviour. This is a bad idea for ahead of time
compiled code, since there is no guarantee that the kernel we compile on
is older than the kernel we want to run on.
=> cmd/bpf2go: set -mcpu=v1 by default

ARCHITECTURE.md, cmd/bpf2go/doc.go, prog.go, types.go
PR corrects the currently dead link at the bottom of "Overview" in https://pkg.go.dev/github.com/cilium/ebpf/cmd/bpf2go#pkg-overview and adds a few very minor editorial changes to the documentation and comments.
=> correct bpf2go/example link

cmd/bpf2go/compile.go, cmd/bpf2go/main.go
Since 96fcfcf48d we include "-mcpu=v1" in the clang command line. The
bpf2go tests don't pass "-target bpf", so clang complains that the
flag is not recognized:
clang-9: warning: argument unused during compilation: '-mcpu=v1' [-Wunused-command-line-argument]
Add a new target argument to the compile function, and default to
"bpf" if no target is given.
=> cmd/bpf2go: pass -target bpf in tests

prog.go, prog_test.go
Currently, loading a program from BPFFS doesn't set it's pinned path
and IsPinned returns false.
=> program: fix LoadPinnedProgram not setting pinnedPath

.golangci.yaml, .semaphore/semaphore.yml, asm/func.go, asm/instruction.go, cmd/bpf2go/compile.go, cmd/bpf2go/output.go, internal/btf/btf_types.go, internal/btf/types_test.go, link/link_test.go, map.go, marshalers.go, perf/reader.go, perf/ring.go, prog.go, prog_test.go
@lmb As discussed. I'd like us to consider adding gocyclo, prealloc, gosec and maligned later, since some of them flagged a few things that I didn't understand at first glance, and some are more invasive.
PTAL!
=> Run golangci-lint in CI, address linter errors

internal/unix/types_linux.go, internal/unix/types_other.go, perf/reader.go
Replace the hard coded constants with the constants in sys/unix.
=> perf: use constants from sys/unix

internal/ptr.go, internal/unix/types_linux.go, internal/unix/types_other.go
As requested in https://github.com/cilium/ebpf/pull/265#discussion_r602169513.
@lmb
=> internal - use BytePtrFromString from stdlib in NewStringPointer()

.semaphore/semaphore.yml
CI runs are currently failing due to a Debian mirror going AWOL.
=> CI: apt-get update before installing dependencies

internal/unix/types_linux.go, internal/unix/types_other.go, link/kprobe.go, link/kprobe_test.go, link/perf_event.go, link/perf_event_test.go, link/tracepoint.go, link/tracepoint_test.go, run-tests.sh
This is a continuation of https://github.com/cilium/ebpf/pull/186. Finally got a Round Tuit!
I believe this addresses one of the bigger shortcomings of the lib (as demonstrated by the verbose tracepoint/kprobe examples that were merged recently), and has been written about in more than a few blog posts over the years. (recent example: https://est357.github.io/posts/cilium_iovisor) There was an issue in the old newtools repo for this that was lost in the migration, so it kind of fell off my radar.
After reaching out to the more prominent/active users of the go-perf package (https://github.com/acln0/perf/issues/30), we've concluded that having this in the lib might be preferable, especially given the tiny subset of go-perf functionality we actually need for ebpf. Additionally, go-perf still …
=> K(ret)probe and Tracepoint support

examples/go.mod, examples/go.sum, examples/kprobe/main.go, examples/tracepoint/main.go
Now using link's nice Tracepoint() and Kprobe() API instead of go-perf!
Also added some documentation in the tracepoint and kprobe examples, since it was quite sparse. This should make it clearer to newcomers.
=> examples/ - Update tracepoint and kprobe examples to use cilium/ebpf/link

internal/unix/types_linux.go, internal/unix/types_other.go, map.go, map_test.go, pinning.go, prog.go
The current implementation uses `os.Rename` which calls `rename` to overwrite an existing pinned path. If the new path already existed before the overwrite, it'll simply be replaced with this syscall. Hence, use the `renameat2` syscall instead that can disallow the replace behavior.
Note to reviewers: Do we want to expose an API that gives user the option to instead replace the new pinned path (i.e. call `renameat2 `with `RENAME_EXCHANGE`), which is the default behavior of the `rename`* syscalls?
Fixes: #263 
Suggested-by : @lmb
=> pinning: Disallow replace during pinning

elf_reader_test.go, internal/pinning.go, internal/syscall.go, internal/testutils/bpffs.go, internal/unix/types_linux.go, internal/unix/types_other.go, link/cgroup.go, link/cgroup_test.go, link/iter.go, link/iter_test.go, link/link.go, link/link_test.go, link/netns.go, link/netns_test.go, link/perf_event.go, link/raw_tracepoint.go, map.go, map_test.go, prog.go, prog_test.go, syscalls.go, types.go
BPF_OBJ_GET accepts the BPF_F_WRONLY and BPF_F_RDONLY flags. Especially
BPF_F_RDONLY is useful, since it allows unprivileged read-only access
to BPF objects. Allow passing flags when loading pinned maps and
programs.
=> map, program: allow passing flags when loading pinned object

link/perf_event.go, link/tracepoint.go
Try to clean up perfEvent even if it's leaked by setting a finalizer
on it.
=> link: set a finalizer on perfEvent

elf_reader.go, elf_reader_test.go, internal/unix/types_linux.go, internal/unix/types_other.go, map.go, prog.go, prog_test.go
Linux 5.10 added sleepable BPF programs.
Quoting uapi/linux/bpf.h:
"If BPF_F_SLEEPABLE is used in BPF_PROG_LOAD command, the verifier will
restrict map and helper usage for such programs. Sleepable BPF programs can
only be attached to hooks where kernel execution context allows sleeping.
Such programs are allowed to use helpers that may sleep like
bpf_copy_from_user()."
The sleepable BPF programs are used, e.g., with LSM hooks and these
are also detected using "lsm.s" ELF section. This commit adds that
capability to elf_reader too.
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>
=> prog: add Flags to ProgSpec

info_test.go, map.go
Initially written for trying to reproduce a CI flake of TestStats, this might be useful to have anyway.
=> info_test: BenchmarkStats for benching BPF runtime stats

.semaphore/semaphore.yml
The 5.9 series is not maintained anymore per kernel.org, remove it from
CI builds.
=> CI: remove 5.9

run-tests.sh
run-tests: run a custom command in the vm
Let the user specify the command to execute in the VM. This is useful
if you want to run only a subset of tests, for example.
run-tests: use go mod tidy
go mod download for some reason modifies go.mod. According to an upstream
Golang issue "go mod tidy" is the preferred command to prime the module
cache.
=> run-test.sh cleanups

collection.go, elf_reader.go, internal/btf/btf.go, internal/btf/core.go, map.go, prog.go, prog_test.go
We need a target BTF when calculating CO-RE relocations for a program and
when resolving attach targets for iterators and LSMs. By default this is
the BTF for the current kernel, which is searched for in a set of well-known
locations.
This is too inflexible: sometimes the kernel doesn't have BTF, so it has to
come from a separate file that isn't shipped by the distribition. The library
might also be used in a container where the canonical paths aren't available.
Allow specifing an io.ReaderAt in ProgramOptions which is used as the
target BTF for CO-RE relocations and to resolve attachment BTF IDs.
Fixes #254
=> program: allow specifying source of BTF

internal/elf.go, link/kprobe.go, link/kprobe_test.go, link/perf_event.go, link/perf_event_test.go, link/uprobe.go, link/uprobe_test.go
Closes https://github.com/cilium/ebpf/issues/277
TODO
=> link: implement uprobe/uretprobe

map.go, map_test.go
This error will be returned by NewMapWithOptions whether the spec for a
pinned map is incompatible with the actual instance of the map, in order
to allow the caller to properly detect this mismatch.
Fixes #289
Signed-off-by: Gilberto Bertin <gilberto@isovalent.com>
=> map: define new ErrMapMismatch error

cmd/bpf2go/api_test.go, elf_reader.go, elf_reader_test.go, internal/btf/btf_test.go, internal/btf/core.go, internal/btf/core_test.go, internal/errors.go, internal/ptr.go, internal/testutils/glob.go, internal/testutils/rlimit.go, linker.go, map.go, map_test.go, perf/reader_test.go, prog.go, run-tests.sh
elf: increase coverage of libbpf integration test
The libbpf integration tests currently only test the ELF loader, since
we never attempt to load the collection into the kernel. This leaves
out a good chunck of code, e.g. CO-RE relocation handling.
Attempt to load kernel selftests into the kernel. Since we don't want
to replicate the user space portion of the selftests we have to be
quite lax in what we consider an error. The following cases lead
to a skipped test:
* ErrIsNotSupported indicates that we've hit a known deficiency in the
library.
* syscall.Errno indicates that we've made it all the way up to loading
a map or program, but don't have the necessary set up code.
All other errors are considered bugs.
program: allow specifying a custom target for CO-RE relocations
We need a target …
=> Increase coverage from libbpf selftests

link/uprobe.go, link/uprobe_test.go
Help the user by returning an error when attempting to set a uprobe on a symbol provided by a shared object (library).
Bash's `readline` implementation can be a library call depending on the distribution. Use main instead.
Closes https://github.com/cilium/ebpf/issues/292, but needs a follow-up that allows the caller to specify an offset manually.
@lmb @mmat11
=> link: uprobe - mark shared library symbols as unsupported

Makefile, asm/instruction.go, asm/instruction_test.go, asm/load_store.go, linker.go, prog.go, prog_test.go, testdata/loader-eb.elf, testdata/loader-el.elf
Sometimes a user assumes that a ProgramSpec from a CollectionSpec can
be loaded with NewProgram instead of using NewCollection. This isn't
true unfortunately, and leads to a hard to understand error issued
by the verifier:
bad file descriptor: fd -1 is not pointing to valid bpf_map
We can catch an unresolved map reference when loading a program and
use that to give a better error message to callers of NewProgram.
Fixes #210
=> program: better error when loading a single program

run-tests.sh
To work around a qemu bug [1] we redirect stdin of virtme-run from
/dev/zero. This has the possible downside that a read from /dev/zero
always returns data. This means that anything reading stdin in the
VM will get a bunch of garbage.
Detect a closed stdin and replace it with an empty fifo.
1: https://github.com/amluto/virtme/issues/33
=> run-tests: use empty fifo instead of /dev/zero if stdin is /dev/null

collection.go, elf_reader_test.go
The loader currently tries to rewrite any dword-sized load with a
non-empty reference and a constant value of -1 to a map load. This
breaks when trying to rewrite a relocation generated by inline
assembly to MaxUint32 aka -1.
The fix is to check that the instruction has the correct source
register in addition to being a dword load.
=> collection: fix map load check when loading programs

CONTRIBUTING.md
Signed-off-by: Robin Gögge <r.goegge@outlook.com>
=> docs: add testing instructions to CONTRIBUTING.md

link/program.go
This allows callers to detect the underlying syscall error, which is
necessary for being able to implement safe fallbacks based on the error
during program loading and unloading. runc in particular needs this to
be able to implement BPF_F_REPLACE fallbacks correctly.
Ref: opencontainers/runc#3008
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
=> link: wrap errors for Raw{At,De}tachProgram 

examples/kprobe/main.go
Commit 1e7f01c7124c ("arch: support arm64") changed the example to
attach to sys_execve instead of __x64_sys_execve, but didn't update the
package godoc accordingly.
=> examples/kprobe: mention sys_execve in package godoc

internal/syscall.go, internal/syscall_test.go, map.go, prog.go, syscalls.go, syscalls_test.go
This commit allows the BPFMapCreate syscall wrapper and BPFMapCreateAttr
type to be used by other subpackages of the library while not publicly
exporting them. 
As discussed in #235 this will help me to move the code in #321 into its own subpackage.
To keep the PR small, I only addressed the function and type I need for now. 
Signed-off-by: Robin Gögge <r.goegge@outlook.com>
=> internal: export BPFMapCreate syscall wrapper

internal/unix/types_linux.go, internal/unix/types_other.go, map.go, syscalls.go, syscalls_test.go
Introduced in
https://github.com/torvalds/linux/commit/fc9702273e2edb90400a34b3be76f7b08fa3344b.
Signed-off-by: Chris Tarazi <chris@isovalent.com>
=> Add feature test for BPF_F_MMAPABLE maps

internal/unix/types_linux.go, internal/unix/types_other.go, map.go, syscalls.go, syscalls_test.go
Introduced in
https://github.com/torvalds/linux/commit/4a8f87e60f6db40e640f1db555d063b2c4dea5f1.
In Cilium, following the merge of https://github.com/cilium/cilium/pull/15546, we need to add this feature test as Maglev mode uses inner maps (map-in-map).
Signed-off-by: Chris Tarazi <chris@isovalent.com>
=> Add feature test for BPF_F_INNER_MAP maps

link/iter.go, link/iter_test.go, link/syscalls.go
We need to pass the target map fd in a separate struct to iterate
the elements of a map, e.g. for bpf_map_elem and sockmap iterators.
=> link: support creating bpf_map_elem iterators

internal/syscall.go, internal/syscall_test.go, syscalls.go
The library is inconsistent in how it wraps errors from syscalls. Sometimes it obscures the underlying error, sometimes it wraps it, sometimes it replaces it with a more specific error. This PR introduces a new approach:
- We always wrap errors returned by SYS_BPF. This means that err == unix.EFOO will never work.
- We always include the original errno when introducing a more specific error. This means that errors.Is(err, unix.EFOO) will always work.
This approach gives users access to syscall.Errno without painting us into a corner.
=> improve error wrapping

features/doc.go, features/map.go, features/map_test.go, internal/unix/types_linux.go, internal/unix/types_other.go, types.go
Currently only supports default bpfMapCreateAttr values, to showcase
basic functionality. Results are cached by a go map. Tests log durations
to see cache performance. Added some open questions and missing error
interface checks to the comments in the file.
Signed-off-by: Robin Gögge <r.goegge@outlook.com>
=> MapType probe API

link/kprobe.go, link/link.go, link/tracepoint.go, link/uprobe.go
The finalizer we set when attaching a perfEvent as a safety measure is potentially surprising to users. Our initial documentation was too vague, we need to explicitly state that losing the reference cuts off the event.
This change documents the consequence on Tracepoint and K(ret)probe.
@kris-nova @lmb
=> link: document losing references to K(ret)probe and Tracepoint objects

link/kprobe.go, link/uprobe_test.go
When running the uprobe tests, I noticed this was failing with my copy of Bash. Offset 0x12345 seems to contain a trap instruction and is rejected by prepare_uprobe(): https://elixir.bootlin.com/linux/v5.13.3/source/kernel/events/uprobes.c#L854
This patch changes the dummy offset to 0x1 and adds some error context to the slightly esoteric ENOTSUPP.
=> link/uprobe: handle ENOTSUPP from the kernel's prepare_uprobe()

link/link_test.go
Previous unit tests assumed that cgroupv2 was mounted at
/sys/fs/cgroup/unified. While this is usually the case for systems
supporting both cgroupv1 and cgroupv2, systems don't have to mount
cgroupv2 to that path, and systems that don't mount cgroupv1 usually don't
(or, at least, Fedora doesn't). This assumption broke unit tests on
systems where cgroupv2 was mounted elsewhere.
Fortunately /proc/mounts will list the cgroupv2 mount point with the
file system type of `cgroup2` which makes it convenient for locating the
cgroupv2 file system. Unit tests now lookup (once) the mount point instead
of assuming its location, fixing unit tests on modern Fedora systems.
=> Find the cgroupv2 mount point in unit tests

internal/testutils/cgroup.go, link/link_test.go, map_test.go, types.go
Currently, using "some_map->Lookup" on a PerCPUCGroupStorage only allows retrieving the first value of the per-cpu storage area. This PR adds the missing declaration.
=> Mark PerCPUCGroupStorage as per-cpu

elf_reader.go
Currently, the whole .maps section is checked for non-zero bytes, rejecting the whole ELF if it contains even a single non-zero byte.
This patch results in nicer error output and doesn't reject the whole program, which currently prevents us from mixing valid and invalid BTF map definitions in a single testdata ELF.
An extra check is added at the end of the function to ensure all bytes in .maps are accounted for with BTF metadata.
Also documented loadBTFMaps() a bit to clarify the rationale.
=> elf_reader: validate .maps ELF data one BTF map definition at a time

collection.go, elf_reader_test.go, link/freplace.go, link/freplace_test.go
This is necessary to be able to access it from package `link`.
=> Export `CollectionSpec.ByteOrder`

link/kprobe.go
The statement sp, err := unsafeStringPtr() declares a new variable sp
which shadows the original, which may result in the new variable sp is
collected before PerfEventOpen() is invoked.
=> link/kprobe: don't redeclare a new variable sp

collection.go
@lmb I ended up reinstating an equivalent of `done()` in `cs.finalize()`, since the `loader.maps, loader.programs = nil, nil` looked a little out of place and it wasn't immediately clear why these fields were nilled out.
=> collection: remove the abomination that is lazyLoadCollection

features/prog.go, features/prog_test.go, internal/syscall.go, prog.go, syscalls.go, types.go
With this commit we add `HaveProgType(pt ebpf.ProgramType) error`,
which allows to probe for available BPF program types. As with the
HaveMapType API, results are cached and probes run at most once.
Signed-off-by: Robin Gögge <r.goegge@outlook.com>
=> features: add HaveProgType API

features/prog_test.go
CONFIG_BPF_LIRC_MODE2 is now enabled in CI kernels, so unconditionally
enable this test.
@rgo3 
Follow-up to https://github.com/cilium/ci-kernels/issues/14.
=> features: prog_test - enable LircMode2 test

features/prog_test.go
As it turns out, some mainstream distributions (Ubuntu, for one) build with LIRC disabled, which also disables this prog type. To keep the test suite compatible with most hosts, make it optional once more.
cc @rgo3
=> features: prog_test - make LircMode2 test optional again

asm/instruction.go, linker.go, syscalls.go, syscalls_test.go
I met the `invalid func unknown#113` error yesterday when deploying bpf programs to a 4.19 kernel, and found that libbpf have this bpf_probe_read_kernel auto replacement feature when it loads program.
https://github.com/libbpf/libbpf/blob/master/src/libbpf.c#L6009
So I added this feature to this project and have it tested.
```
$ go test -run TestHaveProbeReadKernel
PASS
ok  	github.com/cilium/ebpf	0.003s
```
Please let me know if any problem with this implementation 🙇  Thanks a lot!
=> feature: add call fixups for bpf_probe_read_kernel, etc

marshalers.go
Using reflect.Sliceheader as plain struct violates the unsafe pointer
rule 6th.
=> Fix invalid usage of reflect.SliceHeader

README.md
since the channel was renamed yesterday from #libbpf-go to #ebpf-go
=> changed slack channel link

features/map.go, features/map_test.go, types.go, types_string.go
This seems to have been a typo that slipped in unnoticed. The old 'StructOpts' has been kept around as a deprecated alias
to preserve backwards-compatibility and will be removed in a subsequent release.
@mythi @rgo3
=> Rename 'StructOpts' to StructOpsMap

examples/uretprobe/main.go
```
uretprobe/main.go:69:25: not enough arguments in call to ex.Uretprobe
have (string, *ebpf.Program)
want (string, *ebpf.Program, *link.UprobeOptions)
```
=> examples: adapt uretprobe example to the new library version

collection.go, collection_test.go, elf_reader_test.go
Closes https://github.com/cilium/ebpf/issues/366.
Best reviewed per commit.
tl;dr
- deprecated Collection.Assign()
- `flattenStruct()` is now a discrete function in the form of `ebpfFields()`
- `assignValues()` now takes a validator function that can be used to reject the transaction before the struct's fields are actually `Set()`
- `interface{}` is now used instead of a `reflect.Value` for tracking assigned object uniqueness
=> Deprecate `Collection.Assign()`, refactor `CollectionSpec.(LoadAnd)Assign()`

info.go, info_test.go, internal/testutils/feature.go, syscalls.go
nr_map_ids was added to struct bpf_prog_info in v4.15. If we
specify a non-zero value for the field in kernels < v4.15 we'll get
an EINVAL from the syscall. This isn't covered by our testsuite since
we don't test against such a kernel, so strictly speaking we don't
have to support this. As per Hyrum's law it's probably better to
go the extra mile however.
=> program: don't retrieve map ids by default

perf/reader.go, perf/reader_test.go
Encourage the use of errors.Is instead.
=> perf: deprecate IsClosed

CONTRIBUTING.md
Slack channel was renamed from `#libbpf-go` to `#ebpf-go` on August 18, 2021 and the [README.md](https://github.com/cilium/ebpf/blob/master/README.md) was updated in 633cfda797d5f40410e02f072fdf772b397bb68d.
[CONTRIBUTING.md](https://github.com/cilium/ebpf/blob/master/CONTRIBUTING.md) was left untouched, so this PR updates the links in the contributing guidelines too.
=> Update Slack join and channel link in CONTRIBUTING.md

internal/btf/core.go, internal/btf/core_test.go
Handle floats according to upstream libbpf logic: https://github.com/libbpf/libbpf/commit/6b14cfa56eb87724d7c9d489ade6990dc2bc269a
=> btf: handle float relocation for CO-RE

README.md
Make the link to join the Slack more prominent.
=> readme: point users at Slack if they need help

internal/testutils/rlimit.go, internal/unix/types_linux.go, internal/unix/types_other.go, map.go, syscalls.go
This should implement the suggestion in https://github.com/cilium/ebpf/issues/290 if I understood it correctly.
Wasn't sure what package this would best live in, let me know if there's a better location/name.
Going to open another PR to update the examples once (if) this gets merged.
=> Utility function to remove memlock rlimit

link/uprobe.go, link/uprobe_test.go
Context: https://cilium.slack.com/archives/CKC55JL8L/p1629493947056900
I could reproduce the problem, after applying these changes (https://github.com/iovisor/bcc/blob/master/libbpf-tools/uprobe_helpers.c#L268, https://github.com/iovisor/bcc/pull/3519/commits/af3da2370e656e22383dc2f10aa6b1da7637d0ea), it works for me locally.
=> link/uprobe: fix offsets for statically linked binaries

go.mod, go.sum, internal/unix/types_linux.go
Closes https://github.com/cilium/ebpf/issues/407
This returns the original rlimit values overwritten during the syscall, making it safer to call concurrently.
=> internal/unix: implement RemoveMemlockRlimit() using prlimit(2)

README.md, internal/align.go, internal/unix/types_linux.go, internal/unix/types_other.go, map.go, marshalers.go, perf/ring_test.go, ringbuf/doc.go, ringbuf/reader.go, ringbuf/reader_test.go, ringbuf/ring.go, ringbuf/ring_test.go
=> BPF ring buffer

.semaphore/semaphore.yml, asm/instruction_test.go, run-tests.sh
We're at a stage where it's difficult to figure out what went wrong on CI,
since there are so many tests. Turn off verbose output for now.
=> CI: turn off verbose tests

internal/btf/btf.go, internal/btf/btf_test.go, internal/btf/ext_info.go, internal/btf/info.go
btf: add LoadRawSpec
btf: explain that target is optional for Fixups
btf: remove duplicate byte order check
coreRelocate already checks that the local and target byte order
match, no need to check twice.
btf: push byte order checking into ext_info
Make extInfo aware of its own byte order and move the check into
extInfo.MarshalBinary().
=> small btf fixes

map.go
libbpf uses `/sys/fs/bpf` as the default pinpath if the user doesn't specify
one. We'd better keep consistent with it.
```
static int build_map_pin_path(struct bpf_map *map, const char *path)
{
...
if (!path)
path = "/sys/fs/bpf";
...
}
```
Signed-off-by: Hao Lee <haolee@didiglobal.com>
=> map: detect map Name and PinPath separately

marshalers.go
This change avoids the allocations for bytes.Reader.
=> Add sync.Pool to reduce allocations for the default case in unmarshalBytes()

run-tests.sh
CI: run qemu with single CPU
Investigating #422 it seems like the sporadic crashed we see might be
related to giving qemu multiple CPUs. The only reason we have two vCPU
is that TestPerCPUMarshaling needs /sys/devices/system/cpu/possible to
have be at least two.
Instead of adding vCPU we can use the possible_cpus command line argument.
Updates #422
CI: use distinct exit codes
Use distinct exit codes in run-tests.sh to make it easier to discern
which command failed.
Switching to a single vCPU has also made the CI run faster!
=> CI: try to reduce flakiness

elf_reader.go, internal/btf/btf.go, internal/btf/btf_test.go, link/freplace.go, prog.go
Fix `btf.FindType` to return a pointer to the matching BTF type.
This will allow to get exactly the same type (same address) for multiple calls requesting the same type name.
Fixes #416
=> Fix btf.FindType to avoid copy

link/uprobe.go, link/uprobe_test.go
Context: https://cilium.slack.com/archives/C027KBX679U/p1631808389034700
The Go binary on Debian seems to be stripped:
```
SYMBOL TABLE:
no symbols
```
```
$ file /usr/lib/go-1.17/bin/go
/usr/lib/go-1.17/bin/go: ELF 64-bit LSB executable, ..., stripped
```
This PR is for skipping the test in such cases (assuming bash's `main` and Go's `main.main` always exists, it should be safe to do so)
cc @rockdaboot
=> link/uprobe: skip integration test when binaries are stripped

asm/instruction_test.go, cmd/bpf2go/compile_test.go, cmd/bpf2go/main.go, cmd/bpf2go/main_test.go, cmd/bpf2go/output.go, elf_reader.go, internal/btf/btf.go, internal/btf/ext_info.go, internal/btf/strings.go, internal/cpu.go, internal/testutils/bpffs.go, internal/testutils/cgroup.go, internal/version.go, link/iter_test.go, link/kprobe.go, link/link_test.go, link/perf_event.go, map_test.go
Go 1.16 announced [1] the deprecation of io/ioutil with (almost)
drop in replacements in io and os packages. This change moves to
use those replacements.
Note: io/ioutil going away was NOT announced but dropping it is
trivial and allows to reduce imports.
[1] https://golang.org/doc/go1.16#ioutil
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>
=> tree-wide: drop deprecated io/ioutil

features/map.go, features/prog.go, prog.go
Since it is possible to disable the GC, we cannot rely solely on the finalizers to close the file descriptors returned by BPFProgLoad or BPFMapCreate.
So, we always close them explicitly, if needed.
Fixes #373
=> Fix missing close of fds from BPF{ProgLoad,MapCreate}

examples/README.md, examples/ringbuffer/main.go
I noticed a link was broken and a couple examples were missing in the README
=> examples: fix README.md, add build tags in ringbuffer example

.semaphore/semaphore.yml, internal/testutils/rlimit.go, internal/unix/types_linux.go, internal/unix/types_other.go, map.go, prog.go, rlimit/rlimit.go, rlimit/rlimit_test.go, syscalls.go
We only need to raise RLIMIT_MEMLOCK on old kernels. Check whether
the kernel uses memcg accounting by lowering the limit to zero and
creating a small map.
=> make RemoveMemlockRlimit conditional on kernel version

examples/go.mod, examples/go.sum, examples/kprobe/main.go, examples/kprobe_percpu/main.go, examples/kprobepin/main.go, examples/ringbuffer/main.go, examples/tracepoint_in_c/main.go, examples/tracepoint_in_go/main.go, examples/uretprobe/main.go
Following #438, switch to the new rlimit package for conditionally bumping the memlock rlimit.
@folbricht
=> examples - convert to new rlimit package for memlock removal

link/btf_id.go, link/btf_id_test.go, prog.go
The attachBTFID links Tracing/LSM BPF programs which they attach to a btf_id.
=> Add BTFIDLink to support fentry/fexit/fmod_ret/tp_raw/lsm BPF programs

features/prog.go, features/prog_test.go
BPF Syscall programs need to be sleepable which is enforced by the
verifier. So we need to set the correct program flags before executing
the feature probe.
Fixes #464.
Signed-off-by: Robin Gögge <r.goegge@gmail.com>
=> features: fix HaveProgType(ebpf.Syscall)

run-tests.sh
I went down a rabbit hole of trying to squeeze out faster builds, TL;DR: not much success. I originally thought that we waste time on bzip2 decompression, but that turned out to be a red herring. It's just that semaphore UI gives dodgy timestamps in the log.
Using tgz vs. bz2 still makes sense and using curl with etags also avoids unnecessary downloads, so there is no harm in merging these.
=> various CI fixes

link/kprobe.go, link/kprobe_test.go, link/uprobe.go, link/uprobe_test.go
This option should simplify implementing `USDT` probes on top of `link.Uprobe`
=> link/uprobe: support ref_ctr_offset

examples/tracepoint_in_c/bpf/handler.c, examples/tracepoint_in_c/main.go
After working through the awesome tracepoint examples, I fixed a couple of formatting nits.
=> examples: minor tracepoint formatting

internal/epoll/poller.go, internal/epoll/poller_test.go, perf/reader.go, ringbuf/reader.go
The ringbuf package uses a copy of the perf epoll code. Move the code into
a shared package.
=> epoll: factor out poller

Makefile
Ref: https://github.com/cilium/ebpf/issues/479
Usage:
```
$ command -v podman
/bin/podman
$ CONTAINER_ENGINE=docker make container-all
docker run --rm --user "1000:985" \
...
$ make container-all
podman run --rm  \
...
$ CONTAINER_RUN_ARGS='--user "1000:985"' make container-all
podman run --rm --user "1000:985" \
...
$ CONTAINER_ENGINE=docker CONTAINER_RUN_ARGS='--name=cilium-ebpf' make container-all
docker run --rm --name=cilium-ebpf \
...
```
=> Makefile: prefer podman for container engine

asm/instruction.go, features/prog.go, prog.go, syscalls.go
This fixes a subtle bug where buf would always be reallocated if the program contains dword loads.
=> asm: add Instructions.SizeBytes() for convenience and readability

link/link.go, link/xdp.go, link/xdp_test.go
This new API: AttachXDP links an XDP program to an interface through BPF_LINK_CREATE.
=> Link: add XDP support

internal/cmd/gentypes/main.go, internal/sys/syscall.go, internal/sys/types.go, link/link.go, link/syscalls.go
link: simplify link feature test
Don't load a program to check for the presence of bpf_link, we can
just call BPF_LINK_CREATE with an invalid fd instead.
link: use sys constants
=> link: use sys types and simplify feature test

link/cgroup.go, link/cgroup_test.go, link/iter.go, link/iter_test.go, link/kprobe_test.go, link/link.go, link/link_test.go, link/netns.go, link/netns_test.go, link/raw_tracepoint.go, link/raw_tracepoint_test.go, link/tracing.go, link/tracing_test.go, link/uprobe_test.go, link/xdp_test.go
Add a function that allows loading any pinned link. This allows us to
deprecate all of the separate LoadPinned* functions. In the future we
can use LoadPinnedLink to build APIs that work with any kind of link.
=> link: add LoadPinnedLink

internal/btf/btf.go, internal/unix/types_linux.go, internal/unix/types_other.go
The function isn't just a wrapper for a function in `unix`. Move the code
to the single caller instead.
=> unix: remove KernelRelease function

internal/cmd/gentypes/.gitignore, internal/cmd/gentypes/main.go, internal/sys/types.go, prog.go, prog_test.go
This PR implements the BPF_PROG_BIND_MAP functionality. While in general every map can be bind to a program, `bpftool` will only output and interpret data as metadata if the map meets some criteria:
https://github.com/torvalds/linux/blob/66f4beaa6c1d28161f534471484b2daa2de1dce0/tools/bpf/bpftool/prog.c#L212-L219
=> implement BPF_PROG_BIND_MAP

internal/btf/btf.go, internal/btf/btf_test.go, internal/btf/ext_info.go, internal/io.go
This PR aims to improve the readability of the logic and obviates the need to call `r.Seek()` and `io.LimitReader()`. It is part of a larger effort to support multiple progs per ELF section, which also requires some changes to lineinfo/funcinfo/corerelo handling. Moving things around this way makes those patches a bit easier to digest. :)
Convenience methods were added to determine the absolute starting offsets of type info, string table, funcInfos, lineInfos and coreRelos within their respective ELF sections.
Documented all functions in ext_info.go.
---
Also added a benchmark over `ParseVmLinux` because I'd like to make this more efficient in the future. (:scream_cat: :scream_cat:)
```
λ  ebpf tb/buffered-section-reader ✓ go test -exec sudo ./internal/btf  -bench=. -benchmem -memprofile …
```
=> btf: buffered SectionReader, document BTF parsing, vmlinux benchmark

info_test.go, link/cgroup_test.go, link/iter_test.go, link/kprobe_test.go, link/link_test.go, link/netns_test.go, link/program_test.go, link/raw_tracepoint_test.go, link/tracepoint_test.go, link/tracing_test.go, link/uprobe_test.go, link/xdp_test.go, prog_test.go
Our tests very often create very simple BPF programs that just return 0. Add helpers for this, which allows us to remove a lot of identical code.
=> reduce test boilerplate

.semaphore/semaphore.yml
For some reason the coveralls integration accepts our reports, but doesn't
show a diff. The interface is also very confusing and hard to navigate.
Let's remove the integration.
=> CI: remove coveralls integration

cmd/bpf2go/compile.go, cmd/bpf2go/compile_test.go, cmd/bpf2go/main.go, cmd/bpf2go/main_test.go
llvm is often available in multiple versions, with binaries having the
major version attached as a suffix, for example clang-13. Since adding
stripping it's now necessary to pass two flags when using such
versioned binaries:
bpf2go -cc clang-13 -strip llvm-strip-13 ...
Add a heuristic which derives the version suffix from the clang binary
and uses that to look for llvm-strip. This allows skipping the -strip
flag in the example above.
=> cmd/bpf2go: infer llvm-strip suffix from clang binary

Makefile, cmd/bpf2go/test/doc.go, examples/cgroup_skb/main.go, examples/fentry/main.go, examples/go.mod, examples/go.sum, examples/kprobe/main.go, examples/kprobe_percpu/main.go, examples/kprobepin/main.go, examples/ringbuffer/main.go, examples/tracepoint_in_c/main.go, examples/uretprobe/main.go
It's not necessary to pass separate -strip flags since we have the
version suffix heuristic. Remove $BPF_STRIP from bpf2go invocations.
=> remove $BPF_STRIP from Makefile and bpf2go invocations

collection.go
xdpcap [1] used ProgramArrays to implement hooks in XDP programs.
So far, it's been possible to add an xdpcap hook without calling
into the library to patch the ProgramArray. The change to support
pre-populating tail call maps broke this, since we now don't allow
ProgramArrays which are loaded but not requested by the user.
However, this case it is OK for the ProgramArray to be closed since
there are no programs in it anyways. Make the error less strict by
allowing empty ProgramArrays to be unassigned.
1: https://github.com/cloudflare/xdpcap
=> map: allow empty ProgramArray to not be assigned

prog.go
Observed this while running kernel selftests without permissions.
Signed-off-by: Timo Beckers <timo@isovalent.com>
=> prog: don't panic when prog load EPERMs with empty verifier log

elf_reader.go, internal/btf/btf.go, internal/btf/btf_test.go, internal/btf/core.go, internal/btf/format_test.go, internal/btf/types.go, internal/cmd/gentypes/main.go, link/tracing.go, prog.go
This patch adds two querying primitives to btf.Spec:
- `TypeByID()` looks up a `btf.Type` by its ID in the btf.Spec
- `TypesByName()` returns a list of `btf.Type`s that satisfy the given essential name. This can be used to obtain all CO-RE flavors of a struct, to perform a quick lookup without retaining the result, or if the kind or signature of the type you're looking for is not known up front.
In order to simplify the internal graph bookkeeping, harmonize on a single `btf.Type` interface all BTF types must implement instead of the `Type` and `NamedType` interfaces. This facilitates implementing an intuitive API for querying the graph.
Further document the purpose of `essentialName()`.
=> btf: rename FindType to TypeByName, add TypesByName and TypeByID methods

internal/btf/btf.go, internal/btf/btf_test.go, internal/cmd/gentypes/main.go, internal/io.go, prog_test.go
Allow passing BTF not wrapped in an ELF to LoadSpecFromReader. This
allows users to use external BTF for vmlinux, which is usually shipped
without the ELF.
=> btf: support raw BTF in LoadSpecFromReader

map.go, prog.go
s/bay be to low/may be to low/
=> map, prog: fix typo in MEMLOCK error string

cmd/bpf2go/main.go, cmd/bpf2go/main_test.go
This allows to invoke `bpf2go` to build for the native architecture and
have `__TARGET_ARCH_xxx` defined based on `GOARCH` without having to
derive the  architecture e.g. as part of the build system.
For example this would be useful in github.com/cilium/pwru:
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target native KProbePWRU ./bpf/kprobe_pwru.c -- -DOUTPUT_SKB -I./bpf/headers
=> cmd/bpf2go: allow to specify native target

asm/dsl_test.go, asm/instruction.go, asm/jump.go, asm/opcode.go, asm/opcode_string.go, asm/opcode_test.go, linker.go
The unused 0x6 class now represents jumps with 32bit comparisons:
https://lore.kernel.org/all/1548523574-18316-16-git-send-email-jiong.wang@netronome.com/T/
http://patchwork.ozlabs.org/project/netdev/list/?series=88386&state=*
This complements 32bit ALU operations by allowing comparisons without
having to sign extend registers beforehand.
Add a Jump32Class to represent this. As some JumpOps are not supported
by Jump32 (Call, Exit, Ja), centralize the logic for validating jump
OpCodes in OpCode.JumpOp().
=> asm: Add Jump32 support

asm/instruction.go, collection.go, elf_reader.go, elf_reader_test.go, internal/btf/btf.go, internal/btf/btf_test.go, internal/btf/core.go, internal/btf/core_test.go, internal/btf/ext_info.go, internal/btf/ext_info_test.go, linker.go, linker_test.go, prog.go, prog_test.go
This patch adds support for emitting multiple eBPF functions/programs
to the same ELF section.
Significant changes were necessary, both to the BPF linker and the BTF
ext_info parser, as previously most of the code (rightfully) made the
assumption that one ELF section equaled one BPF function. In order to
remove this limitation, all 'offset' logic that used to track positions
within an ELF section had to be modified to track positions within a
function body instead.
Secondly, in order to reassemble instruction streams and BTF func_infos,
line_infos and also CO-RE relocations back into a flat format the kernel
expects, the linking logic had to be broken up into smaller pieces.
This allows the instruction linker and the BTF extinfo linkers to
operate on the same source of truth, so they can …
=> elf_reader,btf: support multiple programs per ELF section

internal/btf/btf.go, internal/btf/btf_test.go, internal/btf/core.go, internal/btf/types.go
Change AnyTypesByName so that essential names stay an implementation
detail of the btf package: we need spec.namedTypes for fast
flavour lookup, but it's not clear that we should expose the flavour
name distinction to the users.
Fix this by only returning types which have an exact name match. This
means that `AnyTypesByName("ambiguous")` does not return ambiguous___flavour.
=> btf: only return exact matches from AnyTypesByName

internal/cmd/gentypes/main.go, internal/sys/types.go, link/cgroup.go, link/link.go, link/link_test.go, link/netns.go, link/netns_test.go, link/perf_event.go, link/raw_tracepoint.go
This PR is related to issue #506 
- add new method: Info() (*RawLinkInfo, error) to Link interface.
- add bpf_link_info union member types to types generator.
- update sys/types with generator.
- add info method to types that they don't support.
- enhance a few tests to cover info. (needs to add more) 
- fix NetNsInfo type.
=> link: expose link info with type-specific information

info.go, internal/btf/info.go, internal/errors.go, map_test.go, prog.go, prog_test.go
Also document availability of tag and name fields somewhere it's not lost on the user.
=> info: Use unix.ByteSliceToString instead of internal.CString

map.go, types.go
In libbpf commit 962f24137978 ([0]), we teach libbpf to recognize
BPF maps that do not support BTF-defined key/value and remove
BTF type IDs quietly on map creation. Make ebpf library support
this feature.
[0]: https://github.com/libbpf/libbpf/commit/962f24137978bf3321bed97785bae59b5a3f3b06
=> Remove BTF type IDs on map creation if not supported 

rlimit/rlimit.go
In an unprivileged process, the restore operation will always fail with EPERM, since oldLimit.Max is always zero at the start of the function. Once Max has been lowered, it's not possible to restore it without permissions.
This patch adds an extra Getrlimit call to obtain an appropriate value for Max so it is never blindly lowered to zero.
Not sure if there are any other solutions, but IMO this is fine because the detection logic now runs as `init()`, meaning no other Go code can manipulate rlimit concurrently. Any potential clashes would have to be caused by external programs.
=> rlimit: avoid lowering Max rlimit

asm/instruction.go, asm/instruction_test.go
This still needs to be fuzzed, but the gains are nice so far:
```
name                    old time/op    new time/op    delta
Read64bitImmediate-16      479ns ±12%      74ns ± 1%  -84.62%  (p=0.008 n=5+5)
Write64BitImmediate-16     417ns ±10%      63ns ± 2%  -84.97%  (p=0.008 n=5+5)
name                    old alloc/op   new alloc/op   delta
Read64bitImmediate-16      32.0B ± 0%      8.0B ± 0%  -75.00%  (p=0.008 n=5+5)
Write64BitImmediate-16     24.0B ± 0%      8.0B ± 0%  -66.67%  (p=0.008 n=5+5)
name                    old allocs/op  new allocs/op  delta
Read64bitImmediate-16       4.00 ± 0%      1.00 ± 0%  -75.00%  (p=0.008 n=5+5)
Write64BitImmediate-16      3.00 ± 0%      1.00 ± 0%  -66.67%  (p=0.008 n=5+5)
```
The use of `internal.DiscardZeroes{}` was considered for checking for …
=> Eliminate binary.Read in instruction (un)marshaler

asm/instruction.go, asm/instruction_test.go, info.go, internal/cmd/gentypes/main.go, internal/sys/types.go, prog_test.go
Allow introspecting instructions after they have been translated by and loaded into the kernel.
Just putting this up here for discussion, I remember there being some prior discussion around this a while back.
---
There's also the following cosmetic bug:
```
tail_main:
0: LoadMapPtr dst: r2 fd: 226
```
226 is the map's BPF ID, not its fd. Not sure if this needs to be taken into account.
=> program: retrieve xlated Instructions from Program

internal/unix/types_linux.go, internal/unix/types_other.go, link/socket_filter.go, link/socket_filter_test.go
Adds support for attaching Socket Filter programs to raw sockets. It would look like this:
```go
link.SocketFilterAttachProgram(conn, objs.Filter)
link.SocketFilterDetachProgram(conn)
```
Any feedback is welcome. I'll also provide an example.
=> Support attaching SocketFilter programs to raw sockets

elf_reader.go, elf_reader_test.go, map.go
This avoids allocating a bytes.Reader for every MapSpec, as its presence is rather uncommon.
This is a breaking change that needs to be documented in the release.
=> map: make Map.Extra field a pointer to a bytes.Reader

perf/reader.go, types.go
These were deprecated and scheduled to be removed in 0.8.0.
https://github.com/cilium/ebpf/pull/397: `IsClosed()`
https://github.com/cilium/ebpf/pull/381: `StructOpts`
=> Deprecate StructOpts and perf.IsClosed()

collection.go, elf_reader.go, elf_reader_test.go
Since the caller doesn't have access to programStub or mapStub, manually populating a MapSpec.Contents with inner maps or programs was not possible.
This patch eliminates the programStub and mapStub types in favor of normal strings so references to other progs/maps in the same CollectionSpec can be added (or changed) by the caller.
=> coll,elf: use string references to inner maps/progs in MapSpec.Contents

internal/btf/btf.go, internal/btf/btf_test.go, internal/version.go, internal/version_test.go
In vmlinux ELFs, symbol values are (virtual) memory addresses and don't necessarily correspond to offsets within ELF sections or even files.
For example:
```
~ llvm-objdump -t /usr/lib/modules/*/build/vmlinux | head -5
/usr/lib/modules/5.15.17-1-lts/build/vmlinux:	file format elf64-x86-64
SYMBOL TABLE:
ffffffff81000000 l    d  .text	0000000000000000 .text
```
Explanation on why this is the case: https://0xax.gitbooks.io/linux-insides/content/Theory/linux-theory-2.html#vmlinux
Remove the check as the MaxU32 assumption no longer holds. This allows the caller to specify an unstripped vmlinux TargetBTF and would result in correct fallback behaviour to one of the files in /boot, /lib and /usr as specified in loadKernelSpec(), which is currently also broken as a result.
=> btf: remove symbol value bounds check to support vmlinux ELFs

asm/instruction.go, features/misc.go, features/misc_test.go, linker.go, linker_test.go, prog.go, prog_test.go
Extend the features API with macros. So similar to`bpftool feature probe macros` one can now check if large instructions, v2 or v3 ISA or bounded loops are supported.
=> features: add misc probes

asm/opcode.go
Removed use of the confusing term 'constant'. The term 'immediate' is more appropriate when describing memory/register values embedded in the instruction stream.
Also, Ld(X) and St(X) appear to have been reversed. The X variants operate on memory, the non-X ones operate on registers. Use both 'load' and 'store' to describe the respective classes.
=> asm: correct opcode Class descriptions

asm/instruction.go, features/doc.go, features/map.go, features/misc.go, features/misc_test.go, features/prog.go, linker_test.go, prog_test.go
Best reviewed per commit.
These are some changes I'd liked to see in #541, but did not have the bandwidth to review at the time. apologies.
The function documentation was getting a bit repetitive to my liking, I think it fits better in the package doc, with any exceptions (currently none) documented on the function in question.
I don't feel very strongly about `ErrUnsatisfiedProgramReference`, but it's potentially confusing during troubleshooting, so IMO it's better to be specific.
=> features: centralize error semantics, remove maxMiscType, etc.

asm/instruction.go, features/misc.go, features/misc_test.go, internal/feature.go, linker.go, prog.go
See commit messages.
The ISA probes didn't match the bpftool ones and the test skips were all off by one kernel release.
=> asm,features: unexport jump fixup, fix misc probes and tests

internal/btf/btf.go, internal/btf/ext_info.go, linker.go, prog.go
Prompted by https://github.com/cilium/ebpf/pull/567/files#r805999952
Make it so that FuncInfo and LineInfo don't expose the BTF wire format outside of the package, and decode FileName, Line, etc. I used getters to avoid users being able to modify `LineInfo.FileName` and expecting that to show up in BTF.
Somewhat WIP since I need to write better commit descriptions.
cc @dylandreimerink
=> Hide BTF wire format of FuncInfo and LineInfo

cmd/bpf2go/output.go, collection.go, collection_test.go, elf_reader_test.go
In preparation of renaming the btf.Spec type itself down the line, once .BTF.ext data has been lifted into per-insn metadata, cement the interface that will be used to query the CollectionSpec for its type information.
A CollectionSpec now provides Maps, Programs and Types.
---
Also fix CollectionSpec.Copy() not copying Types.
=> collection: Rename CollectionSpec.BTF to .Types, copy in Copy()

prog_test.go
To prepare for Instruction no longer being comparable, remove the only test that directly compares Instructions. Comparing instruction streams should be done using Instructions.Tag().
Re-introduce a map load as in 9c06a484cfd5e6f184a2945f8196c0ad27e9c87d, as it was removed to avoid having to overwrite the map fd with an id in xlated insns.
cc @dylandreimerink @lmb
=> prog_test: compare BTF program tags instead of raw insns

collection.go, collection_test.go
Copying btf.Spec requires updating Map/Program.BTF.(S,s)pec, which gets complicated due to btf.Map/Program being pointers.
Instead of implementing a full deep-copy, avoid copying btf.Spec for now, since it's considered read-only. Since we're planning to get rid of btf.Program/Map anyway, this would not be worth the investment.
Add a test that loads both a copy and an original CollectionSpec.
=> collection: don't copy btf.Spec in CollectionSpec.Copy()

features/version.go
In order to allow userspace to determine the value used for LINUX_VERSION_CODE at compile time, expose the constant here.
This is useful when building eBPF objects at runtime.
Supersedes #570
=> features: add LinuxVersionCode function to obtain LINUX_VERSION_CODE

asm/dsl_test.go, asm/instruction.go, asm/instruction_test.go, asm/jump.go, collection.go, collection_test.go, elf_reader.go, elf_reader_test.go, example_sock_extract_dist_test.go, features/misc.go, info.go, linker.go, linker_test.go, prog.go, prog_test.go, ringbuf/reader_test.go
This PR is a sub-set of the changes originally presented in #567. That PR became bloated and hard to review, this PR contains less drastic changes which can be merged into master independently of the rest of the features.
=> Moved Instruction.Symbol and Instruction.Reference into per-instruction metadata

asm/instruction.go
See individual commits. With... methods were split making navigation more difficult than it should be, so they were moved. It's time to split up the file, too.
Having to check for a nil metadata is tedious, error-prone and hurts readability. All naked metadata reads were replaced by nil-safe accessors so nil checks are not necessary. Metadata only needs to be copied and set if the passed-in value differs from the default field value, which significantly simplifies the `With*` methods.
fyi @dylandreimerink
=> asm: remove explicit metadata nil checks

asm/instruction.go, asm/instruction_test.go, collection.go, elf_reader.go, linker.go
This PR improves the existing per-instruction metadata, as discussed in #564 and fixes #515.
This PR moves the existing `Instruction.Reference` and `Instruction.Symbol` metadata to a separate struct called `metadata`. `asm.Instruction` now has a pointer to this `metadata` struct. The `Instruction` struct now has exported getters and setters to get and modify this metadata. The design is such that we only assign metadata to instructions if we have to, since most instructions don't have metadata.
Copying instructions will not automatically copy the metadata since `Instruction` has a pointer to metadata. Therefor the setters will perform a copy-on-write, so upon the first modification of metadata, the instruction will get a new metadata object which is copied from the existing one and then …
=> Add add sparse per-instruction metadata 

internal/btf/btf.go, internal/btf/core.go, internal/btf/core_reloc_test.go, internal/btf/core_test.go, internal/btf/ext_info.go, linker.go, prog.go
CO-RE/CORE is an acronym, consistently name it that way.
Missing program BTF should not be silently ignored in `collectCORERelos()`, so make it return error.
=> btf: rename 'Core' to 'CORE'

elf_reader.go, linker.go, linker_test.go
Best reviewed per commit.
`splitSymbols()` makes splitting Instructions much more convenient.
Extracted relocation loading out of `LoadCollectionSpecFromReader`.
Refactored `loadFunctions()` to allow Line/FuncInfo and CORERelos metadata tagging to be added there without making the function more unwieldy than it already was.
Prep work for https://github.com/cilium/ebpf/pull/594.
=> elf_reader: add splitSymbols(), refactor loadFunctions()

link/kprobe.go
Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>
=> link/kprobe: Allow `.` in symbol name

.semaphore/semaphore.yml
Go 1.18 was just released, switch CI to use it. We don't have an urgent need
for 1.18 in the library itself, so we can wait a bit before requiring 1.17.
This gives users more time to get the new Go via the usual distribution
channels.
=> CI: use Go 1.18

link/kprobe.go, link/kprobe_test.go, link/link_test.go, link/perf_event.go, link/uprobe.go, link/uprobe_test.go
Centos 8 (kernel 4.18) has kprobe PMU, but don't allow `.` in symbol name,
add a new option to workaround this.
=> kprobe: fall back to tracefs if kernel doesn't support dots in PMU symbol

internal/btf/core.go, internal/btf/core_test.go
Small cleanup from the bitfield PR. @joamaki your first idea with the boolean really is the easiest.
btf: inline FixupKind into COREFixup
Having a boolean to skip local validation is the simplest thing to do,
after all. Remove FixupKind and inline the boolean into COREFixup, but
invert the default. We want fixups to be validated by default instead
of the inverse. This also fixes a regression from the introduction of
FixupKind, where too many fixups have their validation skipped.
btf: unexport COREFixup members
COREFixup is public since it is referenced by COREFixup, but there is no need to
for the members to be public. Unexport them.
=> btf: inline FixupKind into COREFixup

link/kprobe.go, link/kprobe_test.go
This patch adds kprobe symbol offset and its unit test.
With symbol offset, we can insert kprobe for functions
inlined.
[PR closed https://github.com/cilium/ebpf/pull/613]
Signed-off-by: Tonghao Zhang <zhangtonghao@didiglobal.com>
=> link/kprobe: specify symbol offset

internal/btf/btf.go, internal/btf/btf_test.go, internal/io.go
We currently read all BTF into memory before starting decoding. This is wasteful,
especially for the large-ish string table. Be a bit more clever to remove intermediate
copies.
name            old time/op    new time/op    delta
ParseVmlinux-4     107ms ± 7%      77ms ±13%  -27.98%  (p=0.029 n=4+4)
name            old alloc/op   new alloc/op   delta
ParseVmlinux-4     119MB ± 0%      93MB ± 0%  -22.20%  (p=0.029 n=4+4)
name            old allocs/op  new allocs/op  delta
ParseVmlinux-4      786k ± 0%      786k ± 0%   -0.01%  (p=0.029 n=4+4)
=> btf: reduce unnecessary copies when parsing BTF

asm/instruction.go, asm/instruction_test.go, asm/metadata.go, asm/metadata_test.go, elf_reader_test.go
asm: add Instruction Source metadata
This commit adds Source metadata to Instruction, which is data about
the origin of a series of Instructions. A Source can be any fmt.Stringer.
Instructions.Format will now print the source information in-line with the
Instruction on which it is set. This results in instructions being annotated
with original source code when loaded from an ELF file, or custom annotations
if fmt.Stringers are ssigned using Instruction.WithSource.
asm: use sparse metadata
Replace the struct based metadata with a linked list. This reduces the amount of memory
needed when the metadata is sparse, aka when there are more different kinds of metadata.
This also allows packages to have their own private metadata, which we'll use to store
BTF ext_infos.
The most common operation …
=> asm: add Instruction Source metadata

elf_reader.go, internal/btf/btf.go, internal/btf/btf_test.go, internal/elf.go
elf.File.Close has a strange API:
Close closes the File. If the File was created using NewFile
directly instead of Open, Close has no effect.
We inconsistently call elf.File.Close across the code base, but since
we always use NewFile whether we call close or not doesn't have an
effect. This is a problem in findVMLinux, as it relies
on elf.File.Close to do cleanup. Introduce a wrapper for elf.File.Open
so that Close works, and remove ineffectual calls to Close.
=> fix incorrect usage of elf.File.Close

Makefile, internal/sys/doc.go
Also regenerate syscall wrappers when generating code. This makes sure that CI
reproduces the checked in code 1:1.
=> Makefile: add internal/sys to generate target

internal/btf/btf.go, internal/btf/btf_types.go, internal/btf/types.go
This PR contains memory usage (and small cpu) improvements to `lawRawSpec` through:
- precomputing the amount of required fixups when building the type graph
- guess-timating the amount of types when reading the btf types reducing the amount of buffer reallocation
Benchmark:
```
>>> sudo go test -run=XXX -bench=BenchmarkParseVmlinux ./internal/btf
```
Before (master branch):
```
goos: linux
goarch: amd64
pkg: github.com/cilium/ebpf/internal/btf
cpu: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
BenchmarkParseVmlinux-4   	       9	 118640220 ns/op	96579569 B/op	  786353 allocs/op
PASS
ok  	github.com/cilium/ebpf/internal/btf	2.049s
```
After (updated after review):
```
goos: linux
goarch: amd64
pkg: github.com/cilium/ebpf/internal/btf
cpu: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz …
```
=> Memory improvements to `loadRawSpec`

internal/btf/btf.go, internal/btf/btf_test.go, internal/btf/ext_info.go, internal/btf/ext_info_test.go, internal/btf/fuzz_test.go, internal/btf/strings.go, internal/btf/strings_test.go, internal/btf/types.go
We currently read the string table into one big byte slice, and
allocate substrings in Lookup. This forces us to hang on to one
large allocation for the string table, and many small allocations
for substrings. Calling Lookup for the same offset also allocates
on each invocation.
Instead, split the string table into substrings at load time. In
Lookup we can then use a binary search to find the correct string.
As a result, both overall memory and allocations drop:
name            old time/op    new time/op    delta
ParseVmlinux-4    76.6ms ±12%    73.9ms ± 4%     ~     (p=0.343 n=4+4)
name            old alloc/op   new alloc/op   delta
ParseVmlinux-4    92.9MB ± 0%    84.3MB ± 0%   -9.22%  (p=0.029 n=4+4)
name            old allocs/op  new allocs/op  delta
ParseVmlinux-4      786k ± 0% …
=> btf: split string table ahead of time

internal/btf/types.go
Converting []rawType into []Type currently creates a lot of temporary
data in the form of fixups. They are necessary since a type may reference
itself, for example in a linked list:
struct node {
struct node* next;
...
}
No matter which order we encode struct node and struct node* in, we
can't resolve one of the types until we've inflated both.
However, such self referential types are rare. Most of the time we
are referencing an already inflated type. We can use this to our
advantage and perform fixups opportunistically. At the same time
we can split out type assertions from fixups, since most fixups
don't care about types at all.
name            old time/op    new time/op    delta
ParseVmlinux-4    68.9ms ± 2%    58.4ms ± 1%  -15.22%  (p=0.029 n=4+4)
name            old alloc/op   new …
=> btf: fix up inflated types immediately if possible

internal/btf/btf.go, internal/errors.go
Trim the log before converting it into a string will save an allocation.
Also document that BPF_LOAD_BTF never returns ENOSPC.
=> internal: make ErrorWithLog slightly more efficient

internal/btf/fuzz_test.go, internal/btf/types.go, internal/btf/types_test.go
btf: stop relying on TypeID when printing Types
Using the TypeID when printing is convenient, but it precludes us from
removing TypeID from the Type interface. Rework the printing code to
use the pointer address to identify a specific Type.
At the same time, make printing a lot more powerful. We now support
printing cyclical types without having to worry about infinite recursion.
For example, formatting a typedef with %v will now ouput
Typedef:"foo"[Pointer]
We can include details of Pointer by formatting with %1v:
Typedef:"foo"[Pointer[target=Void]]
Updates #643
=> btf: stop relying on TypeID when printing Types

internal/btf/btf.go, internal/btf/core.go, internal/btf/core_test.go, internal/btf/format.go, internal/btf/types.go, internal/btf/types_test.go, internal/cmd/gentypes/main.go
We currently have an unexported copyTypes function which allows transforming
a type graph before copying. This is very useful to strip qualifiers or
typedefs out of a graph. The function currently returns an error, since we
might not be able to remove all qualifiers, etc. in the case of deeply
nested or cyclical types.
Instead of returning an error, introduce an invalid sentinel Type "cycle" and
use it to signal that something went wrong. This allows removing the error return
which in turn allows us to extend Copy to the more powerful copyType paradigm.
=> btf: make copying types infallible

collection.go, collection_test.go, map.go
```
collection: Add MapReplacements to CollectionOptions
Add a new way to replace references to specific maps when creating a
new collection by introducing a MapReplacements field to the
CollectionOptions struct.
The goal of this functionality is the same provided by RewriteMaps(),
but this new approach plays nicely with bpf2go as https://github.com/cilium/ebpf/issues/517
is fixed.
```
Fixes https://github.com/cilium/ebpf/issues/517
=> collection: Add ReplaceMaps to CollectionOptions

collection.go
Some follow-ups to https://github.com/cilium/ebpf/pull/646.
Adds a deprecation notice to RewriteMaps().
Moves the Map(Spec) compatibility check out of the lazy-loading path.
cc @mauriciovasquezbernal
=> Deprecate CollectionSpec.RewriteMaps()

link/syscalls.go, prog.go
Discovered while running the test suite on kernel 4.14.
With the addition BPF_PROG_ATTACH tests in package link, the haveProgAttach feature test was added, gated on 4.10. This helper uses the AttachType field, which sets the bpf_attr expected_attach_type field, available as of 4.17.
There are more issues to address for 4.14, but this patch fixes these tests on kernels between 4.10 and 4.17.
cc @rgo3
=> syscalls: omit AttachType field in haveProgAttach

run-tests.sh
Let's add a botch since I've not made any progress with fixing the problem.
Retry running a test twice if we hit the error 42 condition and are
executing on CI.
The CI variable is set by Semaphore: https://docs.semaphoreci.com/ci-cd-environment/environment-variables/#ci
Updates #598
=> CI: retry two times on error 42

prog.go
Not all program types support PROG_TEST_RUN on all kernel versions. Previously, when testing a program type that didn't have a test runner implemented, the following error would be returned:
> Error when running: can't test program: can't run test: errno 524
Since this isn't overly descriptive, make it clear to the caller that the kernel supports test runs, just not for the particular program type.
=> prog: recognize ENOTSUPP in testRun()

info.go, link/link_test.go, map_test.go, prog_test.go
- Run `TestMapLoadPinnedWithOptions` as of 4.15
- Don't specify AttachType in `mustCgroupFixtures`
- Remove map pointer from `TestProgramInstructions`
Together with #657, this makes tests pass on our 4.14 ci-kernels image. To be enabled later when we move to self-hosted CI runners.
=> Assorted fixes for kernel 4.14

cmd/bpf2go/output.go, collection.go, elf_reader.go, elf_reader_test.go, internal/btf/btf.go, internal/btf/btf_test.go, internal/btf/core.go, internal/btf/core_test.go, internal/btf/ext_info.go, internal/btf/fuzz_test.go, internal/btf/types.go, linker.go, map.go, map_test.go, prog.go
btf: move CORERelocate to core.go
btf: add constructors for various *Info
Pull constructors for FuncInfo, LineInfo and CORERelocation out of
splitExtInfos. This makes the function smaller and makes removing it
later easier.
Instead of taking a *Spec in the constructors, take a []Type and
stringTable directly. This makes splitting ExtInfos out of *Spec
easier later on.
btf: track bpfCORERelo.InsnOff in instructions instead of bytes
This makes bpfCORERelo consistent with bpfFuncInfo and bpfLineInfo. It seems like
there is a latent bug here as well, since we used to subtract bpfFuncInfo.InsnOff
from bpfCORERelo.InsnOff, but for some reason the tests pass.
btf: store ExtInfos in instruction metadata
Use per-instruction metadata to store FuncInfo, LineInfo and CO-RE relocations.
As a result, …
=> Use instruction metadata to simplify linking and CO-RE relocation

internal/btf/core.go, internal/btf/core_test.go, internal/btf/ext_info.go, internal/btf/types.go, linker.go, prog.go
It's currently not possible to obtain COREFixups since coreRelocate
is not exported. The relocation process is already opaque to users,
and this makes it worse. To fix this we export coreRelocate and move
the bit that collects CORERelocation into ebpf proper.
=> btf: allow users to obtain COREFixups

internal/btf/core_reloc_test.go, internal/errors.go, internal/errors_test.go, linker.go, linker_test.go, prog.go, prog_test.go, syscalls.go, syscalls_test.go
```
The adjustments performed by fixupAndValidate() don't rely on CO-RE being
applied first. Execute it earlier in the chain to potentially avoid loading
BTF and executing CO-RE when we could bail out instead.
Also avoids having to touch test cases due to changes in a subsequent commit.
```
```
When trying to load a program containing bpf2bpf calls on a kernel that
doesn't support it, we bubble up the verifier error to the caller:
program xdp_prog: load program: invalid argument: unreachable insn 28
This is clear, but doesn't allow skipping tests when loading e.g. loader.c
on older kernels due to it containing bpf2bpf calls.
Implement a feature probe for bpf2bpf, return an unsupported error when
trying to load a program with multiple subprogs on an older kernel.
Update the test suite to …
```
=> Probe kernel bpf2bpf support

ringbuf/reader.go, ringbuf/reader_test.go
ringbuf: reduce allocations on the discard and busy paths
There is no need to wrap internal sentinel errors, since they are
never returned to the user. Not wrapping saves us some allocations.
ringbuf: reduce the number of epoll_wait calls
We don't have to call back into epoll_wait until we've read the
full contents of the ring buffer. This reduces the number of syscalls
made during busy periods.
=> ringbuf: reduce allocations and syscalls

btf/btf_test.go
FindType was renamed to TypeByName in commit 9b2180471cfe ("btf: rename
FindType to TypeByName, add AnyTypesByName and TypeByID methods").
Adjust the fatal message in TestTypeByName accordingly.
=> btf: report correct method in TestTypeByName fatal message

btf/btf.go, btf/btf_test.go, linker.go, prog.go
Some users of package btf might not want cache a parsed vmlinux to
avoid paying the memory cost associated with it, but this isn't possible
at the moment. Move the caching of vmlinux BTF into package ebpf.
=> btf: don't cache kernel BTF in LoadKernelSpec

asm/func.go, features/prog.go, features/prog_test.go, internal/unix/types_linux.go, internal/unix/types_other.go
`HaveProgHelper(pt ebpf.ProgramType, helper asm.BuiltinFunc) error`
allows to probe the available BPF helpers to a given BPF program
type. Probe results are cached and run at most once.
Signed-off-by: Robin Gögge <r.goegge@gmail.com>
=> features: add HaveProgramHelper API

prog.go
Avoid allocating an extraneous `bytes.Buffer` if we don't need to.
Followup from #647 .
=> prog: Avoid allocating for ctx if ctx not provided

btf/core_test.go, btf/types.go
The kernel refuses to load an array type without an index type, so probably
btf.rst is outdated.
=> btf: add Array.Index

link/link_test.go, link/uprobe.go, link/uprobe_test.go
Alternative to https://github.com/cilium/ebpf/pull/683
This PR, for a [bpftrace](https://github.com/iovisor/bpftrace) program like below:
```
#!/usr/bin/env bpftrace
uprobe:./main:"main.probeMe"+42
{
printf("rax: %d\n", reg("ax"));
}
```
enables probing without the need of recalculating the offset of `main.probeMe` (which is already calculated and stored inside [`offsets` field](https://github.com/cilium/ebpf/blob/951bb28908d23e50fca063a2d51098ca028352bf/link/uprobe.go#L46)), adding `0x2a` and setting `Offset` field to the resulting value:
```go
up, err := ex.Uprobe("main.probeMe", objs.ExampleUprobe, &link.UprobeOptions{RelativeOffset: 0x2a})
if err != nil {
log.Fatalf("creating uprobe: %s", err)
}
defer up.Close()
```
The PR also improves some of the comments because it's hard to …
=> Add `RelativeOffset` field to `UprobeOptions` struct

map.go
If a map creation fails and the max entries provided by the spec is
zero, it's likely that it's because of that zero value.
Help the user by suggesting that MaxEntries may be incorrectly set to
zero.
Signed-off-by: Mark Pashmfouroush <mark@isovalent.com>
=> map: suggest incorrect MaxEntries on EINVAL

link/kprobe.go
When getTraceEventID() or openTracepointPerfEvent() returns an error,
tracefs event (e.g. /sys/kernel/debug/tracing/events/<group>), which has
been created by createTraceFSProbeEvent(), is not cleaned up.
Signed-off-by: Chuang Wang <nashuiliang@gmail.com>
=> link: close tracefs event if perf event cannot be opened

.semaphore/semaphore.yml
This reverts commit 41f3f37fcc9c78455921445e7cb9e2cc3ac80afa.
We're now able to run apt-get without manually pulling CA certificates, and the
package we're trying to install has been removed.
=> Revert ".semaphore - workaround to update ca-certificates before apt-get update"

run-tests.sh
Not all systems have bash located at /bin/bash.
A better way to run bash with shebang is with:
`#!/usr/bin/env bash`
Signed-off-by: Mark Pashmfouroush <mark@isovalent.com>
=> run-tests: fix shebang to find bash more reliably

examples/map_in_map/main.go
This example demonstrates the use of maps in maps in pure Go.
There's also use of the BPF_F_INNER_MAP flag which allows for
inner maps to be sized dynamically.
Signed-off-by: Mark Pashmfouroush <mark@isovalent.com>
=> examples: add map in map example

btf/btf.go, btf/handle_test.go, btf/info.go
newInfoFromFd doesn't allocate an extra byte for the NUL character at
the end of the BTF name, hence the syscall fails with ENOSPC. Increase
the buffer size and add a test.
=> btf: fix NewHandleFromID and add test

map.go
When I use perf event map in MapReplacements for ebpf.CollectionOptions,
I'm getting error for maxEntries check.
The perf event map is created with maxEntries initialized to number
of cpus, so we can't check maxEntries before the map is created.
I'm not sure we can postpone the check, but we can surely skip it
for perf event map.
Signed-off-by: Jiri Olsa <jolsa@kernel.org>
=> map: Do not chec maxEntries for PerfEventArray map

internal/cmd/gentypes/main.go, internal/sys/types.go, prog.go, prog_test.go
Certain prog types (SK_LOOKUP, RAW_TRACEPOINT and
RAW_TRACEPOINT_WRITABLE) require that data_in is NULL. The previous
check prevented 0 length data_in.
Fix by removing check.
Followup from #647.
=> prog: Allow empty data for prog.Test and prog.Run

link/uprobe.go, link/uprobe_test.go
Both options currently have subtly different definitions. Kprobe.Offset is counted
from the start of the symbol, while Uprobe.Offset counts from the start of the
address space.
Rename UprobeOptions.Offset to Address and RelativeOffset to Offset. Existing
users of UprobeOptions.Offset will get an error when they first upgrade the
library, so make the error message even more explicit.
=> link: unify KprobeOptions.Offset and UprobeOptions.Offset

btf/format.go, btf/format_test.go, btf/types.go, btf/types_test.go
Contrary to the documentation in btf.rst a BTF_KIND_ENUM can carry a size.
This is used by the kernel to shrink the size of enums, for example:
enum netfs_io_source {
NETFS_FILL_WITH_ZEROES,
NETFS_DOWNLOAD_FROM_SERVER,
NETFS_READ_FROM_CACHE,
NETFS_INVALID_READ,
} __mode(byte);
=> btf: add Enum.Size

btf/btf.go, info.go, link/tracing.go, prog.go
Given a loaded program, it takes four calls to retrieve parsed BTF:
1. Program.Info()
2. ProgramInfo.BTFID()
3. NewHandleFromID()
4. btf.Handle.Spec()
This chain of calls has a subtle requirement: the loaded program
must be kept alive for steps 1-3, since otherwise the BTF ID might
be deallocated or reused by the kernel. Program.Handle encapsulates
these steps while keeping program alive.
=> program: add getter for btf.Handle

run-tests.sh
Stop suppressing error output from curl.
=> run-tests: show curl error messages

elf_reader.go
'Virtual' NOBITS sections like .bss always share an offset with another ELF section, but reading from them is expected to yield only NUL bytes.
Prior to Go 1.18, opening a NOBITS section would yield a reader into the overlapping 'real' section, dutifully returning its non-NUL bytes and potentially reading past the end of the underlying file reader if the size of the NOBITS section was large enough. This was addressed in CL#375216.
As both an optimization (in case of large .bss sections) and a workaround for this bug in Go versions 1.17 and earlier, only read data from PROGBITS sections, which all known LLVM versions use correctly. Return an error if a data section is not PROGBITS or NOBITS.
Addresses https://github.com/cilium/ebpf/pull/668#issuecomment-1190178017.
=> elf_reader: only read data from PROGBITS sections, ignore NOBITS

btf/btf.go, btf/btf_test.go, btf/handle.go, btf/handle_test.go, internal/cmd/gentypes/main.go, internal/sys/types.go, prog.go, prog_test.go
program: support tracing of kernel modules
Allow tracing functions in kernel modules via fentry, fexit, fmod_ret
and tp_btf programs. The behaviour follows libbpf and is transparent
to the user: if we can't find a target in vmlinux we attempt to find
it in any loaded kernel module.
Refactor TestProgramTypeLSM to test attaching via BTF. This removes
LSM tests for BPF_F_SLEEPABLE, since they don't excercise library
behaviour beyond passing ProgramSpec.Flags to the kernel.
Updates #705
btf: add FindHandle
Add a helper that iterates all BTF objects in the kernel and returns
the first one for which a user supplied callback returns true.
btf: allow passing *Type to Spec.TypeByName
=> program: support tracing of kernel modules

.semaphore/semaphore.yml, README.md, elf_reader_test.go
After https://github.com/cilium/ci-kernels/pull/24, now test the library against kernel 5.17.
@lmb @joamaki There's one remaining failing selftest:
```
--- FAIL: TestLibBPFCompat (0.01s)
--- FAIL: TestLibBPFCompat/netif_receive_skb.linked3.o (0.01s)
elf_reader_test.go:665: Error during loading: program trace_netif_receive_skb: apply CO-RE relocations: apply fixup target_type_id=67->16253: invalid immediate 73, expected 67 (fixup: target_type_id=67->16253)
```
Could this be a bug on our side? Nothing was changed to `netif_receive_skb.c` in over a year, so not sure why this broke now.
fyi @rgo3 
---
=> CI: Test against kernel 5.18

.semaphore/semaphore.yml
Push individual test results into the semaphore UI via gotestsum.
=> CI: expose individual test results

link/kprobe.go, link/kprobe_test.go
This is a follow-up to https://github.com/cilium/ebpf/pull/745.
No longer treat EINVAL from creating u/k(ret)probes as `os.ErrNotExist`, since EINVAL has many potential causes. This is a potentially breaking change, since callers scanning valid instruction offsets in symbols must now expect both `os.ErrNotExist` as well as `os.EINVAL`, depending on the kernel version and architecture.
Make errors shorter and more specific, e.g. 'bad insn boundary' no longer includes a 'not found' string. Token is now included in all errors, even unrecognized ones.
=> link: (u|k)probe: don't treat EINVAL as os.ErrNotExist

features/errors.go, features/map.go, features/misc.go, features/prog.go
```
In an attempt to simplify the switch blocks in all types of feature
probes, lift the arbitrary EPERM wrapping exception.
Also, move the call to fd.Close() out of the switch statement to live
closer to the call that returns the fd. The fd can always be immediately
closed.
```
```
Instead of relying on repeated calls to fmt.Errorf("...: %w", err) to ensure
we never return naked sentinels, add error wrappers at a few key locations.
This abstracts and centralizes the wrapping logic to make the probe logic
itself a bit leaner.
```
=> features: remove EPERM wrapping exception, automatically wrap errors

features/map.go, features/map_test.go, features/prog.go
Turns out this was never really blocking: https://github.com/cilium/ebpf/issues/344. Specifying any invalid vmlinux type id when creating a map is enough to get some information other than EINVAL.
=> features: implement probes for StructOps maps and programs

internal/epoll/poller.go, internal/epoll/poller_test.go, perf/reader.go, perf/reader_test.go, ringbuf/reader.go, ringbuf/reader_test.go
ringbuf: add SetDeadline
Analogous to perf.Reader, add ringbuf.Reader.SetDeadline.
ringbuf: stop leaking a goroutine during tests
perf: add test for Reader.SetDeadline
epoll: correctly handle out of bounds deadlines
Explicitly check for deadlines in the past and far future.
=> epoll deadline fixups

elf_reader_test.go, internal/cmd/gentypes/main.go, internal/sys/syscall.go, internal/sys/types.go, prog.go, prog_test.go, types.go
With the recent addition of verifier error summaries, there are fewer reasons for disabling verifier output altogether. The existing behaviour is somewhat underspecified and underdocumented. Logging behaviour hinges on both LogLevel and LogSize, with an undocumented -1 value for LogSize to disable the verifier log. This gets rather complex with the retry mechanism involved.
This patch removes the local logSize variable, sets opts.LogSize directly to the default value, and log behaviour is now controlled by LogLevel only. Disabling the verifier log altogether can be done by setting the LogDisabled ProgramOption.
A type LogLevel was added to reflect the kernel's own constants for requesting logs on either branch or instruction level, as well as the stats summary of the current verifier pass …
=> prog: unconditionally enable verifier retries, add consts, document LogLevel

prog.go
Fixing a minor typo in a comment for `ProgramSpec` field `SectionName`.
=> program: fix comment typo

cmd/bpf2go/output.go
`"io/ioutil" has been deprecated since Go 1.16`
=> bpf2go: replace deprecated io/ioutil function

features/map.go, features/map_test.go, internal/testutils/feature.go, internal/unix/types_other.go
`HaveMapFlag(flag uint32) error` would allow a user to probe running kernel for support for map flags.
The main target of this would be to probe for availability of mmapable array maps.
This PR could also be replaced by just exporting https://github.com/cilium/ebpf/blob/314c7732ecc76e7587edf487d1048fbc165983e3/syscalls.go#L91
=> features: add HaveMapFlag API

features/map.go, features/map_test.go, info.go, internal/cmd/gentypes/main.go, internal/sys/syscall.go, internal/sys/types.go, map.go
As requested in https://github.com/cilium/ebpf/pull/673 this PR defines a new internal type `sys.MapFlags` describing the different map flags constant, and use a re-exported version of it as the type argument for `HaveMapFlag` feature detection API
=> feature: define `sys.MapFlags` and re-export it for map flags feature detection

cmd/bpf2go/compile.go, cmd/bpf2go/main.go
Using tracing macros like PT_REGS_PARM1 causes an error when compiling for
generic targets bpf, bpfel and bpfeb:
offcpu.c:33:41: error: The eBPF is using target specific macros, please provide -target
This is confusing if the user already provides "-target bpfel" or similar.
Clarify that specific arch has to be selected for tracing to work.
See #772
=> cmd/bpf2go: clarify -target usage with bpf_tracing.h

link/kprobe.go, link/kprobe_test.go, link/perf_event.go, link/perf_event_test.go, link/uprobe.go
Instead of parsing the same files over and over, read them once and store
the result. This cuts down on unnecessary file I/O.
Fixes #744
=> link: memoize PMU event types read from sysfs

btf/btf_types.go, btf/core_test.go, btf/format.go, btf/format_test.go, btf/types.go, cmd/bpf2go/test/test_bpfeb.go, cmd/bpf2go/test/test_bpfel.go, internal/sys/types.go
btf: handle signed enums and fix default signedness
Enums now carry signedness encoded in the KindFlag, with the default being
an unsigned enum. This breaks our assumption that enums are signed by default.
Add Enum.Signed and switch EnumValue.Value to uint64. I used uint64 instead of
uint32 since we'll likely need 64 bits to support BTF_KIND_ENUM64 in the future.
Users of bpf2go that generated enums will see their generated types changing from
signed to unsigned types.
Updates #780
btf: reject invalid structs when formatting
GoFormatter currently outputs nonsensical padding given a struct definition
like the following:
&Struct{
Size: 1,
Members: []Member{
{Name: "foo", Type: &Int{Size: 2}, Offset: 0},
},
}
The reason is that the member is large than the enclosing struct. Return
an error …
=> btf: handle signed enums and fix default signedness

elf_reader.go
Adding support to load sleepable iterator program type,
defined by 'iter.s/...' section.
Signed-off-by: Jiri Olsa <jolsa@kernel.org>
=> iter: Add support to load sleepable iterator program type

prog.go
A recent patch[0] to the kernel prevents bpf_prog_test_run_skb() from running the bpf program with with an empty skb.  This makes the existing feature check fail, so to fix it an additional byte of input data is needed.
[0]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=fd1894224407c484f652ad456e1ce423e89bb3eb
I tried tracing through the kernel code, and to be honest I'm only partially confident that I understand the issue.  I can't quite find the place where the `skb->len` is getting reset to zero, because before the call to `convert___skb_to_skb()` is a call to `__skb_put()` with the size of the input data.  The patch I linked is essentially a good guess at the root cause.
I am confident that this issue is introduced in 5.15.65 …
=> Fix haveProgTestRun on kernel version 5.15.65

btf/core_reloc_test.go, collection_test.go, elf_reader_test.go, info_test.go, internal/prog.go, linker_test.go, perf/reader_test.go, prog.go, prog_test.go, ringbuf/reader_test.go
Centralize allocation of the buffer to avoid some duplication and ease future changes to the minimum buffer size.
The patch that introduced this regression doesn't officially land until 6.0, but it has already been backported to kernels as early as 5.15.65 (potentially even earlier?).
cc @dylandreimerink
=> Provide 15-byte context inputs to `Program.{Run,Benchmark,Test}`

btf/core.go, btf/core_test.go, btf/ext_info.go, btf/traversal.go, btf/types.go, btf/types_test.go, internal/deque.go, internal/deque_test.go, linker.go, prog.go
This is the first of three PRs to add BTF marshaling to the library, and does some groundwork. The second PR will contain the actual marshaling code, while the third PR has some more memory optimizations.
For the curious, the whole shebang is on [my btf-encoder branch](https://github.com/lmb/ebpf/tree/btf-encoder).
internal: move Deque
Move Deque from btf into internal and export methods. No other code changes.
btf: make typeDeque generic
Make typeDeque a generic container type so that we can re-use it
for postorderTraversal.
btf: avoid heap allocations when walking types
Type.walk() forces the typeDeque argument to always escape, since the escape analyzer has
to be conservative when dealing with interfaces. We can apply two tricks that reduce
allocations.
First, Type.walk() is replaced …
=> prep work for BTF marshaling

btf/format.go, btf/format_test.go, btf/types.go
We currently treat IntEncoding as if it was a set of flags, but the kernel and bpftool treat it like an enum. Additionally, clang doesn't generate Char encodings in the first place.
Remove the Is* methods on IntEncoding since they give users the wrong idea of how the type works. Tidy up GoFormatter to be more strict when outputting Int.
Updates #656
=> btf: fix IntEncoding

btf/format.go, btf/format_test.go
The latest code seems to have changed quite a bit so it was changed to:
[format.go#L185](https://github.com/Benjamin-Yim/ebpf/blob/fix_uint128/btf/format.go#L185)
```golang
...
case Unsigned, Signed:
stem := "uint"
if i.Encoding == Signed {
stem = "int"
}
if i.Size > 8 {
fmt.Fprintf(&gf.w, "[%d]byte /* %s%d */", i.Size, stem, i.Size*8)
} else {
fmt.Fprintf(&gf.w, "%s%d", stem, bits)
}
```
=> reopen may uint128 to [16]byte

.semaphore/semaphore.yml
Some recommendations from Semaphore support.
'sem-version' apparently installs Go, so rely on it instead of isntalling Go manually.
Execute 'cache restore' before 'go install' to avoid tar errors unpacking the cache archive:
```
Unpacking command failed: tar: /home/semaphore/go/pkg/mod/github.com/jonboulle/clockwork@v0.2.2/.github/workflows/ci.yml: Cannot open: File exists
tar: /home/semaphore/go/pkg/mod/github.com/jonboulle/clockwork@v0.2.2/.github/workflows/.editorconfig: Cannot open: File exists
tar: /home/semaphore/go/pkg/mod/github.com/jonboulle/clockwork@v0.2.2/ticker.go: Cannot open: File exists
...
```
=> Semaphore: remove manual Go installation, expedite 'cache restore'

cmd/bpf2go/main.go
In our project, the eBPF source files are named with underscores, like `ext_vx_decap.c`. We want to have the .go and .o files generated by bpf2go to follow the same naming scheme (e.g. `ext_vx_decap_bpfel.go`). But currently, when setting the `<ident>` parameter to `ext_vx_decap`, the result will be some broken Go type names like `type ext_vx_decapPrograms`
So instead, this PR adds a new `-filename-stem` flag, which allows specifying an alternative filename prefix while one can keep the `ident` as it is supposed to.
The `-filename-stem` flag is optional and if it's not set, the `ident` will be used instead. So this is not a breaking change.
Sample usage:
```
bpf2go [...] -filename-stem ext_vx_decap ExtVxDecap src/ext_vx_decap.c
```
=> bpf2go: add flag for alternative filename stem

README.md
- 'Officially' mention 'ebpf-go' as being a thing.
- Dropped the CF/Cilium notice as the project has received frequent and significant contributions from the wider community and was only partially relevant anymore. We no longer need it to convey the legitimacy of the project.
- Explicitly call out GH Discussions, which is has seen significant use so far.
=> README: update to reflect the project's situation in H2 2022

internal/unix/doc.go, internal/unix/types_linux.go, internal/unix/types_other.go
Document why the package exists, and how stubs will behave on non-Linux OS. Simplify constants for other OS by giving them a distinct but meaninless value. Always use type aliases for structs on Linux and remove boilerplate function comments.
=> internal/unix: add some documentation and tidy up stubs

map.go, prog.go
Looks like [docs.cilium.io/en/k8s-doc/admin/#admin-mount-bpffs](https://docs.cilium.io/en/k8s-doc/admin/#admin-mount-bpffs) link is broken. It redirects itself.
```
~ ❯ curl -L https://docs.cilium.io/en/k8s-doc/admin -v
< HTTP/2 302 
< location: /en/k8s-doc/admin/
curl: (47) Maximum (50) redirects followed
```
I updated the link as [https://docs.cilium.io/en/stable/concepts/kubernetes/configuration/#mounting-bpffs-with-systemd](https://docs.cilium.io/en/stable/concepts/kubernetes/configuration/#mounting-bpffs-with-systemd), I guess it's the correct one.
=> map, prog: fix broken links

prog.go, prog_test.go
Add more cross references betwen VerifierError and NewProgram* and reword the example to hopefully be more explicit.
=> program: clarify how to use VerifierError

internal/unix/types_linux.go, internal/unix/types_other.go, link/kprobe_multi.go
Kprobe multi support is gated on CONFIG_FPROBE, without it creating the link fails with ENOTSUP: https://elixir.bootlin.com/linux/latest/source/include/linux/fprobe.h#L56
Unfortunately the standard Debian sid kernel does not have it enabled.
Update the kprobe multi test to handle ENOTSUP, and drop the minimum kernel version check, tests otherwise fail with:
Feature 'bpf_link_kprobe_multi' isn't supported even though kernel v5.19.11 is newer than v5.18
=> link: Allow kprobe multi to be disabled in kernel

link/link.go, link/link_test.go
Map and Prog have IsPinned() func but RawLink doesn't have it. I added IsPinned() to RawLink. Also seems Unpin method of Rawlink doesn't have a test, I added it too.
=> Add IsPinned() to RawLink

internal/vdso.go
As reported by Daniel Xu, setting capabilities on an executable file will prevent reading /proc/self/auxv since the file is owned by root. The work arounds to this have various trade offs, so the best we can do is tell the user why we failed and hope they check out our discussion or create an issue.
See https://github.com/cilium/ebpf/pull/823
=> internal: detect if /proc/self/auxv is not readable due to file caps

btf/btf_types.go, btf/btf_types_string.go, btf/marshal.go, btf/types.go
Implement support for the BTF_KIND_ENUM64 added in Linux 6.0 kernels. As discussed in https://github.com/cilium/ebpf/issues/780, the idea is to reuse the existing Enum type for the new enum64 since it has been extended to fit 64 bit values.
The majority of this implementation has been compied over from the original enum implementation. btfEnum64 layout comes from https://docs.kernel.org/bpf/btf.html?highlight=btf#btf-kind-enum64.
Please review carefully, as I'm not super familiar with the requirements here. Mostly just working off of what's already been done for the original enum type.
Fixes #780
=> btf: support enum64

asm/instruction.go, asm/instruction_test.go
When replacing an Instruction in an Instructions parsed from an ELF, preserving Metadata is important, so this patch adds a convenient method for in-line assignment of Metadata from other instructions.
With func_info and line_info marshaling being driven by Metadata, accidentally stripping a func_info from the first Instruction will result in the following verifier error:
`invalid argument: missing bpf_line_info for func#0`
The verifier rejects line_infos for subprogs that don't start with a func_info.
cc @rgo3
=> asm: add .WithMetadata() for conveniently replacing individual Instructions

prog.go, prog_test.go
Truncate would only be set in case LogLevel was left to the default value of 0, and would only consider the return code of the retried prog load. Prog loads with a non-zero LogLevel would return ENOSPC all the way to the caller, but would not have the Truncated flag set on the VerifierError.
Since this code is and has been a pain in the rear, codify the behaviour in TestProgramVerifierLogTruncated, with a clear overview of when the Truncated flag is expected to be set, and explicitly validate all cases.
cc @arthurfabre
=> prog: populate VerifierError.Truncate when LogLevel > 0

elf_reader.go, internal/unix/types_linux.go, internal/unix/types_other.go
Perfom a basic check on the given ELF. This change adopts the check that is happening also in other loader:
https://github.com/libbpf/libbpf/blob/c97b16d96c8b1771973dba1596477f7d7e9ba201/src/libbpf.c#L1380-L1385
=> elf_reader: check if ELF is for BPF data

map_test.go
Close maps after use in benchmarks and examples.
=> map_test: clean up after tests and close maps

btf/core.go, btf/core_test.go
btf: check for compatibility first when searching for a CO-RE field
Some kernels have both a struct bpf_sk_lookup and a function
bpf_sk_lookup() in their BTF. When trying to CO-RE relocate struct
bpf_sk_lookup we attempt to calculate against the function. This should
generate errImpossibleRelocation but in fact returns this:
relocate Struct:"bpf_sk_lookup": target Func:"bpf_sk_lookup": unsized type *btf.Func
This is because in coreFindField we attempt to adjust the offset
before checking that local and target are actually compatible.
Call coreAreMembersCompatible before trying to adjust the offset.
Fixes https://github.com/cilium/ebpf/issues/850
btf: always include coreKind when CO-RE fails
Include relo.kind in the error string in coreCalculateFixups to
ensure we always output this …
=> btf: check for compatibility first when searching for a CO-RE field

prog.go, prog_test.go
When a Program is constructed from a file descriptor, only the file descriptor and the program type are set. This results in the name not being present for `.String()`. Because of this the resulting string is different depending on how the Program was constructed.
As the program info is used in `newProgramFromFD()` already anyway, it can be used for setting the name as well.
=> Set Program.name when constructing from file descriptor

btf/btf.go, btf/format.go, btf/types.go, collection.go
Patch inflated Datasec instead of rawType. This wasn't possible earlier since we relied on writing out the rawType to the kernel.
Only perform the fixup when loading an ELF, since raw BTF doesn't have the necessary information.
=> btf: do Datasec fixup on inflated types

collection.go, map.go
Adding IsCompatibleWith function to export spec.checkCompatibility function.
Suggested-by: Lorenz Bauer <lmb@cloudflare.com>
Signed-off-by: Jiri Olsa <jolsa@kernel.org>
=> map: export MapSpec.Compatible

collection.go, elf_reader.go, map.go, prog.go
Setting ProgramSpec.BTF to nil was a convenient way of making prog loads execute without func/lineinfos with the introduction of Instruction.Metadata.
For example, in case instructions are added at the start of Instructions, the caller would need to make sure to move the Func to the 'new' first instruction to set up a valid function boundary. Clearing ProgramSpec.BTF was a convenient hack to load without BTF if your program type didn't need it.
Unfortunately, since adding full BTF marshaling, the {Map,Program}Spec.BTF field was no longer checked while loading BTF. Callers nilling the field had their code happily compile and fall over loading a program in production.
This commit removes these .BTF fields to make this a compile-time error.
cc @willfindlay
=> btf: Remove deprecated {Map,Program}Spec.BTF field

map.go
When attempting to create a new map with the Pinned field set, a pin path is automatically generated based on MapOptions.PinPath and the map's name.
This makes it cumbersome for the caller to figure out what the final path was that was used in the pin operation, with vague errors like:
'pin map: no such file or directory'
Wrap the error message with the final pin path.
=> map: include generated pin path in newMapWithOptions error

cmd/bpf2go/compile.go
I want to develop Android eBPF programs on Windows, but found that bpf2go uses `/dev/fd/3` to accept dependencies output, which is not supported on Windows. This commit modified it to use temporary files to accept dependencies.
=> bpf2go: write dependencies to temporary file to support Windows

internal/sys/syscall.go, prog.go, prog_test.go
Extend the profiler blocking we introduced for BPF_PROG_LOAD to BPF_PROG_RUN, with the difference that EINTR is not handled in the syscall wrapper itself. This allows us to have PROG_RUN specific retry logic.
Deprecate RunOptions.Reset since its main motivation was to account for profiler skew. Interruptions from the runtime are only possible via runtime.AllThreadSyscall, which is very specialised anyways. This doesn't protect from interruptions due to signals that are being sent from "outside" the process, which will still skew results and cause retries.
Document that RunOptions.Repeat is a lower bound for how often a program is run due to the retry behaviour. Also add a workaround that makes the common case of repeat == 1 not suffer from interruptions.
Fixes …
=> program: block SIGPROF during BPF_PROG_RUN

btf/btf.go
Signed-off-by: Robin Gögge <r.goegge@isovalent.com>
=> btf: fix function doc typo

internal/cmd/gentypes/main.go, internal/sys/types.go, link/query.go, link/query_test.go, link/syscalls.go
This PR adds a wrapper around `BPF_PROG_QUERY` and with this API it's possible to query cgroups, network namespaces or LIRC2 devices for attached programs.
Signed-off-by: Robin Gögge <r.goegge@isovalent.com>
=> link: add QueryPrograms API

link/kprobe.go, link/kprobe_test.go, link/perf_event.go, link/uprobe_test.go
In some case we want to missed as little as possible and
it is helpful to have this configuration option.
=> link: add maxactive for kretprobe

btf/ext_info.go, btf/types.go, features/prog.go
With this PR we support feature probes for all program types the library currently supports.
=> Add missing program type feature probes

.semaphore/semaphore.yml
Something broke Go module caching on the semaphore side. Disable restoring the cache for now.
=> CI: disable cache

collection.go, collection_test.go
RewriteConstants can return the error "spec is missing one or more constants" if the constant given as parameter does not exist. This patch defines the error as a specific type so it can be tested with:
```
var mErr *MissingConstantsError
if !errors.As(err, &mErr) {
```
New unit tests are added, for both the success and failure cases.
Tested with:
```
go test -exec sudo -run TestCollectionRewriteCon  ./...
```
Signed-off-by: Alban Crequy <albancrequy@linux.microsoft.com>
-----
This PR was suggested by @mauriciovasquezbernal in https://github.com/inspektor-gadget/inspektor-gadget/pull/1201#discussion_r1053515224 to avoid testing with
```
strings.Contains(err.Error(), "spec is missing one or more constants")
```
-----
Supersedes https://github.com/cilium/ebpf/pull/902
=> cs.RewriteConstants: define error MissingConstantsError

btf/btf_test.go, internal/cpu.go, internal/memoize.go, internal/testutils/cgroup.go, internal/version.go
Add a generic wrapper around sync.Once which memoizes the result of a function call.
=> internal: add Memoize

info.go, info_test.go, internal/testutils/feature.go, link/kprobe_test.go, prog_test.go
=> Fix ProgramInfo.MapIDs for programs without maps on old kernels

link/kprobe_multi.go, link/kprobe_multi_test.go
The kernel expects kprobe_multi.addrs to point at an array of unsigned long. The size of unsigned long is compiler or platform dependent, so using uint64 is incorrect on 32-bit arches.
uintptr seems like the closest analog to C's unsigned long, although I've not been able to figure out how uintptr is really defined.
See https://elixir.bootlin.com/linux/v6.1.7/source/kernel/trace/bpf_trace.c#L2671
=> link: make KprobeMultiOptions.Addresses a []uintptr

btf/btf.go, btf/btf_test.go, btf/btf_types.go, btf/ext_info.go, btf/handle.go, btf/marshal.go, btf/marshal_test.go, btf/strings.go, btf/strings_test.go, btf/traversal.go, btf/types.go, internal/deque.go, internal/deque_test.go
Add Spec.Add, which allows creating BTF on the fly from outside of the btf package.
=> btf: export API to create BTF from scratch

link/uprobe.go
strings.Map has a fast path in case a string doesn't contain any characters that have to be replaced. Use it instead of manually allocating a strings.Builder.
=> link: use strings.Map in sanitizeSymbol

btf/marshal_test.go
For some reason the kernel refuses the .data..percpu Datasec encoded by the library. Skip it in the test suite for now so that CI stops being flaky.
See https://github.com/cilium/ebpf/issues/921
=> btf: skip .data..percpu in TestRoundtripVMlinux

link/kprobe_test.go, link/perf_event.go
If a Kretprobe is created with RetprobeMaxActive > 0 on a kernel supporting bpf_link, a bpf_link is created based on a tracefs-backed perf event.
perfEventLink.Close() would try to remove the tracefs entry first, resulting in EBUSY because of the open link. This error, in turn, leaked the bpf_link fd. This also caused perf events to never be removed from tracefs/kprobe_events.
This commit closes the link and the perf event in the correct order.
Found by the fd tracer in https://github.com/cilium/ebpf/pull/732.
---
Unfortunately, this also means pinning a retprobe link with maxactive set means tracefs entries will leak by design. The only real solution I see is https://github.com/cilium/ebpf/pull/842.
=> link: close perfEventLink.fd before perf event in Close()

map.go, map_test.go
Allow DevMap and DevMapHash flags to differ in BPF_F_RDONLY_PROG.
Fixes #925.
=> map: ignore BPF_F_RDONLY_PROG for DevMap compatibility check

examples/tracepoint_in_c/main.go, examples/tracepoint_in_c/tracepoint.c, link/kprobe.go, link/perf_event.go, link/perf_event_test.go, link/tracepoint.go, link/tracepoint_test.go, link/uprobe.go
The tracefs should be mounted at `/sys/kernel/tracing`, and/or `/sys/kernel/debug/tracing`, or not mounted at all.
Today cilium/ebpf rely only on `/sys/kernel/debug/tracing`, this PR adds a fallback to also consider `/sys/kernel/tracing` (which should be the default one since kernel 4.1, based on what I understand from [the documentation](https://www.kernel.org/doc/Documentation/trace/ftrace.txt)).
=> link: use /sys/kernel/tracing if available

collection_test.go, elf_reader_test.go, features/prog_test.go, internal/feature_test.go, internal/sys/fd.go, internal/sys/fd_trace.go, internal/testutils/fdtrace/fd.go, link/cgroup.go, link/cgroup_test.go, link/kprobe_multi_test.go, link/link_test.go, map_test.go, marshaler_example_test.go, perf/reader_test.go, prog_test.go, ringbuf/reader_test.go
In an effort to improve the library's fd hygiene, this patch adds optional
metadata to sys.FD to hold a name and a stack trace of where the fd was
created, as well as a simple subscription mechanism for packages to
get notified when a live fd gets garbage collected due to losing its reference.
Metadata is only collected when there are active tracers, so they must be
registered before creating the first sys.FD.
This has shaken out a few minor bugs so far. Most of them from the test suite,
but also a few where we forgot to close resources that were no longer needed
before returning from LoadAndAssign and some other internal APIs
All test packages now also include a TestMain that sets up leak tracing and
starts a GC round before finishing the test, so we can catch these kinds of
errors more …
=> sys: add fd leak tracing instrumentation

prog.go, prog_test.go
When loading a program from a pinned file, the program name is set from the file name instead from the object info.
This commit adds a test that expects the program name to be set from the object info and changes the procedure to set the name from the object info, which is present already and used to set the program type.
Signed-off-by: Tobias Böhm <code@aibor.de>
=> program: set name from object info for pinned file

link/kprobe.go, link/kprobe_test.go, link/uprobe.go, link/uprobe_test.go
In support of #284 this seemed like the most flexible option.
~~Note: If you supply a custom group name, you cannot attach to the same symbol twice.~~ I'm wondering if we should be using the program name instead of a sanitized symbol name, for the portion of the tracefs event name after the group.
Currently:
`<type>:<group>/<sanitized_symbol> <symbol>`
Proposed:
`<type>:<group>/<sanitized_program_name> <symbol>`
=> Allow specifying the tracefs prefix in options

internal/pinning.go, internal/statfs.go, link/perf_event.go
=> Use FSType for tracefs mount detection

btf/btf.go, btf/btf_test.go, btf/traversal_test.go
Spec.Add will grow Spec.types, which means that an iterator will see newly added types. Instead take a copy of the original slice to ensure that iteration doesn't reach added types.
=> btf: ensure that TypesIterator is not affected by Spec.Add

.golangci.yaml, .semaphore/semaphore.yml, go.mod
Bump our minimum Go version and run CI against 1.20.
=> require Go 1.19

btf/marshal.go, btf/types_test.go, btf/workarounds.go, btf/workarounds_test.go
btf: work around kernel Datasec bug
The kernel erroneously rejects Datasec where a Typedef, Volatile, Const,
Restrict or typeTag follows a Pointer, Struct, Union or Array. Work
around this by explicitly adding such types to the Spec first.
The workaround only applies to BTF generated via Map.Value.
Manually crafting a Datasec is not covered.
Fixes #921
btf: fix marshaling of typeTag and declTag
Marshaling of typeTag and declTag is currently broken. This is because
we rely on marshaling vmlinux BTF for test coverage, which doesn't
contain tags since we don't compile with clang.
cc @alban @mauriciovasquezbernal
=> btf: work around kernel Datasec bug

link/kprobe.go
Before, when a caller would try to set a kprobe on e.g. __x64_sys_listen, the error message would look something like 'creating perf_kprobe PMU: token __arm64___x64_sys_listen: not found: no such file or directory'. This doesn't mention that the requested symbol has been attempted in addition to the prefixed symbol mentioned in the error message.
If a symbol doesn't exist, which is going to be the vast majority of cases, the caller will only see the prefixed symbol echoed in the error message, which can make them wonder if the original symbol has been attempted at all.
This patch makes PMU and tracefs errors more uniform and always mentions the requested symbol in the error string, which only used to happen for tracefs.
Fixes #956
=> link: always include requested symbol in kprobe creation errors

collection.go
Hi.
In this PR, I added a check to ensure `LINUX_KERNEL_VERSION` variable is a `btf.Int`.
I did not check the encoding, because it seems both signed and unsigned are possible:
https://github.com/iovisor/bcc/blob/a8949790c501560a589e52e8994d64e4f3d66dc4/libbpf-tools/capable.bpf.c#L15
https://github.com/iovisor/bcc/blob/a8949790c501560a589e52e8994d64e4f3d66dc4/libbpf-tools/biosnoop.bpf.c#L17
Best regards.
=> collection: ensure LINUX_KERNEL_VERSION variable is a btf.Int.

internal/statfs_test.go, link/perf_event_test.go
@brycekahle I brought back your test for FSType, slightly modified.
link: add a test for getTracefsPath
Assert that we can find a suitable tracefs path on CI.
internal: add test for FSType
Co-authored-by: Bryce Kahle <bryce.kahle@datadoghq.com>
=> add tests for FSType and getTracefsPath

internal/unix/types_linux.go, internal/unix/types_other.go, link/perf_event.go
RHEL/CentOS support eBPF on 3.10 before tracefs was introduced, and thus have /sys/kernel/debug/tracing mounted with debugfs fstype.
=> Allow debugfs fstype for /sys/kernel/debug/tracing

map.go
When creating a new map, if the the map type is unspecified (i.e. BPF_MAP_TYPE_UNSPEC) then the call to create the map will fail with EINVAL and the following Go error is returned due to the btf file descriptor being zerod out:
...: map create: ... (without BTF k/v)
Instead, upon failure to create me, this will now check if the map type was set to unspecified and return a relevant error.
=> Add error case for creating unspecified map type.

link/cgroup.go, link/query.go, link/syscalls.go
Document some of the lessons learned through https://github.com/cilium/cilium/pull/23557.
Also removes some papercuts from `AttachCgroup` resource cloning.
=> link: document AttachCgroup and flags

perf/reader_test.go, perf/ring_test.go
The regular and overwritable perf buffer tests currently don't share much test scaffolding because we want to know which sample we've read for the overwritable case.
Reduce code duplication by adopting the regular and overwritable tests to use a common sample format which includes both size and sample ID. Also adopt some of the helpers to fit their most common use case.
=> perf: clean up tests

btf/btf.go, btf/handle.go
Turn firstTypeID into a cached field instead of recalculating it on the fly. Map accesses with a Type as key are expensive, wich in turn make Spec.TypeByID more expensive than it has to be.
=> btf: remove Spec.firstTypeID()

btf/btf.go, btf/btf_test.go
Spec.lastTypeID was introduced to avoid having to do overflow checks in multiple places. However, in combination with firstTypeID it leads to confusion. Spec.lastTypeID is actually a valid id, instead of the first invalid one. This bit me when refactoring Spec.TypeByID.
Remove Spec.lastTypeID in favour of arithmetic based on firstTypeID and len(types).
=> btf: fix off-by-one in Spec.TypeByID

link/uprobe.go, link/uprobe_test.go
https://github.com/cilium/ebpf/issues/987
=> link/executable: lazy load symbol table

btf/btf.go, btf/btf_test.go, btf/ext_info.go, btf/fuzz_test.go, btf/handle.go, btf/marshal_test.go, btf/types.go, btf/types_test.go
Remove "type types []Type" since the only use case is the ByID method, which doesn't take split BTF into account. Use *Spec instead where necessary.
=> btf: remove type alias for []Type

btf/types.go, internal/cmd/gentypes/main.go, internal/output.go, internal/output_test.go, internal/sys/syscall.go, internal/sys/types.go, link/link.go, map.go, prog.go
Add an exported type for BTF type IDs to `sys`. Use the opportunity to make `gentypes` a little bit nicer.
=> sys: introduce TypeID

elf_reader.go
The verifier will only treat .kconfig as constants if the map is frozen, since otherwise modification from user space is possible.
Always freeze the kconfig map.
=> elf: freeze .kconfig map

btf/btf.go, btf/types.go, btf/types_test.go
btf: simplify split BTF handling in inflateRawTypes
Pass a *Spec down into inflateRawTypes and refactor the function
to make split BTF handling a bit more straightforward.
btf: account for split BTF in loadRawSpec
The calculation for the first type id assumes that base.firstTypeID
is zero. This is only true if base wasn't parsed from split BTF
itself. Refuse split BTF as base but use base.lastTypeID as a
defensive measure.
=> btf: clean up handling of split BTF in loadRawSpec and inflateRawTypes

collection.go, elf_reader.go, linker.go, prog.go
.kconfig support is currently implemented in the ELF loader, which does
a fix up of the relevant instructions to point at a ".kconfig" map. This
map is available in CollectionSpec.Maps. This is basically how constants
(aka references to .rodata) work today. Now that we have per-instruction
metadata this isn't necessary anymore.
Instead of using the generic WithReference, introduce a new kconfig
metadata and tag instructions with that. Right now the metadata just
contains the MapSpec for .kconfig as generated by the compiler. In
the future we can create the MapSpec on the fly, which would allow
referencing kconfig via ins.WithKconfig or similar.
Prevent ".kconfig" from being accessible via CollectionSpec.Maps.
This preserves our ability to change how kconfig references work
without having …
=> elf: use per-instruction metadata for .kconfig references

cmd/bpf2go/main_test.go, cmd/bpf2go/output.go, cmd/bpf2go/tools.go
Since https://github.com/cilium/ebpf/commit/223b7d740c167a41a7ba82ad59f81c7ef375b843, bpf2go reads the module name from `debug.ReadBuildInfo()`. Unfortunately this fails when `bpf2go` is built with bazel which doesn't add the buildinfo (there is an open issue for it), causing a failure with `determine current module: missing build info`.
This change sets a default if BuildInfo is not available.
=> bpf2go: Fall back to default module name when debug.ReadBuildInfo is not available

info.go, info_test.go
The CreatedByUid provides some helpful context for the source of the BPF program. Making it public in ProgramInfo
=> ProgramInfo provides CreatedByUid

btf/btf_test.go, btf/types.go
btf: avoid allocating typeDeque in copier.copy
goos: linux
goarch: amd64
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
SpecCopy-16   37.76m ± 2%   33.27m ± 5%  -11.91% (p=0.002 n=6)
│   old.txt    │               new.txt               │
│     B/op     │     B/op      vs base               │
SpecCopy-16   38.10Mi ± 0%   32.28Mi ± 0%  -15.27% (p=0.002 n=6)
│   old.txt   │              new.txt               │
│  allocs/op  │  allocs/op   vs base               │
SpecCopy-16   294.7k ± 0%   203.2k ± 0%  -31.05% (p=0.002 n=6)
btf: pre-size copier
Make sure copier has the appropriate size from the start.
goos: linux …
=> btf: optimize Spec.Copy

syscalls.go
Make sure we only attempt to remove the tracefs event if creating it really succeeded and return any errors encountered during cleanup.
cc @paulcacheux
=> program: improve error handling in haveSyscallWrapper

Makefile
It's probable I'm holding it wrong, but when running `make container-all` it uses the host path instead of the make binary in the container, failing with a "file not found" error because it cannot find it.
This PR fixes the issue by simply running `make` and trusting the `PATH` in the container to find the correct make binary.
=> fix `container-all` make invocation

Makefile
Allocate a pseudo-tty and connect stdin to allow killing make container-all via ctrl-c.
=> make: allow interrupting container-all with ctrl-c

elf_reader.go
The original error message did not print the relocation name that is causing the problem. Adding it should help with debugging the problem.
Related [discussion](https://cilium.slack.com/archives/CKC55JL8L/p1682507708984999)
Credit to @lorenz for finding this problem and debugging with me :)
Before patch:
```
Error: can't write /root/.../tc/bpf_bpfel.go: can't load BPF from ELF: load BTF maps: map test_tc_calls_map: resolving values contents: unknown relocation type STT_NOTYPE
exit status 1
```
After patch:
```
Error: can't load BPF from ELF: file /root/.../bpf_bpfel.o: load BTF maps: map test_tc_calls_map: resolving values contents: unknown relocation handle_ipv6 type STT_NOTYPE
exit status 1
```
=> Print out the relocation name in the error message

internal/sys/fd.go, internal/sys/fd_test.go, internal/sys/fd_trace.go, internal/testutils/fdtrace/fd.go, map_test.go, prog_test.go
newFD() didn't check whether the stack it tried to insert for the given fd would overwrite an existing entry.
Use LoadOrStore to check if a stack is already present, and panic if there is.
=> sys: prevent clobbering existing entries in fd tracing registry

btf/ext_info.go, btf/handle.go, btf/marshal.go
Importing package btf currently executes a feature test since we use it to initialize a global variable. Move initialization to a function to avoid this.
=> btf: avoid triggering feature probe on import

prog.go
Benchmark is not skewed by profiling since we started blocking SIGPROF during BPF syscalls. Update the function documentation.
=> program: update Benchmark doc

btf/btf.go, btf/btf_test.go, btf/core.go, internal/linux/types.go, internal/linux/types_test.go, linker.go, linux/types.go, prog.go
vmlinux BTF turns out to be a big headache, because it is quite large at roughly 150k types. The API we currently have in place forces a copy of the whole vmlinux btf.Spec on every call to LoadKernelSpec. We copy to prevent distinct callers of LoadKernelSpec from modifying types that may be referenced by someone else. As a result, some things that require access to kernel BTF are really slow: attaching fentry/fexit hooks, kfuncs, etc.
We've optimized the copying a little bit, but we can't get around the fact that there are a lot of objects to be copied so it's unlikely to get much faster. An attempt to copy btf.Spec lazily was abandoned due to it's complexity.
Which leaves us with this approach: the library shares a single kernel Spec and must take care to avoid mutating or exposing types …
=> btf: move LoadKernelSpec into separate package

link/iter_test.go
Ensure that we can create a global UDP iterator.
=> link: add test for UDP iter

.semaphore/semaphore.yml
CI: use per-job execution time limits
The current Sempahore configuration kills jobs if their waiting
+ executing time exceeds 10 minutes. This is causing problems when multiple
PRs are going through CI at the same time.
Switch to per-job execution time limits instead which do not take waiting
time into account if I understand correctly.
CI: remove Coveralls secret
The Coveralls integration never really worked, get rid of it.
=> CI: try to fix job timeouts

syscalls.go
This is showing up in memory profiles on some of our internal deployments. Seems like an easy gain.
=> Pre-allocate map sys.Errors

internal/sys/signals.go, internal/sys/signals_test.go
Remove the panic when initializing the profSet. It's causing friction when k8s tried to update the vendored dependency.
=> internal/sys: don't panic in init()

cmd/bpf2go/main.go, cmd/bpf2go/main_test.go
Enable unit tests for argument parsing in `bpf2go`. This is in preparation for enabling bpf2go to take some arguments from the  environment.
The patch moves argument parsing from `run` into a separate function.
=> bpf2go: argument parsing unit test

cmd/bpf2go/main.go, cmd/bpf2go/main_test.go
Adds `BPF2GO_CC`, `BPF2GO_CFLAGS`, `BPF2GO_STRIP` and `BPF2GO_MAKEBASE`.
The rationale for  `BPF2GO_MAKEBASE`:
This is in addition to existing -makebase option.
When used in go:generate line, the existing option requires a *relative* path from current package directory to the one with the Makefile. (While absolute pathes are accepted, we can't write one since we don't know where a user puts the project in the filesystem.)
Relative paths WILL break as packages move around.  The environment variable, on the other hand, can be set in the Makefile once and doesn't require further maintenance.
See https://github.com/cilium/ebpf/discussions/988#discussioncomment-6037792
=> bpf2go: some options take defaults from the environment

map.go
It's difficult to figure out what kind of types are valid to unmarshal into because "regular" and per-CPU values use the same code paths. This was done originally to cut down on duplicate code, but ultimately has just led to harder to read code.
Handle per-CPU values in a separate code path. This in turn makes it easy to understand that the only valid types for per-CPU values are slices and pointers to slices. Zero-copy shenanigans with unsafe.Pointer are not supported.
=> map: disentangle per-CPU handling

btf/btf.go, btf/btf_test.go, btf/ext_info.go, btf/fuzz_test.go, btf/handle.go, btf/marshal.go, btf/marshal_test.go, btf/strings.go, btf/types_test.go, btf/workarounds.go, btf/workarounds_test.go, internal/buffer.go, marshalers.go
internal: add NewBuffer
Share a single pool of bytes.Buffer across the whole library.
btf: add marshalOptions.Order
Allow specifying which ByteOrder to encode BTF into via a new field in
marshalOptions.
btf: use number of types to pre-size string table
Remove the dependency on the ELF string table to pre-size the string table
builder for large Specs. Instead we use the heuristic that for vmlinux the
number of strings is roughly equal to the number of types.
btf: refactor to Builder
Spec allows both querying Types as well as constructing new BTF blobs via
Add. This has some unfortunate consequences: we need to do extra work so
that Added types can …
=> btf: move Spec.Add to dedicated type

internal/testutils/cgroup.go, internal/unix/types_linux.go, internal/unix/types_other.go, link/socket_filter.go
Adapt code to be able to run on multiple OS.
As described in https://github.com/cilium/ebpf/issues/1073 currently there is an issue with non Linux support:
```bash
$ GOOS=windows go build ./...
internal/testutils/cgroup.go:58:21: undefined: unix.Stat_t
internal/testutils/cgroup.go:59:14: undefined: unix.Fstat
link/socket_filter.go:18:34: cannot use int(fd) (value of type int) as syscall.Handle value in argument to syscall.SetsockoptInt
link/socket_filter.go:34:34: cannot use int(fd) (value of type int) as syscall.Handle value in argument to syscall.SetsockoptInt
```
This PR moves Linux specific code into `/internal/unix`.
Fixes https://github.com/cilium/ebpf/issues/1073
=> Keep code multi OS aware

map.go, map_test.go
Since `MapIterator` is an interesting target for optimization through the upcoming zero-copy map ops work, add a benchmark and simplify its internal representation a bit.
```
Benchmark results at time of writing:
BenchmarkIterate/MapIterator-16         	             866	   1457681 ns/op	   64126 B/op	    4004 allocs/op
BenchmarkIterate/MapIteratorDelete-16   	             408	   2526392 ns/op	   80210 B/op	    6004 allocs/op
BenchmarkIterate/BatchLookup-16         	           59647	     19974 ns/op	   32851 B/op	       8 allocs/op
BenchmarkIterate/BatchLookupAndDelete-16         	   10000	    154757 ns/op	   32872 B/op	       8 allocs/op
BenchmarkIterate/BatchDelete-16                  	    8306	    136770 ns/op	   16416 B/op	       3 allocs/op
```
```
Change the terminology used in the …
```
=> Benchmark batch lookups vs. MapIterator, remove MapIterator.prevKey

btf/core.go, btf/core_test.go, btf/types.go, btf/types_test.go
btf: add CO-RE benchmark
btf: don't copy types during CO-RE relocation
During CO-RE relocation we need to ignore qualifiers and Typedefs. So far
we've done this by creating a full copy of each target type with those types
stripped out.It turns out that this is really expensive especially for large
types like struct sk_buff.
Stop copying types during CO-RE relocation and instead use the existing
UnderlyingType() and a new helper as() to skip when appropriate. As a rule
of thumb, anytime we do a type assertion during CO-RE relocation we should
use one of these helpers as appropriate.
Embarrassingly this leads to a speedup of 99.99% for large types:
goos: linux
goarch: amd64
cpu: 12th Gen Intel(R) Core(TM) …
=> btf: don't copy types during CO-RE relocation

features/prog.go, features/prog_test.go
features: add missing HaveProgramHelper test cases:
```
Add the missing test cases now that CI and the library support these
helpers.
Unfortunately the diff of this commit will touch all program/helper test
cases because of go formatting, while it only adds the four cases that
were pointed out in the removed comment.
Signed-off-by: Robin Gögge <r.goegge@isovalent.com>
```
features: fix unsupported progtype/helper probes:
```
By enabling feature probes for the program types Tracing, Extension, LSM
and StructOps within the HaveProgramType API, we overlooked that this
would cause false negative results when using these types with the
HaveProgramHelper API. To probe for these program types we craft
specialized ProgramSpecs, but don't do the same when probing for these
types in combination …
```
=> features: fix unsupported progtype/helper probes

elf_reader_test.go, link/iter.go, link/kprobe_multi.go, link/program.go, link/syscalls.go, link/uprobe.go, map.go, syscalls.go
=> improv: make errors more conclusive

elf_reader.go, elf_reader_test.go, map.go, map_test.go
elf: don't clamp PerfEventArray.MaxEntries at parse time
One key idea of the ELF reader is that it is deterministic: it should always
produce the same output regardless of which system it runs on. The
PerfEventArray clamping logic violates this since it substitutes the number
of possible CPUs.
Move the logic into map creation and adjust MapSpec.Compatible to do the
same fixup.
map: fix MapSpec.Compatible for PerfEventArray with zero key or value size
MapSpec.Compatible currently returns an error when comparing a
PerfEventArray created from a MapSpec without explicit key or value sizes.
This is because we only do the fixup just before executing the
BPF_MAP_CREATE syscall.
Move the fixup logic into a separate function so that we can invoke it …
=> elf: don't clamp PerfEventArray.MaxEntries at parse time

asm/alu.go, asm/instruction_test.go, btf/btf_test.go, elf_reader.go, features/map.go, internal/epoll/poller.go, map_test.go, types.go
This PR fixes spelling mistakes in Go comments and test messages.
=> all: fix typos in comments and tests

btf/core_test.go, btf/marshal_test.go, internal/testutils/seed.go
Include the used seed in the test log so that test2json contains the full information needed to recreate a test failure. This is useful on CI which parses the output and provides a nice UI to see failures.
Also allow overriding the used seed via an environment variable.
=> testutils: log random seed to test output

internal/unix/types_linux.go, internal/unix/types_other.go, ringbuf/reader.go, ringbuf/reader_test.go, ringbuf/ring.go
The goal for this PR is describe in https://github.com/cilium/ebpf/discussions/1108
=> Ringbuf read on timeout

map.go
=> implementation for hinting on possible error on map create with noPrealloc flag set

.semaphore/semaphore.yml, elf_reader_test.go
CI: update to latest Go point releases
CI: test against 6.1
Replace 5.19 with 6.1 as the latest kernel we test against. This requires
updating the libbpf integration tests. In v6.1 the selftest build system
started adding a .bpf suffix to all object files containing BPF programs.
Introduce a helper selftestName so that we only have to deal with this in a
single place. This also allows taking care of the .linked[123] suffixes
which have made some of the test skipping code overly verbose.
elf: update libbpf integration tests
We now support CONFIG_* variables, so update the integration tests 
accordingly.
=> CI: test against 6.1

btf/core_test.go, btf/ext_info.go, info.go, info_test.go, internal/cmd/gentypes/main.go, internal/sys/types.go
The instructions returned by program info gotten from the kernel did
not contain any metadata such as line info or function info. This
makes it harder to read the instructions when comparing the xlated
instruction in the kernel with the spec.
This PR uses the line info and function info that is available via
the program info and adds it to the returned instructions.
=> Add metadata to instructions returned by program info

collection.go, internal/endian_be.go, internal/endian_le.go, internal/sysenc/buffer.go, internal/sysenc/buffer_test.go, internal/sysenc/doc.go, internal/sysenc/layout.go, internal/sysenc/layout_test.go, internal/sysenc/marshal.go, internal/sysenc/marshal_test.go, map.go, marshalers.go, prog.go, prog_test.go, syscalls.go
map: zero-allocation operations for common types
Map keys and values are currently marshaled into []byte by souped up
versions of binary.Write and binary.Read. This allows users to be blissfully
unaware of compiler inserted padding on the Go side. This is wasteful in
case the Go in-memory representation matches what the kernel expects because
we need additional allocations.
Refactor syscall marshaling into a new package sysenc which encapsulates the
logic we need to determine whether a Go type is safe for zero-allocation /
zero-copy marshaling. The type must be a pointer to or a slice of:
* A primitive type like uint32, ... or
* An array of valid types or
* A struct made up of valid types without any compiler
inserted padding between fields
Per-CPU maps don't support zero-allocation …
=> map: zero-allocation operations for common types

elf_reader_test.go
Without this, on kernels without bpf_testmod, the following error would occur:
--- FAIL: TestInvalidKfunc (0.17s)
elf_reader_test.go:744: Expected an error wrapping incompatibleKfuncError,
got program call_kfunc: fixing up kfuncs: kfunc "bpf_kfunc_call_test_mem_len_pass1": not supported
=> elf_reader_test: check for bpf_testmod before running TestInvalidKfunc

.github/workflows/ci.yml, Makefile
Convert the Semaphore YAML into a roughly equivalent GH Actions workflow. The benefit of GH Action is that we have more and faster runners available and that permission management is more integrated.
In the future we can also use the same set up to test on arm64.
=> CI: add github actions

btf/btf.go, btf/btf_test.go, btf/feature.go, btf/feature_test.go, btf/marshal.go, btf/marshal_test.go, btf/types.go
btf: move feature tests to separate file
No other changes intended.
btf: add feature test for BTF_KIND_ENUM64
btf: work around missing ENUM64 support on older kernels
Replace an ENUM64 with a 64-bit integer on kernels which don't support the
former. This behaviour is similar to libbpf, which replaces the ENUM64 with
a union instead.
Remove the old heuristic which encoded a 64-bit enum as a 32-bit enum if
none of the values exceeded math.MaxUint32. The heuristic has no tests and
doesn't take the signedness of the enum into account.
Fixes #1116
=> btf: work around missing ENUM64 support

run-tests.sh
ci-kernels are now packaged slightly differently:
* Kernels are real tar files which also contain bpf_testmod
* Kernels contain the arch in their name
* Selftests don't contain bpf_testmod anymore
Update run-tests.sh to support the new format.
Needs: https://github.com/cilium/ci-kernels/pull/42
=> run-tests: support new packaging

Makefile, asm/alu.go, asm/func.go, asm/jump.go, asm/load_store.go, asm/opcode.go, btf/btf_types.go, cmd/bpf2go/README.md, cmd/bpf2go/test/doc.go, examples/cgroup_skb/main.go, examples/fentry/main.go, examples/kprobe/main.go, examples/kprobe_percpu/main.go, examples/kprobepin/main.go, examples/ringbuffer/main.go, examples/tcprtt/main.go, examples/tcprtt_sockops/main.go, examples/tracepoint_in_c/main.go, examples/uretprobe/main.go, examples/xdp/main.go, internal/sys/syscall.go, internal/tracefs/kprobe.go, types.go
https://github.com/cilium/ebpf/pull/1047 added env support to bpf2go, so use it.
Also cleaned up the stringer statements that would otherwise pick an old version from my GOBIN.
=> Update bpf2go and stringer go:generate statements across the codebase

btf/btf.go, btf/btf_test.go, btf/btf_types.go, btf/ext_info.go, btf/fuzz_test.go, btf/marshal_test.go, btf/strings.go, btf/types_test.go
These commits have languished in a branch of mine for a while. I think they're good to go in on their own.
btf: remove newSpec
btf: Spec.strings can't be nil anymore
Spec always has a string table now that NewSpec is not a thing anymore.
btf: move btfHeader to btf_types.go
Move btfHeader so that all btf* types live in the same file. This reduces
the size of btf.go as well.
No other changes intended.
btf: don't skip per-CPU datasec in tests anymore
There is an upstream fix and we have a workaround for the Datasec issue. 
Don't skip it in tests anymore.
btf: use slices.BinarySearch when reading a …
=> btf: clean up some small things

.github/workflows/ci.yml
Update the package repositories before installing new software. Without this CI will run into occasinal 404s when downloading qemu.
=> CI: update apt repositories

linker.go, prog.go
linker: fix fd leak in fixupKfuncs
The kfunc fixup code doesn't properly close the btf.Handle if the 
compatibility check fails:
leaked fd created at:
github.com/cilium/ebpf/internal/sys.newFD+0x26
/home/lorenz/dev/ebpf/internal/sys/fd.go:23
github.com/cilium/ebpf/internal/sys.NewFD+0x24
/home/lorenz/dev/ebpf/internal/sys/fd.go:63
github.com/cilium/ebpf/internal/sys.BtfGetFdById+0x36
/home/lorenz/dev/ebpf/internal/sys/types.go:583
github.com/cilium/ebpf/btf.NewHandleFromID+0x2e
/home/lorenz/dev/ebpf/btf/handle.go:83
github.com/cilium/ebpf/btf.(*HandleIterator).Next+0xa4
/home/lorenz/dev/ebpf/btf/handle.go:228
github.com/cilium/ebpf.findTargetInModule+0xc9
/home/lorenz/dev/ebpf/prog.go:965
github.com/cilium/ebpf.findTargetInKernel+0xe4
/home/lorenz/dev/ebpf/prog.go:943 …
=> linker: fix fd leak in fixupKfuncs

.github/dependabot.yml
What it says on the tin. We immediately got slapped with a dependabot PR after merging the documentation. Ignore security vulnerabilities in transient dependencies, we're only interested in keeping up with direct dependencies since Python code is only run during documentation build.
=> dependabot: add configuration, ignore indirect Python dependencies

Makefile, internal/cmd/gentypes/main.go, internal/sys/syscall.go
Makefile: fix generate-btf
My recent changes to the kernel packaging format broke the generate-btf 
target. Fix the invocation to work against current builds.
internal/cmd/gentypes: print more helpful error when patch fails
Output the struct being patched just before showing the patch error. This
makes it easier to figure out how the patch went wrong. Example output:
struct BtfInfo
Struct:"bpf_btf_info"[fields=6]
"btf" Int[unsigned size=64]
"btf_size" Typedef:"__u32"[Int:"unsigned int"]
"id" Typedef:"__u32"[Int:"unsigned int"]
"name" Int[unsigned size=64]
"name_len" Typedef:"__u32"[Int:"unsigned int"]
"kernel_btf" Typedef:"__u32"[Int:"unsigned int"]
Error: output "BtfInfo": patch 1: missing members: frood
Signed-off-by: Lorenz Bauer …
=> sys: small cleanups

.github/dependabot.yml, docs/Pipfile, docs/Pipfile.lock, docs/ebpf/guides/getting-started.md
No longer copy the whole snippet including output.
=> docs: copy shorthands to clipboard in getting-started

btf/format.go, btf/format_test.go
The formatter currently doesn't do sign conversion when writing out enum values. This means that negative signed enum values end up with large unsigned values. Fix this by doing correct sign conversion.
=> btf: fix writing out signed enums

perf/doc.go
Update the doc comment to make it clear that the package is only really about reading from PerfEventArray.
=> perf: clarify purpose of the package

docs/Makefile
Include 'pipenv sync' in the 'pipenv' make target to get the behaviour documented in the README.
Also adds an `exec` to the 'shell' target to avoid an error from make when the shell exits. Also, no need to keep make running during a shell session.
=> docs: improve Makefile UX with pipenv sync

btf/ext_info.go, info_test.go
When BTF ext info is encoded in ELF the instruction offsets are in bytes, but when you pass them to the kernel they must be instruction indecies. Therefor we devide the offset by the instruction size in the parsing logic for ELF.
This was missed during the initial implementation of reading back BTF ext info from the kernel. This would cause an error when loading back ext info which was not a multiple of the instruction size or a bad instruction offset if it was.
This PR adds an argument to the parsing logic to specify where the ext info is being read from. It also adds `LoadKernelLineInfos` and `LoadKernelFuncInfos` to load the ext info from the kernel, using the correct direction enum internaly. These are now used by the `info` package.
Fixes: #1168
=> btf,info: Fix bad instruction offset when parsing infos from kernel

btf/btf_test.go, btf/marshal_test.go
Spec.types is going away, so refactor tests to use an iterator to read all
types instead.
Updates #1068
=> btf: stop accessing Spec.types from tests

types.go, types_string.go
For supporting custom pinning behaviours in Cilium, we're looking to extend the MapSpec.Pinning flag and treat it as a bitfield internally. libbpf and ebpf-go currently only support LIBBPF_PIN_BY_NAME and ebpf.PinByName respectively, which has a value of 1, so it's still up in the air whether or not this could officially evolve into a bitfield in the future, since doing so can be done while maintaining backwards compatibility.
In Cilium's case, we reserve the lower 4 bits for the upstream enum values and mask out the remaining bits before calling NewCollection. The upper bits are used for specifying flags to request specific behaviours, e.g. to ignore a pinned map during loading, and explicitly overwriting its pin at a later stage, when the entrypoint program(s) were successfully …
=> PinType: change from int to uint32

examples/xdp/main.go
The IP address output by [xdp demo](https://github.com/cilium/ebpf/tree/main/examples/xdp) is empty. Although it can be solved by directly changing the `key` type to `netip.Addr` after go1.18 version, I still use a more general way to fix it.
Issue: #1175
=> example: fix key type of xdp example

internal/sysenc/marshal.go, map.go, map_test.go, prog_test.go
map: use t.Cleanup in createArray
sysenc: special case unmarshaling into []byte
The library has somewhat complicated semantics when unmarshaling map keys
and values. It turns out that the following was supported
(but not documented) until the zero-allocation marshaling work broke it:
var s []byte
m.Lookup(key, &s)
The important thing is that the slice here is empty. The current code treats
this as "the key should be zero length" while originally we'd assign the
temporary buffer used by the syscall to s as a way to reduce allocations. In
hindsight this wasn't a great idea, but it is what it is.
Reintroduce the byte slice special case.
Fixes https://github.com/cilium/ebpf/issues/1175
=> sysenc: special case unmarshaling into []byte

internal/sysenc/marshal.go, map_test.go
Unmarshal currently doesn't check that unmarshaling actually consumes to full buffer. This means that looking uint16 from an uint32 value doesn't return an error.
Fixes https://github.com/cilium/ebpf/issues/1157
=> sysenc: refuse to unmarshal into undersized dst

perf/reader.go, perf/reader_test.go, perf/ring.go, ringbuf/reader.go, ringbuf/reader_test.go, ringbuf/ring.go
This allows tracking utilization of the underlying buffers. Processing the values to make sense in a user's monitoring system is left to the user. 
Using the post-read remaining bytes allows the value to reach zero, whereas a pre-read value would never reach zero.
=> Add Remaining and Size to perf/ring Record

btf/types.go, btf/types_test.go
It seems OK that the printing size of Int type in bits.
But while printing a struct, like 'struct sk_buff', it seems strange that the printing size units of Int type and Struct/Union type are different:
```
: offset=1088
: Union[fields=2]
size: 4
csum: offset=0
csum: Typedef:"__wsum"[Typedef:"__u32"]
__wsum: Typedef:"__u32"[Int:"unsigned int"]
__u32: Int:"unsigned int"[unsigned size=32]
: offset=0
: Struct[fields=2]
priority: offset=1120
priority: Typedef:"__u32"[Int:"unsigned int"]
__u32: Int:"unsigned int"[unsigned size=32]
```
So, it's better to make the printing size of Int type in bytes same as Struct/Union type.
=> btf: correct printing size of Int type in bytes

collection.go, collection_test.go
Assign() bridges bpf2go generated code and functionality implemented in
Collection. A few things are easier to do in Collection, like iterating
through maps and programs. It is harder to guarantee invariants like map
and program initialization using reflection as well as being more
complicated.
Signed-off-by: Daniel Xu <dxu@dxuuu.xyz>
=> collection: Add Assign method

docs/ebpf/concepts/features.md, docs/ebpf/concepts/rlimit.md, docs/examples/features_test.go
This PR adds an overview page for the concept of feature detection in package `features`. It explains the differences of the provided API to `bpftool`, describes the returned error semantics and highlights a few of its shortcomings.
=> docs: add overview for package features

elf_reader_test.go
Seems like there is something funny going on with clang emitting the wrong immediate into the instruction stream.
See https://lore.kernel.org/bpf/CAN+4W8i=7Wv2VwvWZGhX_mc8E7EST10X_Z5XGBmq=WckusG_fw@mail.gmail.com/
=> elf: skip local_kptr_stash libbpf test

btf/btf.go, btf/btf_test.go
We use the cilium ebpf library in some old centos 4.18 kernel and the btf file generated by phaloe tools for CO-RE，the error occurs as like "apply CO-RE relocations: bad magic number '[159 235 1 0]' in record at byte 0x0", since the btf file we used is raw format when the cilium ebpf library only support parse elf format btf file。
Support both elf and raw BTF parse will make the cilium library be available in old centos 4.18 kernel(centos 8.0 or centos 8.1 kernel).
What's more, I see the libbpf added the same feature: https://github.com/libbpf/libbpf/commit/0420f75dbcf732e3230ae212970b33a80026e225
The similar commit in cilium library: https://github.com/cilium/ebpf/commit/48bf2ba10aee9422c9e7f43836afec0788052658
=> btf: support both elf and raw BTF in loadKernelSpec

elf_reader_test.go
The test fails for the same reason as local_kptr_stash.
=> elf: skip local_kptr_stash_fail test

btf/strings.go, btf/strings_test.go
btf: remove unused stringTable.Marshal
The library now uses stringTableBuilder instead.
btf: add fast path for string table offset 0 lookup
It turns out that the vast majority of string table lookups are for offset
zero, which is always defined to be the empty string.
This gives a good 14% speedup on my machine:
goos: linux
goarch: amd64
│  base.txt   │              zero.txt              │
│   sec/op    │   sec/op     vs base               │
ParseVmlinux-16   50.14m ± 7%   43.07m ± 3%  -14.10% (p=0.002 n=6)
│   base.txt   │           zero.txt            │
│     B/op     │     B/op      vs base         │
ParseVmlinux-16   31.45Mi ± 0%   31.45Mi ± 0%  ~ (p=0.485 n=6)
│ …
=> btf: optimize stringTable to speed up vmlinux parsing

btf/strings.go, btf/strings_test.go
After doing some observations while parsing VMLinux, it seems that the lookup access pattern for strings is mostly globally increasing with with some patches of seemingly unpridicable offsets.
This is a sample of the access pattern, numbers are the index into the string table, not the offset:
```
1112
1113
1114
348
78
1115
1116
372
1117
1118
1119
```
This commit adds logic to track this globally increasing offset and checks if the if the offset at the next expected index matches the offset we are looking for. If it does, we can skip the binary search. In VMLinux this fast path is taken about 50% of the time, resulting in about a 7% speedup.
```
goos: linux
goarch: amd64
cpu: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
│ before.txt  │          after.txt …
```
=> btf: Optimize string table for globally increasing offsets

map.go, map_test.go
This is a subset of https://github.com/cilium/ebpf/pull/1093.
Make ErrMapIncompatible a bit more descriptive.
=> map: include full property diff in ErrMapIncompatible error string

btf/ext_info.go, collection_test.go, elf_reader.go, linker.go
This PR implements two speedups/memory usage improvements in the elf loading path.
The first one is about preallocating the instructions buffer, based on the size provided by the elf section header. Due to double width load instruction we might over allocate by a bit, but from testing on our ebpf code this over allocation is negligible compared to the pre-allocation done by `slice.append` anyway, and the win is significant in case of large instructions buffer.
The second one implements a fast path for `splitSymbols` in the case where the instructions are composed of only one symbol, which is the dominant use case from my understanding (happy to be challenged on that).
I implemented a small benchmark depicting some instructions on both ends of the spectrum (one symbol, and 2 symbols at …
=> small speedups during elf loading

go.mod, go.sum
Updating golang.org/x/sys/unix to the recently released v0.14.0 will break the build because of the missing definition of BPF_F_KPROBE_MULTI_RETURN, see
https://github.com/golang/go/issues/63969 and
https://github.com/cilium/ebpf/pull/1206.
This was fixed upstream in https://go.dev/cl/540395, so manually pull in the latest unreleased version to allow modules depending on cilium/ebpf to update to later versions as well.
=> go.mod: update golang.org/x/sys to latest unreleased version

ringbuf/reader.go
We fixed this for perf buffers, but not ring buffers. Oops.
=> fix data race by caching ring buffer size

cpu.go, cpu_test.go, map.go, map_test.go, marshalers.go
Prequel to #1192 
Note: Also added `MustPossibleCPUs()` as a wrapper.
Considered switching to `sync.OnceValues()`, but instead referenced `internal.Memoize()`
=> Move PossibleCPUs to a public API

.github/workflows/trusted.yml
gh cli complains with:
gh: To use GitHub CLI in a GitHub Actions workflow, set the
GH_TOKEN environment variable.
So let's try that.
=> CI: fix trusted workflow

.github/workflows/trusted.yml
Another error from the workflow:
Unhandled error: HttpError: Resource not accessible by integration
at /home/runner/work/_actions/actions/github-script/v3/dist/index.js:2591:23
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v3/dist/index.js:7514:16), <anonymous>:4:1)
at async main (/home/runner/work/_actions/actions/github-script/v3/dist/index.js:7541:20) {
status: 403,
...
Allow the workflow to set labels on pull requests, which according to the documentation needs write permission.
=> CI: allow writing PRs from trusted workflow

internal/cmd/gentypes/main.go, internal/sys/mapflags_string.go, internal/sys/syscall.go, internal/sys/types.go, internal/unix/types_linux.go, internal/unix/types_other.go, link/anchor.go, link/cgroup.go, link/link.go, link/program.go, link/program_test.go, link/query.go, link/query_test.go, link/syscalls.go, link/syscalls_test.go, link/tcx.go, link/tcx_test.go, map_test.go
internal/sys: generate tcx wrappers
link: add TCX support
Add support for the new tcx link type. This supersedes netlink based 
attachment to TC ingress and egress hooks. It is the first user of the
bpf_mprog API in the kernel, which allows attaching multiple programs to the
same interface. Semantically programs are put into a list and then executed
in order. Earlier programs may prevent the execution of later programs.
The most interesting part is a way to express where a new program should be
inserted in the list. By default, a program attached via a new link will be
appended to the list, which is equivalent to passing the BPF_F_AFTER flag.
Passing the BPF_F_BEFORE flag prepends instead.
BEFORE and AFTER can be combined with a reference to …
=> link: add TCX support

map.go, map_test.go, marshalers.go, marshalers_test.go
Prequel to #1192 note that this *will* conflict with #1219 and need a rebase.. oh for a stacked diff workflow on GH.
=> map: allow pre-allocating per-CPU values on lookup

.github/workflows/trusted.yml
This reverts commit a26d93537d3d48d0384b1f21406f32d9261d29a1.
Turns out the action was working fine, the UI was just slow to update.
=> Revert "CI: add logging to trusted workflow"

.github/workflows/apidiff.yml, link/anchor.go, link/program_test.go, link/tcx_test.go
Timo suggested renaming First and Last to make it less likely that users assume that the position is guaranteed for the lifetime of the link.
=> link: rename First, Last to Head, Tail

go.mod, go.sum
We had to update golang.org/x/sys to an unreleased version in commit 36f6316fb169 ("go.mod: update golang.org/x/sys to latest unreleased version") to fix a build breakage in v0.14.0. Now that v0.15.0 with the fix is out, switch back to a released version.
=> go.mod: update golang.org/x/sys to v0.15.0

map.go, map_test.go
Rejig MapIterator.Next to stop allocating nextKey over and over. This makes Next() not allocate in a steady state:
core: 1
goos: linux
goarch: amd64
pkg: github.com/cilium/ebpf
│  base.txt   │              opt.txt              │
│   sec/op    │   sec/op     vs base              │
Iterate/MapIterator         1.596m ± 0%   1.500m ± 1%  -6.05% (p=0.002 n=6)
Iterate/MapIteratorDelete   2.862m ± 0%   2.754m ± 0%  -3.75% (p=0.002 n=6)
geomean                     2.137m        2.032m       -4.91%
│   base.txt    │              opt.txt              │
│     B/op      │    B/op     vs base               │
Iterate/MapIterator         56082.00 ± 0%   96.00 ± 0%  -99.83% (p=0.002 n=6)
Iterate/MapIteratorDelete    56082.0 ± 0%   104.0 ± 0%  -99.81% (p=0.002 n=6) …
=> map: avoid allocations in MapIterator.Next

map.go, map_test.go
See commit msgs.
* Introduce BatchCursor abstraction
* Add unit test for batch lookup with chunking
* Add warning to Batch* API operations
---
Main commit for convenience: 
> Introduce BatchCursor abstraction
> 
> The batch API in the kernel is quite tricky to get right. In order to
> pass the arguments in correctly, especially regarding the "in_batch" and
> "out_batch" arguments, it requires knowledge of how the batch map
> iteration is implemented in the kernel.
> 
> In order to avoid pushing the cognitive overhead onto users of the
> library, abstract away the details of batch map iteration into an opaque
> type, BatchCursor.
> 
> Users are expected to pass in a reference to a BatchCursor and the
> library will handle allocating the underlying buffer when needed.
> Specifically, the …
=> map: Introduce BatchCursor abstraction

.github/workflows/ci.yml, btf/core_test.go, map_test.go
Execute benchmarks once on CI, to prevent bitrot from setting in.
=> CI: execute benchmarks once to prevent bitrot

docs/ebpf/users.md
The pkg.go.dev importers tab is not very useful to gauge how widely the library is used because it includes lots of duplicates due to forks.
Use a Sourcegraph query instead which also includes repo stars.
=> doc: use Sourcegraph query for list of importers

internal/sysenc/buffer.go, map.go, map_test.go
Extend the optimization from 4609dc73 ("map: zero-allocation operations for common types") to BatchLookup. This means that types without implicit padding will not incur allocations.
core: 1
goos: linux
goarch: amd64
pkg: github.com/cilium/ebpf
│   base.txt   │              opt.txt               │
│    sec/op    │   sec/op     vs base               │
Iterate/BatchLookup   4317.0n ± 2%   771.6n ± 1%  -82.13% (p=0.002 n=6)
│   base.txt    │              opt.txt              │
│     B/op      │    B/op     vs base               │
Iterate/BatchLookup   16432.00 ± 0%   48.00 ± 0%  -99.71% (p=0.002 n=6)
│  base.txt  │              opt.txt              │
│ allocs/op  │ allocs/op   vs base               │
Iterate/BatchLookup   4.000 ± 0%   2.000 ± 0% …
=> map: avoid allocations during batch lookup of common types

.github/workflows/ci.yml, link/uprobe_test.go
Use the actuated runners provided by the CNCF to run the testsuite on arm64. These runners do not support nested KVM and therefore we can run the VM tests there.
Fixes #266
=> CI: run tests on arm64

link/uprobe_test.go
In c035e6ac we changed the address we pass when creating a perf_event uprobe to the first byte of the second page to support arm64. This however fails consistenly on my local setup (older intel machine). After some investigation, it turns out arm64 doesn't require the address to not be in the first page, but to be aligned with a multiple of 4.
=> link: fix TestUprobeExtWithOpts address

cmd/bpf2go/main.go, cmd/bpf2go/main_test.go
The current error message makes people think that bpf2go can only be invoked via go generate. In fact we just expect to find the package name in GOPACKAGE.
Reword the error and add a test to make sure that the error message mentions the variable.
=> cmd/bpf2go: rephrase GOPACKAGE error message

docs/ebpf/contributing/index.md, run-tests.sh
Use the new GH Actions built containers as a source for run-tests.sh.
Fixes: https://github.com/cilium/ebpf/issues/1258
=> run-tests: fetch kernels and selftests from containers

prog.go, prog_test.go
The `bpf_prog_test_run_raw_tp` function has a lazy check on `bpf_attr->test.repeat`: it checks that it's equal to 0 while it could check for <= 1.
```C
/* doesn't support data_in/out, ctx_out, duration, or repeat */
if (kattr->test.data_in || kattr->test.data_out ||
kattr->test.ctx_out || kattr->test.duration ||
kattr->test.repeat || kattr->test.batch_size)
return -EINVAL;
```
Program.run was hard setting the repeat value to 1 in case of 0, preventing running any raw_tracepoint program. Now it handles special cases with repeat <= 0, and does not touch the value, letting the kernel handle the 0 value.
=> program: fix raw_tracepoint run repeat check bug

perf/reader.go
fix #1281
First check the err variable, then use the ring variable.
=> perf: fix nil pointer when perf map create failed

link/link.go, link/link_test.go
Just like for other link types, this commit adds a method for retrieving TCX link specific extra metadata info.
=> Add link.Info.TCX method

link/syscalls.go, link/syscalls_test.go, link/tcx.go
As with many of the other existing APIs, this adds a feature test for tcx to indicate to the user if the underlying kernel APIs are available in the running kernel.
=> link: add feature test for tcx

cmd/bpf2go/main.go
In #975, someone added support for the loong64 GOARCH, but did't provide a Linux string for it. Since the upstream support ([0]) has already landed, let's add the missing Linux string and make LoongArch a supported target.
[0]: https://github.com/torvalds/linux/commit/00883922ab40
=> cmd/bpf2go: Make LoongArch a supported target

features/misc.go
Exporting feature tests as variables means that they can't be navigated to in online documentation. Fix this by exporting functions instead.
=> features: fix documentation

btf/btf.go, btf/btf_test.go, btf/core.go, btf/core_test.go, btf/fuzz_test.go, btf/marshal_test.go, btf/traversal.go, btf/traversal_test.go, btf/types.go
btf: add benchmark for Spec.TypeByID
btf: don't access Spec.types from iterator
btf: fix slow LoadKernelSpec by making Spec.Copy lazy
LoadKernelSpec is currently very slow, on the order of tens of milliseconds. 
The reason for this is that we copy all ~150k types before returning the
Spec to the caller. This is necessary since we don't want independent
callers of LoadKernelSpec to be able to influence each other.
So far we've put up with the slowness in case of features that are not used 
that much yet (kfuncs) or worked around it by moving APIs into the btf 
package where we can avoid the copy.
I've made multiple attempts at fixing this problem. In no particlar order:
* Have an internal …
=> btf: fix slow LoadKernelSpec by making Spec.Copy lazy

internal/cmd/gentypes/main.go, internal/sys/types.go, link/link.go, link/link_test.go, link/netfilter.go, link/netfilter_test.go, link/syscalls.go
Add netfilter support to attach BPF programs to netfilter hooks.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=84601d6ee68ae820dec97450934797046d62db4b
=> link: add netfilter support

.github/workflows/ci.yml, go.mod
1.22 has been released, bump minimum version to 1.21.
=> bump minimum Go to 1.21

internal/auxv.go, internal/auxv_test.go, internal/vdso.go, internal/vdso_test.go
Fixes https://github.com/cilium/ebpf/issues/1166
This PR extracts auxv related code to its own file. It also creates a common interface to read auxv pairs. The new go 1.21 runtime function to fetch auxv is then used to create a new auxv provider, and the old file based one is kept around for tests.
This PR also adds a test ensuring the file and runtime based auxv reader actually read the same pairs.
If we decide we can remove `TestAuxvVDSOMemoryAddress` and `TestAuxvNoVDSO`, I would be open to simplifying drastically this PR and keeping only the runtime auxv provider. Open to feedback especially on this.
=> add support for reading auxv from Go runtime

.github/dependabot.yml
We currently have a lot of github actions missing upgrades, resulting in some 
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-go@v4 ...
```
[warnings](https://github.com/cilium/ebpf/actions/runs/7817377529).
This PR onboards the github actions workflows into dependabot, which should make our life updating those easier.
=> dependabot: onboard github actions upgrades

map.go, map_test.go
All of the other map related types have this prefix, so make BatchCursor the same.
=> map: rename BatchCursor to MapBatchCursor

.github/workflows/trusted.yml
This has been broken by https://github.com/cilium/ebpf/commit/4d619bbc8b492e0d2f2a37c369f444da39c9a8db, and the bump to a version higher than v5 (see https://github.com/actions/github-script?tab=readme-ov-file#v5).
Please note: this fix is pretty difficult to test since the job itself uses the workflow definition from the main branch to run
=> fix trusted "Tag breaking changes" workflow

btf/btf.go, btf/btf_test.go, run-tests.sh
Up until the introduction of lazy copying, reading from a Spec concurrently was safe. Now a read may trigger a copy and a write into the Spec, therefore causing a race on mutableTypes.
Fix this by introducing a mutex which protects access to the mutable state. We need to be a bit careful here: copying in mutableTypes.add happens piecemeal, so we need to take a lock for the whole duration of modifyGraph.
=> btf: fix race due to concurrent read access

btf/btf.go, btf/btf_test.go
We reference mt.copiedTypeIDs during copy to be able to figure out the correct ID for a copied type. This access can currently race with mutableTypes.add since we don't protect mt.copiedTypeIDs.
Take a read lock to prevent modification.
=> btf: fix race in mutableTypes.copy

btf/btf.go, btf/btf_test.go, btf/core.go, btf/core_test.go, btf/kernel.go, btf/kernel_test.go, internal/kallsyms/kallsyms.go, internal/kallsyms/kallsyms_test.go, kallsyms.go, linker.go, prog.go
re #705 
- Adds `KernelModule string` to `ProgramSpec`. This is automatically populated by `tracefs.KernelModule()` for kprobe/fentry programs, by parsing `available_filter_functions`. 
- Adds `KernelModuleTypes *btf.Spec` to `ProgramOptions`, so user can provide their own kmod BTF.
The usage of a `*Spec` in parts of CO-RE had to be abstracted to avoid copying/merging of `[]Type` slices.
This does work (tested with `nf_conntrack` kmod and `__nf_conntrack_hash_insert` kprobe), but I imagine you have thoughts about how to adapt this approach.
=> Add CO-RE support for kernel modules

ringbuf/ring.go
Remove the clamp function in favour of the new min builtin.
=> ringbuf: replace clamp with min

run-tests.sh
We added the code to retry failed qemu invocations due to an undiagnosed Semaphore bug. Remove it now that we are on GHA.
=> CI: increase vm memory to avoid oomkills

CODEOWNERS, docs/ebpf/contributing/index.md
As discussed at the Cilium Dev Summit 2024, this codifies review assignments and expectations around interactivity on PR reviews.
---
We understand there are potentially multiple candidates for some packages, but to reduce potential bystander effect, we want to start off by assigning a single code owner and seeing where that goes. Over time, we can add multiple code owners for the more active packages.
=> CODEOWNERS: assign code ownership to florianl, mmat11 and dylandreimerink

elf_reader_test.go
The "test_log_fixup" selftest is broken on purpose, with the goal of testing error messages. Due to changes in #1364 we now emit a poison instruction in `bad_relo_subprog` on a instruction which also has a reference to a BPF-to-BPF function. This causes the symbol/reference resolution step to fail.
This error is flaky, it only happens when `bad_relo_subprog` is loaded first. If any other program in the collection is loaded first due to random hash map ordering we skip the test instead due to the test checking for verifier errors.
Since this test is broken on purpose, we previously just always hit this skip condition. This commit disabled this selftest explicitly which resolves the CI flakiness.
=> elf_reader_test: Fix CI by disabling the "test_log_fixup" selftest

btf/core.go, btf/core_test.go
coreAreTypesCompatible currently uses two manually maintained stacks to traverse two types to compare. The original idea was that using stacks would somehow be more efficient or it'd be easier to understand than the recursive approach. Time has shown that this was probably not true. Using the stacks is both harder to understand and probably less performant than using recursion. This is because the runtime maintains a stack for us, which can be reused across many invocations. Allocating on the (goroutine) stack is also incredibly cheap.
Rewrite coreAreTypesCompatible to use recursion to traverse the two types. Instead of using walkType we simply open code the switch cases for Pointer, Array and FuncProto. This isn't much code and gets rid of a bunch of complexity and allocations, …
=> btf: use recursion in coreAreTypesCompatible

internal/cmd/gentypes/main.go, internal/sys/syscall.go, internal/sys/types.go, link/link.go
The current generic abstraction of `bpf_link_info` makes it harder to implement features like #1295. Instead of splitting LinkInfo into a generic part and having extra structs to represent the fields of union members in `bpf_link_info`, with this PR we generate the full LinkInfo struct for each member the union in `bpf_link_info`.
=> link, internal: generate full linkinfo for union subtypes

.gitattributes
Annoyingly, GH hides types.go in diffs by default. Turn off this behaviour.
=> gh: do not hide internal/sys/types.go in diffs

btf/core_reloc_test.go, cmd/bpf2go/output_test.go, collection_test.go, elf_reader_test.go, info_test.go, internal/endian_be.go, internal/endian_le.go, internal/testutils/glob.go, link/tracing_test.go, linker_test.go, map_test.go, prog_test.go
internal: remove ClangEndian
Replace uses of ClangEndian with a NativeFile test utility.
tests: remove !IsNativeEndian skips
We have a lot of tests which first glob a list of files containing BPF for
little and big endian, then parse those files and finally skip a test if the
files endianness doesn't match the native endianness.
This is pretty wasteful, since we parse BPF for no good reason and makes the
tests more verbose than they have to be. Use NativeFile instead and remove
almost all checks for IsNativeEndian from tests.
The two remaining cases are in the ELF loader tests, where they do have
value: we want to make sure that we can parse things from any endianness.
=> tests: clean up ClangEndian

examples/tcprtt/main.go, examples/tcprtt_sockops/main.go
Technically this builds fine in CI, but these are supposed to function from outside the repo's ebpf module as well. These internal references were added after we removed the separate Go module from examples/.
Supersedes #1288
Thanks @antoniomerlin for reporting!
=> examples: avoid depending on internal packages

docs/mkdocs.yml
master branch was renamed to main, update mkdocs.yml to match.
The link in the top-right corner of every page is currently 404, example: https://github.com/cilium/ebpf/edit/master/docs/ebpf/guides/getting-started.md
=> Fix GitHub edit link on every page

cmd/bpf2go/main_test.go, link/uprobe_test.go
cmd/bpf2go: don't require internet connection in tests
Disable the checksum db and the module proxy. They aren't needed for tests
and disabling means we don't need internet access.
link: disable uprobe tests on v4.9
Running v4.9 in vimto, trying to create a perf event via perf_event_open 
returns EIO. I've tracked this down to a check in uprobe_register:
if (!inode->i_mapping->a_ops->readpage &&
!shmem_mapping(inode->i_mapping))
return -EIO;
See
https://elixir.bootlin.com/linux/v4.9.337/source/kernel/events/uprobes.c#L880
My hunch is that this is related to how vimto sets up the overlayfs mount:
if the probed binary is below the overlayfs the setup fails.
Instead of fixing vimto, stop testing these code paths on v4.9. That kernel 
is already …
=> miscellaneous test fixes

internal/cmd/gentypes/main.go, internal/sys/types.go, link/link.go, link/link_test.go
Add an iterator for links that loops over all links in the system.
This then can be used to get information about attached programs, e.g. to [find which XDP program attached to an interface](https://github.com/cilium/ebpf/discussions/1380).
The implementations closely mirrors that of the  [HandleIterator](https://github.com/cilium/ebpf/blob/65fb774468cbc51047f7115a57623832e8388eff/btf/handle.go#L201)
=> link: add Iterator

btf/btf.go, btf/core.go, btf/core_test.go, btf/marshal.go, btf/marshal_test.go, btf/traversal.go, btf/traversal_test.go, btf/types.go, btf/types_test.go, internal/cmd/gentypes/main.go
Reduce iterator complexity in the btf package by using recursion. If you have played with the rangefunc proposal you will realise that `visitPostorder,` etc. can be turned into an `iter.Seq` with a few lines of code. The reason to make this change now (rather than waiting) is that the recursive implementation is easier to reason about and about as fast:
```
core: 1
goos: linux
goarch: amd64
│  base.txt   │            recursive.txt             │
│   sec/op    │   sec/op     vs base                 │
ParseVmlinux                             64.06m ± 2%   64.43m ± 2%        ~ (p=0.394 n=6)
SpecCopy                                 353.2n ± 1%   270.3n ± 2%  -23.46% (p=0.002 n=6)
SpecTypeByID …
```
=> btf: use recursion

.github/workflows/ci.yml
GH Actions cancels CI runs on main when merging PRs in quick succession. Try to only cancel pull requests.
=> gh: only cancel pull_request runs

perf/reader.go, perf/reader_test.go, perf/ring.go, perf/ring_test.go
follow up to #524 with only the `WakeupEvents` portion.
=> add WakeupEvents support to perf Reader

.github/workflows/ci.yml
The default builtin timeout in the go test runner is 10 min and the GH runner is also limited to 10 min. In practice the GH runner is quicker to kill tests that exceed this time limit, in which case we abruptly exit without logs on which test caused the timeout.
This change extends the runner timeout to 15 min to give the go runner a chance to kill the bad test and to tell us which test was taking longer so that we can fix the issue.
=> Extend go test CI from 10 to 15 miniutes

btf/core.go, btf/ext_info.go
When an asm.Comment is added to an instruction, existing source information like btf.Line will be replaced. But in some cases, instructions without line information won't pass the verifier. The expected behavior would be, that the comment gets synthesized into a line info where everything but the line string is zero. This PR implements this.
Fixes https://github.com/cilium/ebpf/issues/1413
=> btf: synthesise instruction comments into line info 

internal/cmd/gentypes/main.go, internal/sys/syscall.go, internal/sys/types.go, link/link.go, link/link_test.go
adding support to get info data from kprobe_multi/perf_events probes, using it in tetragon [1941](https://github.com/cilium/tetragon/pull/1941)
=> Add support to retrieve missed counts from probes

internal/testutils/cpu.go, internal/unix/types_linux.go, internal/unix/types_other.go, perf/reader_test.go
The WakeupEvents limit is per ring, one per CPU. And when we execute BPF_PROG_RUN multiple times, we sometimes execute on different CPUs. This means that samples don't all go into a single ring.
Fix this by forcing the producer to run on a single CPU.
Co-developed-by: Dylan Reimerink <dylan@isovalent.com>
=> perf: fix TestPerfReaderWakeupEvents

prog.go
The outLen parameter to (*Program).Test was removed in commit e45ae4ab8640 ("detect kernel support for BPF_PROG_TEST_RUN and work around unsafe API"). Remove it from the godoc comment as well.
=> Don't mention inexistent outLen parameter in (*Program).Test godoc

btf/btf.go, btf/core.go, btf/core_test.go
reloTypeIDTarget is used to substitute the ID of an equivalent type in vmlinux. This is problematic when dealing with kmod types, since their IDs are defined to be sequential with vmlinux. If the last vmlinux type ID is 99, the first type in kmod a and b has ID 100. To disambiguate between these we need a (BTF ID, Type ID) tuple, which we currently don't support.
Poison any relocation which tries to use the target ID of a kmod type. This also gets rid of mergedSpec which didn't take overlapping ID ranges into account.
=> btf: refuse reloTypeIDTarget for kmod types

btf/types.go, btf/types_test.go, internal/math.go, internal/math_test.go, map.go
example:
```c
struct {
__uint(type, BPF_MAP_TYPE_RINGBUF);
__uint(max_entries, 4097);
} rb SEC(".maps");
```
then output: 
```
program dev_hard_start_xmit: map rb: EINVAL (ring map size 4097 not a power of two page size(pageSize 4096))
```
=> when ringbuffer map size is not a power-of-2 multiple of page size, prompt users in a user-friendly way

README.md
Change the wording in the readme so that we don't have to keep updating it all the time. This also helps to set expectations with users.
Updates https://github.com/cilium/ebpf/issues/1434
=> doc: rephrase supported kernel versions

btf/kernel.go, linker.go
In kernels where the flag `CONFIG_DEBUG_INFO_BTF_MODULES` is not set, including kernels 5.10 and below (because the flag was introduced in 5.11), loading a program that attaches to kernel module functions and relied on CORE failed because the module's BTF is not available.
This fix allows the program to run, obviously only as long as it only relies on the kernel's BTF and not on the specific module's BTF.
Fixes: https://github.com/cilium/ebpf/issues/1436. Tested on the same example included in the issue: when using the fixed package, the program attaches successfully.
=> program: don't return error when kmod BTF is disabled

go.mod
Relates to #1438
Signed-off-by: Pablo Baeyens <pablo.baeyens@datadoghq.com>
=> [go.mod] Change `go` directive to `1.21`

.github/ISSUE_TEMPLATE/bug_report.yml
The Bug report template turns the textareas into code blocks. This leads to some weird formatting. Remove the offending "render:" attribute.
=> gh: don't use code blocks in Bug report template

.github/workflows/ci.yml, internal/testutils/feature.go
Seems like the new CI arm64 kernels doesn't have the necessary config to support kprobe_multi. Ignore the error until we figure out what to do.
Updates https://github.com/cilium/ebpf/issues/1460
=> ci: ignore kprobe_multi test failures on arm64

internal/epoll/poller.go, perf/reader.go, perf/reader_test.go
epoll: simplify timeout calculation
epoll: fix eventFd.add
eventFd.add hardcoded the value to add to 1 instead of using the argument.
This hasn't caused a bug since we never call add with a different value.
perf: opportunistically check all rings for data
Waking up user space from the kernel is expensive and so the perf reader 
allows adjusting the rate at which wakeups happen. This saves CPU at the 
cost of latency: some data will remain in the buffer for longer.
The reader is an abstraction over multiple ring buffers. It only reads from
a ring buffer if it has received a wakeup from the kernel. This is wasteful
because wakeups are expensive (due to context switching and so on) but
checking a …
=>  perf: flush Record when deadline is exceeded

link/kprobe.go, link/perf_event.go
This will match libbpf behavior. Relevant snippet from `perf_event_open` [manpage](https://man7.org/linux/man-pages/man2/perf_event_open.2.html#DESCRIPTION)
>        pid > 0 and cpu == -1
>              This measures the specified process/thread on any CPU.
=> perf_event_open cpu should be -1 for valid PID

.github/workflows/ci.yml
ci: debug sporadic vimto hang
There is a case where one of the CI tests hangs for 10 minutes an is then 
killed by the go test harness' timeout. From the dumped goroutines it seems 
like the runner inside the VM is stuck writing to stdout:
goroutine 82 [syscall, 9 minutes]: syscall.Syscall(0x4a4b1c?, 0x708c80?,
0x80000000000?, 0x7ffff80000000000?)
/opt/hostedtoolcache/go/1.21.9/x64/src/syscall/syscall_linux.go:69 +0x25 
syscall.write(0xc000014120?, {0xc0002340c0?, 0x4f0996?, 0xc002048680?})
/opt/hostedtoolcache/go/1.21.9/x64/src/syscall/zsyscall_linux_amd64.go:949
+0x3b syscall.Write(...)
/opt/hostedtoolcache/go/1.21.9/x64/src/syscall/syscall_unix.go:209 
internal/poll.ignoringEINTRIO(...)
/opt/hostedtoolcache/go/1.21.9/x64/src/internal/poll/fd_unix.go:736 …
=> debug sporadic vimto hang

link/cgroup.go, link/kprobe_multi.go, link/link.go, link/netfilter.go, link/netkit.go, link/netns.go, link/perf_event.go, link/tcx.go, link/tracing.go, link/xdp.go
This PR pulls out retrieving linktype-specific metadata from `RawLink.Info()`. This will reduce the amount of syscalls when calling `RawLink.Info()` directly. If needed the inktype-specific metadata can now be retrieved through linktype-specific `Info()` methods.
=> link: add Info() method to all link types

info.go, info_test.go
Adding RecursionMisses to access ProgramInfo recursion misses counter.
It does not depend on whether collection of statistics is enabled, the value is always counted.
=> Add RecursionMisses to access ProgramInfo recursion misses counter

elf_reader.go
Seems like BTF map definitions have gained a map_extra field which we don't know how to handle. Return ErrNotSupported for now so that TestLibBPF can skip the test.
=> elf: turn BTF map_extra into ErrNotSupported

docs/ebpf/contributing/new-example.md, docs/mkdocs.yml, examples/README.md
Every once in a while we have to reject new examples because they don't really show a use case of the library but instead explain some eBPF feature.
Add documentation to explain what examples make sense in the library to avoid future disappointments.
=> docs: add a section on examples

map.go, map_test.go
The batch lookup API for hash maps returns ENOSPC when a bucket doesn't fit into the provided batch. This is unfortunate since user space has no way to figure out what the largest bucket size is. This makes the API very awkward to use.
It also seems that hash tables don't deal well with sequential keys, hashing them into the same bucket with fairly high probability.
Fix the flaky test by always making the batch size equal to the map size, which means we can never trigger ENOSPC. Also make the error message more descriptive.
Fixes: https://github.com/cilium/ebpf/issues/1390
=> map: fix TestMapBatch failing with ENOSPC for hash maps

info.go, map.go, map_test.go
What it says on the tin. A do-over from Program.Handle().
cc @olsajiri
=> map: add Map.Handle() method for retrieving a Map's type information

docs/ebpf/stylesheets/extra.css
The "eBPF Library for Golang" headline is clipped in Firefox on Linux. Remove the offending CSS.
=> docs: fix clipped headline on home page

ringbuf/reader_test.go, ringbuf/ring.go
The data pages of a ring buffer are mapped twice in a contiguous virtual region to allow easy wrap around when writing data. The code returns the ring size as the capacity of this mmaped region. However, this is wrong since the kernel [double maps the underlying pages](https://elixir.bootlin.com/linux/latest/source/kernel/bpf/ringbuf.c#L99).
This PR fixes this by reporting the ring size as half the capacity of the underlying mmap region.
=> Fix ringbuffer ring size reporting

internal/epoll/poller.go, internal/epoll/poller_test.go, perf/reader.go, perf/reader_test.go, ringbuf/reader.go, ringbuf/reader_test.go, ringbuf/ring.go
When using `WakeupEvents` for perf buffers or `BPF_RB_NO_WAKEUP` for ring buffers, you can enqueue data that does not immediately trigger a reader blocked in `Read/ReadInto` to wakeup.
This PR adds a function `Flush` to manually cause those blocked readers to wakeup. Further, a sentinel error `FlushCompleteError` is returned when all the rings have been read, indicating all the data already queued when `Flush` was called has been read.
=> Add Flush to manually unblock Read/ReadInto

link/kprobe_multi.go, link/link.go, link/perf_event.go
we need to pin kprobe and kprobe_multi links, ATM I'm using this, but I guess there's better way at least for standard kprobes
I'm not sure if the issue described in Pin function comment is also valid  for kprobes created via perf_link,
but the pinning seems to work, and that's what we'd like to use (we don't need to re-open the link)
note the wrapRawLink for perf event kprobe needs to be done properly somehow
cc: @lmb @ti-mo
=> allow to pin kprobe and kprobe_multi links

link/uprobe_multi.go
I accidentally dropped the change to allow pinning uprobe multi from Jiri's patch. This restores the functionality.
=> link: allow pinning uprobe multi links

.github/workflows/ci.yml, btf/btf_test.go, btf/handle.go, internal/errors.go, internal/errors_test.go, prog.go, prog_test.go
ci: fix golangci-lint
For some reason the Action decided to break now, after being updated a
couple of weeks ago.
program, btf: probe correct log buffer size
The kernel exposes a log of operations to aid debugging a program or BTF
load. Until recently there was no way to know the size of that buffer, so
the library forces the user to specify a buffer size. From a cursory survey
on sourcegraph.com it seems that users either hardcode a large fixed buffer
or probe the correct size by doubling the buffer size when hitting ENOSPC.
Since commit 47a71c1f9af0 ("bpf: Add log_true_size output field to return
necessary log buffer size") the kernel does provide a hint to user space.
Move probing of the correct log buffer size into the library. On recent …
=> program, btf: probe correct log buffer size

perf/reader.go
<details>
<summary>eBPF code</summary>
``` c
//go:build ignore
#include <common.h>
#include <vmlinux.h>
#include <bpf_helpers.h>
#include <bpf_core_read.h>
#include <bpf_endian.h>
char __license[] SEC("license") = "Dual MIT/GPL";
struct event {
u32 pid;
u32 ppid;
u32 uid;
char comm[100];
};
struct {
__uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
} events SEC(".maps");
// Force emitting struct event into the ELF.
const struct event *unused __attribute__((unused));
SEC("kprobe/sys_execve")
int kprobe_execve(struct pt_regs *ctx) {
struct event e;
u32 pid, ppid, uid;
struct task_struct *task;
pid = bpf_get_current_pid_tgid() >> 32;
uid = bpf_get_current_uid_gid() & 0xFFFFFFFF;
task = (struct task_struct *)bpf_get_current_task();
ppid = BPF_CORE_READ(task, real_parent, tgid);
e.pid  = pid; …
```
=> fix(perf) skip to process nil ring

map_test.go
For some reason the allocation check is flaky, with an allocation happening in sysenc.Unmarshal. Pinpointing the exact cause is difficult because we can't tell whether the allocation happened during the warm up or not.
Increase the number of runs for the allocation check, which is probably a sensible thing to do anyways.
=> map: fix flaky TestMapIteratorAllocations

link/xdp.go, link/xdp_test.go
With the change in #1435, failures to attach to a XDP link cause a nil pointer dereference. This change ensures any error returned from `AttachRawLink` is handled correctly.
=> link: fix nil pointer dereference in AttachXDP

info.go, info_test.go
People adding new fields to the Info API always get tripped up by how it works. Add a comment which explains why it works the way it does. Also add a test which ensures that new exported fields are only added when they are really warranted.
=> info: make it harder to add backwards incompatible API

perf/reader.go
Adding nil to rings and eventFds for offline CPUs can cause issues when iterating over these elements.
Therefore skip adding to rings and eventFds if the CPU is offline at the time of initalization.
=> perf: do not add offline CPUs

btf/btf.go, btf/btf_test.go, collection.go, collection_test.go, internal/testutils/checkers.go, internal/testutils/checkers_test.go, map.go, map_test.go, prog_test.go
The are multiple Copy() methods in the code base which are used to create deep copies of a struct. Any bugs in them can manifest as data races in concurrent code.
Add a quicktest checker which ensures that two variables are a deep copy of each other: values match, but all locations in memory differ.
Fix a variety of problems with the existing Copy() implementations. They all allow copying a nil struct and copy all elements.
There are exceptions to the deep copy rule:
- MapSpec.Contents is not deep copied because we can't easily make copies of interface values. This is documented already.
- MapSpec.Extra is an immutable bytes.Reader and therefore only needs a shallow copy.
- ProgramSpec.AttachTarget is a Program, which is (currently) safe for concurrent use.
Fixes #1517
=> fix a variety of Copy() problems

map.go, map_test.go
=> map: do not allocate on lookup when key doesn't exist

internal/errors.go, prog.go
We removed LogSize and VerifierError.Truncated in a previous commit, but this causes lots of headache when trying to update the dependency in cilium/cilium and cilium/tetragon. We won't be the only ones suffering, so deprecate the field instead of removing it outright.
=> program: deprecate LogSize and VerifierError.Truncated

btf/types.go, btf/types_test.go, map.go
Copying a nil Type panics since we unconditionally invoke Type.copy(). Fix this and adjust the tests.
=> btf: fix panic when copying nil Type

map.go
Time and time again people misunderstand errors like the following:
map create: cannot allocate memory (without BTF k/v)
Instead of focusing on the ENOMEM they assume that it has something to do with BTF. In reality it just means that creating a map has failed, and we didn't supply any BTF during creation.
Avoid this confusion by removing the "without BTF k/v" part.
=> map: remove misleading error message when creating without BTF

internal/errors.go, prog.go
This reverts commit 218b9f968308e6bfdf1cc4324ee683de66c3ea68.
Remove the deprecated API related to log buffer sizing. We've just cut a release where the fields are deprecated, which gives people time to update.
=> program: remove LogSize and VerifierError.Truncated

CODEOWNERS
Add Timo as the codeowner of the docs/ folder, which mostly gets automated PRs from dependabot.
=> docs: make timo code owner

internal/errors_test.go
Using unix.EINVAL as the error makes the test depend on package unix without any real need.
=> internal: use sentinel error in TestVerifierErrorWrapping

.golangci.yaml, btf/types_test.go, cmd/bpf2go/main_test.go, internal/epoll/poller_test.go, link/uprobe_multi_test.go, link/xdp_test.go
This PR ensures that we uniformly format imports in the future (mostly relevant for tests).
=> ci/goimports: group cilium/ebpf imports after 3rd party imports

ringbuf/reader.go, ringbuf/reader_test.go, ringbuf/ring.go
Adds AvailableBytes(), which is equivalent to ring__avail_data_size in libbpf.
=> feat(ringbuf): Add AvailableBytes()

btf/ext_info.go, btf/marshal_test.go, link/kprobe.go, link/kprobe_multi.go, link/netfilter.go, link/perf_event.go, link/tracing.go, link/uprobe.go, link/uprobe_multi.go, map.go
These get flagged by gopls and always stick around in my editor, so I decided to get rid of them. There's currently no way to run the gopls linters in CI, so not modifying the linter config at this time.
=> *: remove unused parameters and tautological conditions

go.mod, go.sum, internal/math.go, internal/math_test.go
Temporarily copy the definition of the Integer constraint until the constraints package is moved out of x/exp into the stdlib.
Add a test that makes sure Integer contains all of Go's integer types.
Supersedes https://github.com/cilium/ebpf/pull/1551.
=> internal: remove dependency on x/exp/constraints

elf_reader.go, elf_reader_test.go, map.go, map_test.go
This has been an ambiguous flag since its inception. Internally, we would allow maps to be created with BPF_F_RDONLY_PROG, but not freeze them afterwards. Conversely, we would allow MapSpecs with Freeze set to 'true', but without the rdonly map flag set.
The latter case has caused subtle bugs in the past, since BPF_MAP_FREEZE only blocks further modifications from user space, but doesn't actually mark the map as readonly for the verifier. This will prevent code pruning and other optimizations from taking place.
This commit removes the Freeze field in favor of the map flag and adds a helper to keep existing call sites simple. Sourcegraph code search yields no references to this field in open-source code.
=> map: remove MapSpec.Freeze field

info.go, info_test.go
Hello! 👋 
I'm implementing a Telegraf plugin that extracts metadata information from the `bpf_prog_info` object. There's some additional fields that I'd like to include in the metric, that aren't exposed in `ProgramInfo`.
The additional fields that are exposes are:
- `jited_prog_len`
- `xlated_prog_len`
- `load_time`
- `verified_insns`
=> info: expose additional `bpf_prog_info` fields in `ProgramInfo`

map_test.go
This PR introduces a new test for `MapIterator` as well as small refactoring to some other tests.
With this, the aim is primarily to ensure that `MapIterator` fails when called on keyless maps such as queues/stacks: this is because the current implementation relies on a key (nextKey) lookup from the map, which is then used to retrieve its respective value.
Commit messages should contain each the explanation, feel free to reach me for further q&a :smiley:
=> map tests queues and refactor

cmd/bpf2go/gen/output.go, cmd/bpf2go/gen/output_test.go
The standard Identifier function used by the generator results in very unidiomatic go identifier names when used with my ebpf object. With this change, the Identifier function becomes configurable, allowing me to pass in something that produces better outputs in my context. If no function is passed in, we keep using the default, this makes the change entirely backwards compatible.
Furthermore, a test has been added to ensure the configuration is correctly passed through.
=> feat(gen): Make Identifier function configurable

info.go, info_test.go, map.go
- Added MapInfo.MapExtra(), .Memlock() and .Frozen() methods.
- Moved all unexported fields to a separate section within MapInfo.
- Changed a few tests to use quicktest instead of manual if statements.
This change required a small refactor to how fdinfo is used, since memlock and frozen are only available there. fdinfo is now always consulted regardless of the success of ObjInfo, and any empty fields are supplemented by data from fdinfo.
Removed errMissingFields since its meaning sort of overlapped with ErrNotSupported. It was only used for getting ProgramInfo, which currently looks for just 2 fields. If we want to pull more fields from fdinfo, this no longer works for the majority of older kernels, since they'll always be missing some fields that were introduced later.
Going forward, …
=> map: add map_extra, memlock, frozen to MapInfo

.github/workflows/ci.yml, internal/tracefs/kprobe.go, link/kprobe.go, link/kprobe_test.go, link/uprobe_multi.go, link/uprobe_multi_test.go
As documented in the code, Linux commit torvalds/linux@46ba0e49b642 added an extra check on the pid field, which it interprets as a signed pid_t value, returning EINVAL if it's negative.
Take care not to overflow the value in tests so we can keep receiving ESRCH.
=> link: uprobe multi: add context to EINVAL, don't overflow pid_t in tests

btf/ext_info.go, info.go, info_test.go, internal/cmd/gentypes/main.go, internal/sys/ptr.go, internal/sys/types.go
In [pwru](https://github.com/cilium/pwru), I'm planning to improve the tracing info of bpf prog by mapping ksym addresses to bpf prog info, i.e. the function name of subprograms.
Therefore, it requires more prog info exposed from ProgramInfo, including ksym info and func info.
`bpf_prog_info` supports ksym info since commit torvalds/linux@dbecd7388476 ("bpf: get kernel symbol addresses via syscall"), and supports func info since commit torvalds/linux@838e96904ff3 ("bpf: Introduce bpf_func_info").
=> info: expose ksym info and func info by ProgramInfo

.github/workflows/ci.yml, prog_test.go
Switch to ubuntu-latest runners, these now support nested virt. Also added a test for disabling verifier logs.
=> GHA: re-enable mainline kernel in testing matrix

btf/types.go, btf/types_test.go
d4b2f8cc introduced Tags on different types implementing btf.Type. Tags arrays are initialized at load time from declTag-s referring to the respective type.
Type-s are explicitly copied with btf.Copy, also implicitly when copying a btf.Spec. Semantically, it is a deep copy, hence Tags must be cloned as well.
=> btf: Handle Tags when making copies

elf_reader.go, elf_reader_test.go, internal/kallsyms/kallsyms.go, internal/kallsyms/kallsyms_test.go, internal/kallsyms/reader.go, internal/kallsyms/reader_test.go, prog.go
This commit introduces kallsyms.reader, meant to address the performance
concerns caused by fmt.Sscanf and bytes.Fields. Both of these options
allocate heavily and aren't flexible in terms of avoiding unnecessary
work like skipping the remainder of a line if we're not interested in
the remainder of its contents.
This approach borrows the implementation for reader.Word() from
bufio.ScanWords, paying attention to handling utf-8 characters correctly.
Kernel modules (out-of-tree, at least) can contain international symbols
in exported global kernel variables, which show up in /proc/kallsyms. We
need to err on the side of caution since this is technically user input
that's beyond our control.
This commit renames kallsyms.LoadSymbolAddresses to AssignAddresses and
kallsyms.KernelModule to …
=>  kallsyms: introduce 'reader', an efficient /proc/kallsyms line parser

.github/workflows/ci.yml, internal/feature.go, internal/feature_test.go, internal/testutils/feature.go, internal/testutils/feature_test.go
Feature tests are used to enable new features in a backwards compatible manner. They exercise very specific code paths in the kernel. It makes sense to assume that the existing feature tests will not work as intended when porting to a new platform. Change the existing NewFeatureTest constructor to return a new sentinel error when invoked on non-Linux OS.
Add a new constructor NewPortableFeatureTest which allows indicating on which platforms and versions a feature test is reliable.
=> internal: add a way to write portable feature tests

internal/linux/platform.go, link/kprobe.go, syscalls.go
The platform prefix is tied to the Linux kernel, move it to the appropriate package.
=> internal: move PlatformPrefix to internal/linux

.github/workflows/ci.yml
Seems like the CNCF is stopping funding for the external arm64 runners. Switch to the GitHub provided ones.
=> CI: switch arm64 runners to GHA

map.go, map_test.go, prog.go, prog_test.go
In case of programs or maps as map value types, the value marshalling results in a panic in case of a nil pointer. For other types this is not a problem since sysenc.Marshal does a nil check.
This commit adds a nil check to the internal helper for marshalling programs and maps.
=> prog, map: add nil checks for value marshaller

btf/btf_types.go, btf/feature.go, btf/feature_test.go, btf/marshal.go, btf/marshal_test.go
Decl tags and type tags appeared in 5.16 and 5.17 respectively. This patch makes it possible to load BTF containing such tags on older kernels by replacing decl tags with integers and type tags with const qualifiers. This mirrors the logic in libbpf.
This is convenient if the user wants to load an ELF containing decl tags on global variables (available through CollectionSpec.Variables[].Tags) on older kernels.
=> btf: replace decl and type tags with placeholders on unsupported kernels

elf_reader.go, variable.go, variable_test.go
Before this patch, VariableSpec shared its Type with the underlying datasec, including any prior copies. This commit copies when the type is assigned from the Datasec to the VariableSpec, as well as when the VariableSpec is copied during CollectionSpec.Copy().
=> variable: copy VariableSpec.Type during initial assignment and during copy

internal/epoll/poller.go
Batched perfmap readers with 10ms deadlines showed `fmt.Errorf` consuming ~4% of CPU. This PR reduces CPU usage by replacing repeated formatting with package-level error variables.
=> Optimize `epoll.Wait` by using sentinel errors

elf_reader.go
In commit 82c5aca ("elf: include data sections without references in CollectionSpec"), the sec.references check at the start of *elfCode.loadDataSections was removed to enable generating VariableSpecs for sections without references due to them being potentially compiled out.
After merging this patch, we received an early user complaint about a .rodata.str1.1 map suddenly popping up and being loaded on a non-supported kernel, whereas the same ELF worked fine before.
This patch reintroduces the behaviour with an extra condition: the datasec must have both no references and no symbols, meaning it can't be meaningfully represented in a CollectionSpec, since it would be freed immediately after closing the resulting Collection. String sections typically don't have any associated symbols nor a …
=> elf: reintroduce unreferenced datasec pruning

internal/cmd/gentypes/main.go, internal/sys/fd.go, internal/sys/fd_test.go, internal/sys/types.go, link/link.go, link/link_test.go, map.go, map_test.go, prog.go
Fixes https://github.com/cilium/ebpf/issues/1566.
Before this patch, ebpf.LoadPinnedMap and ebpf.LoadPinnedProg both succeed when used with the wrong object type. Meaning that you can open a prog using epbf.LoadPinnedMap or vice-versa and you'll get garbage data in the object's info.
To my knowledge, there are two ways of knowing from an opened FD which object type it is:
* checking for specific fields in /proc/self/fdinfo/<fd>;
* running readlink(2) on /proc/self/fd/<fd> and check for anon_inode:bpf-prog or anon_inode:bpf-map.
This is a breaking change for users relying on LoadPinned<object> to open any object: I've been using that behavior to scan BPF filesystem.
Note to the reviewer: I've been writing this fairly quickly, I'm sure I'm breaking all your conventions style-wise and I was …
=> map,prog,link: verify object type in LoadPinned*()

features/misc.go, features/misc_test.go
This PR introduces the `haveV4ISA` probe and `HaveV4ISA` API to check in the running kernel if instructions of the v4 ISA are supported. The upstream commit used as reference is 1f9a1ea821ff ("bpf: Support new sign-extension load insns"). The probes tests the new long jump given by `BPF_JMP32 | BPF_JA`.
I'm attempting to submit an identical patch to bpftool, so that `bpftool feature probe` will output also ISAv4 support.
=> features: add HaveV4ISA probe for checking ISA v4 support in the kernel

internal/sys/fd.go, internal/testutils/checkers.go, pin/doc.go, pin/load.go, pin/load_test.go, pin/walk.go, pin/walk_test.go
See individual commits.
The API added in this PR:
```go
type Pinner interface {
Pin(string) error
}
// Load retrieves a pinned object from a bpf virtual filesystem. It returns one
// of [ebpf.Map], [ebpf.Program], or [link.Link].
//
// Trying to open anything other than a bpf object is an error.
func Load(path string, opts *ebpf.LoadPinOptions) (Pinner, error)
// WalkDirFunc is the type of the function called for each object visited by
// [WalkDir]. It's identical to [fs.WalkDirFunc], but with an extra [Pinner]
// argument. If the visited node is a directory, obj is nil.
//
// err contains any errors encountered during bpffs traversal or object loading.
type WalkDirFunc func(path string, d fs.DirEntry, obj Pinner, err error) error
// WalkDir walks the file tree rooted at path, calling …
```
=> pin: new package for loading bpf pins and walking bpffs directories

internal/epoll/poller.go, internal/math.go, internal/math_test.go, prog.go
When the verifier hits a bug, it returns EFAULT while clobbering other retcodes. This defeats the buffer growth algorithm, so the user needs a break-glass procedure for obtaining the full verifier log.
Also, reinstate maxVerifierLogSize since the maxu32 >> 2 limit is still in effect in the Linux kernel. This can be removed if the limit is removed one day and someone has a verifier log that's actually this big.
EFAULT can't be reliably triggered in CI, and I'm currently out of ideas for testing this.
Fixes https://github.com/cilium/ebpf/issues/1554
=> prog: add ProgramOptions.LogSizeStart to obtain full log after verifier bug

map.go, map_test.go
This commit modifies the `MapSpec.fixupMagicFields` method to support the following for the CPU map:
* Validation of KeySize and ValueSize
* Setting KeySize, ValueSize and MaxEntries when set to zero
* Clamping MaxEntries to the number of possible CPUs
This enables to write more portable code when utilizing the CPU map, since kernel-specific and node-specific arguments no longer have to be supplied at compile-time.
=> map: automatically set CPUMap MaxEntries based on possible CPUs

prog.go, prog_test.go
When ProgramOptions.LogSize was removed in 0.16, the tests weren't updated to exercise the retry loop, since a minimum log size was chosen that was larger than what the test program could generate.
With the addition of LogSizeStart, this notoriously fragile code broke when logSize was again tracked as a separate variable, while being accidentally shadowed within the scope of the for loop. This resulted in an endless loop on kernels without the LogTrueSize field.
Remove the shadowing and fix the tests.
=> prog: fix shadowing log size variable in verifier log retry loop

pin/load.go, pin/load_test.go, pin/walk_test.go
The new pin package didn't import fdtrace.TestMain until now, which is why the leaks went by unnoticed.
=> pin: fix a bunch of fd leaks in tests

linker.go, linker_test.go
When resolving the bpf-to-bpf calls we need to copy the instructions from the program to flatten the references.
But when there is no reference there is nothing to do so we can skip the copy operation altogether.
=> linker: do not copy instructions when there is no reference in `flattenInstructions`

collection.go, collection_test.go, elf_reader_test.go
There were 2 problems with the existing implementation:
- cl.loadMap would mutate the original MapSpec before loading
- map compatibility was checked before cl.loadMap applied the BPF_F_MMAPABLE flag
To address this, the following changes were made:
- MapSpec.Copy() is called in loadMap, to follow suit with cl.loadProgram
- the compatibility check on MapReplacements was deferred to loadMap, after flags are mutated
- Added a superficial CollectionSpec mutation test after loading, using the same logic as TestLoadCollectionSpec. testutils.IsDeepCopy() isn't usable here since MapSpec.Copy() doesn't deepcopy .Contents.
- Added a regression test on using .data and .rodata in MapReplacements
Fixes issues seen in https://github.com/cilium/pwru/pull/484. cc @brb @Asphaltt
=> map: check MapReplacements compatibility after applying BPF_F_MMAPABLE

.github/workflows/ci.yml, docs/Pipfile, docs/Pipfile.lock, netlify.toml
Netlify recently announced configurable Python versions in their build pipeline: https://www.netlify.com/blog/announcing-configurable-python-versions-in-netlify-builds.
Make use of this and bump Python to 3.13 since dependabot is now also issuing warnings for 3.8 EOL.
=> docs: upgrade Python version to 3.13

go.mod, go.sum, internal/linux/auxv.go, internal/unix/types_linux.go, internal/unix/types_other.go
Use the newly added `Auxv` wrapper added in `golang.org/x/sys/unix` v0.30.0 instead of manually go:linknaming `runtime.getAuxv`. This also allows to get rid of the check for malformed auxv data as it is already performed by `unix.Auxv`.
=> internal/linux: use `unix.Auxv`

btf/ext_info.go, btf/ext_info_test.go
When parsing line info records, we currently iterate and call `binary.Read` once per line info record. This is quite inefficient and `binary.Read` already supports out of the box being called directly on a slice and reading multiple structures at once. This is exactly what this PR does.
Benchmark:
```
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
ParseLineInfoRecords-10   288.6µ ± 3%   141.3µ ± 4%  -51.02% (p=0.000 n=10)
│   old.txt    │            new.txt             │
│     B/op     │     B/op      vs base          │
ParseLineInfoRecords-10   128.0Ki ± 0%   128.0Ki ± 0%  ~ (p=1.000 n=10)
│    old.txt    │              new.txt               │
│   allocs/op   │ allocs/op   vs base                │
ParseLineInfoRecords-10 …
```
=> btf: read all line info records at once in `parseLineInfoRecords`

info.go
Commit 78074c59 ("info: expose more prog jited info", PR #1598), which made its
way into v0.17.0, resulted in random runc CI failures when running i386
binary on an amd64 kernel (see [1]).
Apparently [2], the kernel always returns 64-bit pointers, so uint64
(rather than uintptr) should be used for ksyms slice regardless of
the platform to avoid the buffer overrun.
Now, to keep the public API of `(*ProgramInfo).JitedKsymAddrs` intact,
convert those addresses back to `uintptr`, as it was done before
commit 78074c59. Except, if the kernel address won't fit into an `uintptr`
(as it is the case when running i386 binary on an amd64 kernel), return
an empty slice and a false, rather than incorrect addresses.
[1]: https://github.com/opencontainers/runc/issues/4594
[2]: …
=> Fix ksym buffer overflow on 32 bit platforms

cpu.go, cpu_other.go, cpu_test.go, cpu_windows.go, internal/linux/cpu.go, internal/linux/cpu_test.go
Move the Linux implementation into internal/linux and add a wrapper around the Windows GetMaximumProcessorCount function.
=> ebpf: implement PossibleCPU on Windows

internal/cmd/gentypes/main.go, internal/sys/ptr_32_be.go, internal/sys/ptr_32_le.go, internal/sys/ptr_64.go, internal/sys/types.go
Go 1.23 introduced structs.HostLayout to tell the toolchain that a struct should be laid out in memory as it is laid out in code. Add the annotation to the generated structs.
=> sys: hint that structs require host layout

info_test.go
For some reason this test is flaky on arm64. Disable the assertion for now.
Updates https://github.com/cilium/ebpf/issues/1683
=> info: don't check Runtime in TestStats on arm64

btf/marshal.go, btf/marshal_test.go, btf/traversal.go, btf/traversal_test.go, btf/types.go, btf/types_test.go
Now that we're on 1.23 we can use iterators. The existing iterators don't really need to be modified. Allocations don't change, run time seems a little bit faster.
core: 1
goos: linux
goarch: amd64
cpu: 13th Gen Intel(R) Core(TM) i7-1365U
│   base.txt   │              iter.txt              │
│    sec/op    │    sec/op     vs base              │
PostorderTraversal/single_type           49.79n ± ∞ ¹   48.68n ± ∞ ¹  -2.23% (p=0.029 n=4)
PostorderTraversal/cycle(1)              146.4n ± ∞ ¹   135.8n ± ∞ ¹  -7.24% (p=0.029 n=4)
PostorderTraversal/cycle(10)             1.928µ ± ∞ ¹   1.861µ ± ∞ ¹  -3.45% (p=0.029 n=4)
PostorderTraversal/gov_update_cpu_data   1.895m ± ∞ ¹   1.907m ± ∞ ¹       ~ (p=0.057 n=4)
geomean                                  2.271µ …
=> btf: use iterators

.gitattributes
Ensure that files in the repository use Unix-style line endings throughout.
See https://git-scm.com/docs/gitattributes#_checking_out_and_checking_in
=> all: force consistent line endings

.github/workflows/ci.yml
4.9 has been EOLed a long time ago. Remove it from CI.
Fixes #1007
=> CI: remove 4.9

internal/efw/object.go, internal/testutils/bpffs_other.go, internal/testutils/bpffs_windows.go, internal/testutils/bpffs_windows_test.go
Object pinning on Windows isn't backed by a file system, instead the path is just used as an identifier. Generate a random prefix to use for tests on Windows.
=> internal/testutils: make TempBPFFS portable

btf/feature.go, btf/handle.go, info.go, internal/cmd/gentypes/main.go, internal/output.go, internal/output_test.go, internal/sys/ptr.go, internal/sys/ptr_test.go, internal/sys/syscall.go, internal/sys/types.go, internal/sysenc/buffer.go, internal/sysenc/buffer_test.go, link/iter.go, link/kprobe_multi.go, link/query.go, link/uprobe_multi.go, map.go, marshalers.go, prog.go, syscalls.go
Add TypedPointer which is a type safe wrapper around Pointer. This relieves users of the generated bindings from knowing which types are expected. This should make it less likely that we cause a hard to debug panic or crash due to the kernel overwriting runtime memory.
sys.Pointer still exists because there are some cases where we legitimately don't know what type to point at, for example the link info APIs. Map APIs are also unchanged for now because they don't benefit much from converting to TypedPointer[byte].
=> sys: add type safe Pointer wrapper

.github/workflows/ci.yml
Installing clang-11 takes the majority of time for the bpf2go test. This in turn delays the matrix based tests, lengthening the overall CI run time by a minute or two.
Bump the minimum version to 13, which is pre-installed on ubuntu 22.04 runners. This way we don't have to pay the price of installation.
=> ci: speed up test of bpf2go

collection_test.go, elf_reader_test.go, go.mod, go.sum, helpers_test.go, info_test.go, linker_test.go, map.go, map_test.go, marshaler_example_test.go, memory_test.go, prog_test.go
Introduce helpers for creating a map, program, collection from a spec. Additionally, add helpers which create very common types like arrays or socket filter programs.
This significantly cuts down on boiler plate in unit tests, and ensures that all resources backed by a file descriptor are cleaned up.
It will also allow adding compatibility code for running Linux unit tests on Windows in a central location.
=> ebpf: clean up tests

.github/workflows/ci.yml, info_test.go, internal/feature.go, internal/platform/platform.go, internal/testutils/fd_other.go, internal/testutils/fd_windows.go, internal/testutils/feature.go, internal/testutils/feature_windows.go, map_test.go, prog_linux_test.go, prog_test.go
testutils: make IsVersionLessThan cross platform
We usually rely on feature tests to skip certain portions of a test. This
causes a lot of overhead when the feature tests would only be used by the
unit tests.
For that reason the info tests skip some tests based on the current kernel
version. Extend this concept to other platforms by reusing the selection
logic introduced for feature tests.
testutils: add DupFD helper
Add a cross-platform DupFD helper and use it from tests.
ebpf: run TestProgramTestRunInterrupt only on Linux
TestProgramTestRunInterrupt tests Linux specific behaviour around signal 
delivery. It doesn't make sense to run it on a different platform.
The test was copied without …
=> windows: more test / testutils fixups

collection.go, collection_test.go, internal/testutils/feature.go, prog_test.go
More prep work to make the Windows support easier to add.
collection: remove obsolete TestCollectionSpecLoadCopy
The test was added in bf5a6cd6 ("collection: don't copy btf.Spec in
CollectionSpec.Copy()"). We now copy the spec, so the test doesn't add
anything meaningful.
collection: remove TestCollectionSpecLoadMutate
Replace the test added in 278a9141 ("map: check MapReplacements 
compatibility after applying BPF_F_MMAPABLE") with one that doesn't rely on
the ELF reader.
collection: fix missing Map.Close in collectionLoader.loadMap
program: rework TestProgramRunEmptyData
Remove the test in favour of a much shorter assert in TestProgramRun. Also
remove the now unnecessary version skip, since …
=> windows: even more test fixes

map.go
We have already judged err before. Therefore, err here must be nil.
Here  `sysErr` should be returned instead of err.
=> map: fix problematic error returns

.github/workflows/ci.yml, internal/efw/error_reporting.go, internal/efw/error_reporting_test.go
ci: log chosen workflow run
Add debug logging to make it clear from which workflow run the efW runtime
is downloaded.
efw: configure CRT error reporting
The Windows C runtime validates parameters passed to common functions. An
assertion is raised if an invalid parmeter is detected. By default, 
assertions are presented as a graphical message box. Displaying a message
box hangs on systems without a UI, such as our CI.
Configure the debug runtime to log assertions to stderr instead of showing a
dialog. Try to avoid stepping on application specific debug handlers in the
process.
=> efw: configure CRT error reporting

collection.go
Remove the loops which copy MapSpec and ProgramSpec another time after copyMapOfSpecs is done.
=> collection: don't copy Maps and Programs twice

.github/workflows/ci.yml, cmd/bpf2go/test/api_test.go, features/map.go, features/map_test.go, features/misc.go, features/misc_test.go, features/prog.go, features/prog_test.go, features/version.go, internal/feature.go
features: return ErrNotSupportedOnOS on windows
This reverts commit 8d7c47ffbd3812ed2ef7de4ada79141b9d3a8126.
Return a sentinel error instead of removing the API outright. This avoids
compilation failures on non-Linux platforms.
CI: cross build for darwin
Switch the windows cross-build back to darwin. We have a dedicated Windows
job now, so bringin the darwin build back is more useful.
=> features: return ErrNotSupportedOnOS on windows

link/helpers_windows_test.go, link/link_windows_test.go, types_windows.go, types_windows_test.go
Export a function which allows resolving a GUID to an AttachType. This is useful when an eBPF extension has not yet registered a stable AttachType with the eBPF for Windows runtime, as is currently the case for ntosebpfext.
=> ebpf: allow retrieving program / attach type from GUID

docs/ebpf/contributing/windows.md, docs/ebpf/guides/windows-support.md, docs/includes/glossary.md, docs/mkdocs.yml
Add a short section to our docs which calls out the most important differences between Linux and Windows.
=> docs: add user facing documentation for Windows

elf_reader.go, map.go, map_test.go, prog.go, prog_test.go, syscalls.go, syscalls_test.go
The kernel only allows a restricted set of characters when naming a map or program. So far we've required the user to call SanitizeName manually to ensure that the Name is valid.
Always sanitize names and unexport SanitizeName. The ELF reader still calls sanitizeName to avoid changing the output too much.
=> map, program: always sanitize names passed to the kernel

internal/epoll/poller.go, internal/epoll/poller_test.go, perf/reader.go, perf/reader_test.go, perf/ring.go, perf/ring_test.go, ringbuf/reader.go, ringbuf/reader_test.go, ringbuf/ring.go
As suggested in https://github.com/cilium/ebpf/issues/1746#issuecomment-2800923799 replace the go build tag `linux` with `!windows`.
Fixes https://github.com/cilium/ebpf/issues/1746 and https://github.com/cilium/ebpf/issues/1749.
=> perf,ringbuf: switch Go build tag

btf/fuzz_test.go, internal/kconfig/kconfig_test.go, internal/sysenc/marshal.go, internal/sysenc/marshal_test.go, prog.go
ebpf: use binary.Append
tests: use binary.Append where appropriate
sysenc: use binary.Append when marshaling
Using binary.Append allows us to drop allocating a bytes.Buffer from a
sync.Pool. This reduces the number of allocations in some benchmarks.
=> all: use binary.Append where appropriate

btf/btf.go, btf/btf_test.go, btf/core.go, btf/strings.go, btf/unmarshal.go, btf/unmarshal_test.go
Most of the time in parsing vmlinux BTF is spent in constructing the essentialName -> TypeID index.
1. We need to allocate a lot of strings
2. We need to do a lot of hash table lookups
Replace the hash table with a "fuzzy" index, which doesn't require allocating strings. The trade-off is that lookups now become more expensive, but that is a fine trade-off to make.
core: 1
goos: linux
goarch: amd64
cpu: 13th Gen Intel(R) Core(TM) i7-1365U
│  base.txt   │          lazy-strings.txt           │
│   sec/op    │    sec/op     vs base               │
ParseVmlinux      27.24m ± 1%   15.49m ±  1%  -43.15% (p=0.002 n=6)
IterateVmlinux    149.9m ± 2%   132.3m ± 15%  -11.73% (p=0.041 n=6)
InspectorGadget   35.08m ± 2%   21.28m ±  5%  -39.34% (p=0.002 n=6)
geomean …
=> btf: lazy decoding of string table

btf/btf_test.go
Just saw the typo in https://github.com/cilium/ebpf/pull/1763 in the benchmark function name
=> Typo: BenchmarkInspectorGadget -> BenchmarkInspektorGadget

map.go, types.go
This commit adds a new MapType.mustHaveNoPrealloc() helper to collect map types that need BPF_F_NO_PREALLOC in order to be created successfully. This reduces the potential for red herrings while troubleshooting why map creation returns EINVAL.
Also added a similar warning for map types that are known to require the flag when the user forgets to specify the flag.
Supersedes https://github.com/cilium/ebpf/pull/1720.
=> map: reduce false positives of BPF_F_NO_PREALLOC hint on EINVAL

.github/workflows/ci.yml
Seems like the CI setup for eBPF for Windows has changed. Use the scheduled CI builds on main as the source for the binaries.
=> ci: fix efW installation

btf/format.go, btf/format_test.go, cmd/bpf2go/gen/output.go, cmd/bpf2go/gen/output.tpl, cmd/bpf2go/test/test_bpfeb.go, cmd/bpf2go/test/test_bpfel.go, examples/fentry/bpf_bpfeb.go, examples/fentry/bpf_bpfel.go, examples/ringbuffer/bpf_bpfeb.go, examples/ringbuffer/bpf_bpfel.go, examples/tcprtt/bpf_bpfeb.go, examples/tcprtt/bpf_bpfel.go, examples/tcprtt_sockops/bpf_bpfeb.go, examples/tcprtt_sockops/bpf_bpfel.go, examples/uretprobe/bpf_x86_bpfel.go, internal/cmd/gentypes/main.go, internal/sys/types.go
Types described by BTF essentially follow C rules for laying out a struct. Use the newly introduced structs.HostLayout to hint at the compiler that reordering is not permissible.
Fixes #1686
=> bpf2go, btf: emit structs.HostLayout in GoFormatter

btf/btf.go, btf/btf_test.go, btf/unmarshal.go
Make decoder.Copy do a deep copy of the base, so that types which are inflated in the future also point at the correct copy.
=> btf: fix Spec.Copy() for split BTF

asm/load_store.go
=> fix: return InvalidOpCode for StoreImm with DWord size

info.go, info_test.go
This patch adds a ProgramInfo.Memlock() method, the memlock field is obtained from fdinfo.
=> info: add memlock field to ProgramInfo

.github/workflows/ci.yml, .golangci.yaml, asm/func_lin.go
golangci-lint uses a copy of staticcheck rules, which leads to funky differences between what staticcheck reports locally and what golangci-lint reports. This is annoying, and the real staticcheck is of higher quality than golangci-lint. Use it in CI instead of the copy.
=> ci: use real staticcheck

internal/deque.go, internal/version.go, map.go
use the built-in max/min to simplify the code
=> refactor: use the built-in max/min

linker.go, prog.go
KFuncs fixing up loads only system BTF, so using custom (non-system) BTF specification with KFuncs leads to errors.
=> kfunc: poison all weak kfunc calls if the kernel lacks BTF

btf/kernel_test.go
The module is called bpf_testmod, not btf_testmod. Fix the name to make the test execute.
=> btf: fix TestLoadKernelModuleSpec

btf/kernel.go, btf/kernel_test.go, btf/unmarshal.go, collection.go, linker.go, prog.go
We currently create a new copy of kernel BTF when loading each program in a 
collection, which is quite expensive.
Introduce a new type btf.Cache which allows re-using kernel BTF as-needed. 
As an optimisation, the Cache is opportunistically populated from the global 
cache on creation.
core: 1
goos: linux
goarch: amd64
pkg: github.com/cilium/ebpf
cpu: 13th Gen Intel(R) Core(TM) i7-1365U
│   base.txt   │             cache.txt              │
│    sec/op    │   sec/op     vs base               │
NewCollectionManyProgs   347.84m ± 1%   14.54m ± 2%  -95.82% (p=0.002
n=6)
│    base.txt    │              cache.txt           
│
│      B/op      │     B/op      vs base             
│
NewCollectionManyProgs   108.056Mi ± 0%   3.841Mi ± 0%  -96.44% (p=0.002
n=6)
│   base.txt    │ …
=> collection: share kernel BTF when loading a collection

internal/kallsyms/kallsyms.go, internal/kallsyms/kallsyms_test.go, internal/kallsyms/reader.go
Two small optimisations which drop CPU time by 25% on my machine, plus a lot less allocations.
=> kallsyms: optimize things a bit

Makefile, cmd/bpf2go/README.md
Fix docs and Makefile that reference `BPF2GO_FLAGS`. Use `BPF2GO_CFLAGS` instead.
=> cmd/bpf2go: Use BPF2GO_CFLAGS instead of BPF2GO_FLAGS

asm/instruction.go, asm/instruction_test.go, internal/platform/constants.go, internal/platform/constants_test.go
The work to encode a platform into various constant types made it so that decoding a call to a builtin helper with a negative value fails with
decoding instructions for section <sectionname>:
offset <offset>: invalid constant 0xffffffff
for a BPF instruction of "call -1". This is because we can't represent -1 as a tagged platform constant.
Allow negative constants by not transforming them into a platform constant at all. Adjust the platform tag size so that we never generate a platform constant with the high bit set. This avoids confusing it with a negative number when reinterpreting it as a signed number and ensures that trying to marshal such an instruction gives an error.
Fixes: https://github.com/cilium/ebpf/issues/1797
=> asm: allow negative constants for builtin function calls

linker.go
9958a4f58fb4e533201e0a76d6d82eeeaa91434b allowed to perform CO-RE against all kernel modules, but introduced a small regression where kernels with no BTF would fail to perform CO-RE with the manually provided types. This commit fixes the issue by skipping the modules BTF collection if there is nothing in `/sys/kernel/btf`.
=> linker: do not error out when there is nothing in `/sys/kernel/btf`

prog.go
With commit df9ebe8 the opening of programs by fd was improved. The LoadPinnedProgram still uses to full ProgramInfo instead of the sufficient minimal one.
This commit improves the load of pinned Programs as well by using the central helper for creating programs from a fd. This also makes it more consistent with the LoadPinnedMap function as well.
=> prog: speed up opening pinned Programs

internal/kallsyms/kallsyms.go, linker.go
Calling kallsyms.Address is incredibly expensive because we need to scan all of /proc/kallsyms for a single address.
Move to AssignAddresses instead and remove Address.
=> linker: resolve ksyms in one go

.github/workflows/ci.yml
It's not possible to add a matrix step as a check to branch protection rules. Add an extra step to work around this.
=> ci: add a Results step to work around GH protection rules

cmd/bpf2go/gen/compile.go, cmd/bpf2go/main.go
Allow multiple commands to be specified inside `BPF2GO_CC`. Example:
```
BPF2GO_CC="ccache clang" go generate ../pkg/a/b
```
I'm working on https://github.com/cilium/cilium/pull/38693 where one of the checks uses `ccache clang` instead of just `clang` as the compile command substitution. Currently, this doesn't work with `bpf2go`. This change makes it possible to use the same compile command as the rest of the build in cases like this.
=> bpf2go: Allow multiple commands inside `BPF2GO_CC`

.github/workflows/ci.yml
Remove EOL kernels and add the most recent LTS.
Fixes: https://github.com/cilium/ebpf/issues/1699
=> ci: remove 4.14 and 4.19 and add 6.12

btf/btf_test.go, btf/strings.go, btf/strings_test.go
I opened this PR to address [issue#1818](https://github.com/cilium/ebpf/issues/1818).
In my experience, the problem has been occurring since version v0.19.0 (it does not appear in v0.18.0), specifically for the `aesni_intel` kernel module. The error encountered is:
```text
apply CO-RE relocations: load BTF for kmod aesni_intel: read string section: string table is empty
exit status 1
```
I've checked `stat /sys/kernel/btf/aesni_intel`. It shows 24 bytes, which is for the BTF header, but it has no content.
=> btf: don't try to load strings when file is empty

ringbuf/ring.go
fixes https://github.com/cilium/ebpf/issues/1835
=> ringbuf: Use uintptr for positions for 32-bit compatibility

ringbuf/reader.go, ringbuf/reader_test.go
Fix the issue describe in #1857.
Following https://github.com/cilium/ebpf/pull/1849, the `Close` function was changed to not set the ring to nil.
The panic happens when `r.haveData` is true, a `Close` happens and then another `Read`.
Added a test that reproduces the panic.
=> ringbuf: fix read after close panic

prog.go, prog_test.go
fixes https://github.com/cilium/ebpf/issues/1841
=> prog: Allow explicit ifindex specification

btf/kernel.go, btf/kernel_test.go, collection.go, linker.go, prog.go
Extend the BTF cache to fixups and target search. This means that each collection load will load each BTF blob at most once.
Unexport fields in btf.Cache since we don't need to short-circuit BTF loading from package ebpf anymore.
=> program: use cached BTF for fixups and target search
