go.mod
go.sum
syscalls.go

Update golang.org/x/sys dependency to get these consts.

Use BPF_OBJ_NAME_LEN and BPF_TAG_SIZE from golang.org/x/sys/unix

---

prog.go
prog_test.go
syscalls.go
types.go

This PR adds the syscall wrappers to attach/detach a program as mentioned in https://github.com/cilium/ebpf/issues/22.

Add prog Attach/Detach

---

collection.go
collection_test.go

Given a CollectionSpec, it's sometimes useful to use existing Maps instead
of having NewCollection spec create them from scratch. For example,
multiple programs might share the same map. Another use case is persistet
state that needs to be kept between two versions of an eBPF program.
Add a helper RewriteMaps which allows to achieve this.

collection: allow rewriting individual maps

---

map.go
map_test.go
prog.go
prog_test.go
syscalls.go
types.go

This PR implements the *GetNextID functions for ebpf maps and programs.

Add *GetNextID

---

map.go
map_test.go
prog.go
prog_test.go
syscalls.go

This PR add the functions to get the FD of a map or program by its ID.

Add New(Map|Program)FromID

---

example_sock_elf_test.go

remove unused const from example

---

elf_reader.go

This PR fixes two error messages.

fix errors

---

example_program_test.go

This PR reads the system specific tracepoint id instead of using the hard coded id.

Get system specific tracepoint id

---

example_program_test.go

tiny: remove new line from tracepoint id

fix tracepoint id

---

elf_reader.go
types.go
types_string.go

Add support for the new BPF socket lookup program and attach type.

elf: recognize BPF_PROG_TYPE_SK_LOOKUP

---

link/iter.go
link/link.go

Allow accessing the underlying fd for exported types.

link: add FD methods

---

internal/btf/types.go

Inflate BTF FuncProto params

---

internal/btf/btf_test.go
internal/btf/btf_types.go
internal/btf/types.go

Add BTF Int encoding, offset, and bits fields

---

internal/btf/types.go
internal/btf/types_test.go

I was experimenting with writing an `Equal` function for btf.Type. That didn't go far, but these small changes from that work still seem useful.

small BTF tweaks

---

internal/btf/btf.go
internal/unix/types_linux.go
internal/unix/types_other.go

Extend kernel BTF search to other likely locations

---

.semaphore/semaphore.yml
elf_reader_test.go

CI: test on 5.9 kernel

---

elf_reader.go
internal/btf/btf.go
internal/btf/btf_test.go
internal/feature.go
internal/testutils/feature.go
link/iter_test.go
prog.go
prog_test.go
run-tests.sh

Support LSM attach

---

internal/btf/btf.go

Add a missing err != nil check.

btf: check err in loadSpecFromVmlinux

---

internal/syscall.go
link/link.go
link/link_test.go
link/netns.go
link/netns_test.go
link/syscalls.go
syscalls.go

Add a wrapper for SkLookup programs that allows retrieving information about the link.

link: add AttachSkLookup

---

map.go
prog.go
readme.md

See individual commit messages for details.

Various doc link fixes

---

readme.md

Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>

readme.md: update linux filter doc link

---

elf_reader_fuzz.go

As with the BTF fuzz target, add a function that tests ELF loading.

elf: add go-fuzz target

---

internal/feature.go

Refactor feature tests to use a read-write mutex
for the more common read case.
Signed-off-by: Nate Sweet <nathanjsweet@pm.me>

nit: Give Feature Test RWMutex

---

info_test.go

TestStats flaked here:
https://ebpf.semaphoreci.com/jobs/40a1735f-1281-49b3-b352-73881e04a8d5#L2912-L2913
and it wasn't clear whether runtime info was available or not.
Would be nice to see the difference in case this happens again.
Modified while investigating https://github.com/cilium/ebpf/issues/117#issuecomment-789011271.

info_test: explicitly check RunCount and RunTime fields availability

---

map.go
map_test.go

https://github.com/cilium/ebpf/issues/237
(I think) I did what suggested [here](https://github.com/cilium/ebpf/pull/218#discussion_r576876853)

map: return error on inner MapSpec with pin

---

map.go
pinning.go
prog.go
prog_test.go

This is a follow-up PR to #204 to add similar support for `Program`.
Signed-off-by: Aditi Ghag aditi@cilium.io

Add Unpin for Program

---

link/kprobe.go
link/kprobe_test.go

Closes https://github.com/cilium/ebpf/issues/275

link/kprobe: parse retprobe bit

---

examples/README.md

Hi all,
The commit is to provide the helpful guidelines on how to run the examples.
Signed-off-by: Wen-Quan Li <legendarilylwq@gmail.com>

Update README.md for how to run examples

---

.semaphore/semaphore.yml

Bump to the latest point release.

CI: update to Go 1.16.5

---

link/uprobe.go
link/uprobe_test.go

Closes https://github.com/cilium/ebpf/issues/297

link/uprobe: support user provided offsets

---

cmd/bpf2go/output.go

Include the offending line of generated source code if formatting
fails. This makes it easier to diagnose template problems:
13:6: expected 'IDENT', found '.': .Name.Constants struct {} (and 1 more errors)

cmd/bpf2go: make formatting errors more descriptive

---

elf_reader.go

elf: support cgroup getsockname/getpeername prog
Signed-off-by: Feng Zhou <zhoufeng.zf@bytedance.com>

elf: support cgroup getsockname/getpeername prog

---

.semaphore/semaphore.yml

Build examples on CI, to ensure they work.

CI: build examples

---

info.go
prog.go
prog_test.go
syscalls.go

Signed-off-by: chenqijun <chenqijun@corp.netease.com>

features: support get map ids from program.

---

collection.go
elf_reader.go
internal/btf/btf.go
internal/btf/btf_test.go
internal/btf/core.go
internal/btf/core_test.go
internal/btf/strings.go
internal/btf/types.go
link/freplace.go
link/freplace_test.go
linker.go
map.go
prog.go

I think this is the MVP to make `btf` accessible to users.

btf: prepare for making the package public

---

examples/go.mod
examples/go.sum
examples/kprobe/main.go
examples/kprobepin/main.go
examples/tracepoint/main.go
examples/uretprobe/main.go

examples: upgrade ebpf, adopt RemoveMemlockRlimit()

---

ringbuf/reader.go

If the ringbuffer map size is zero or not a power of two,
ringbuf.NewReader would leak the epoll file descriptor it just created.
Fix this by moving the ringbuffer map size check before the call to
unix.EpollCreate1.
Fixes: af50a38dd5c8 ("ringbuf: add new package to read from BPF ring buffers")

ringbuf: avoid leaking epoll FD on invalid map size in NewReader

---

map_test.go
marshalers.go

The common int32 and int64 types are directly handled to avoid
unnecessary heap allocations as happening in the default case.

Directly handle int32 and int64 types in unmarshalBytes()

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml

Add a bug report template and point users to discussions and slack.
Example for the contact_links: https://github.com/microsoft/vscode/issues/new/choose

Update issue templates

---

.semaphore/semaphore.yml
Makefile
README.md
testdata/docker/Makefile

This commit allow using Podman to regenerate examples/testdata objects

makefile: allow changing container engine and args

---

link/kprobe_test.go

As of at least 5.15.6, the printk function symbol is no longer present in the Linux kernel. Switch to vprintk instead, and put the symbol name into a variable so it can be easily changed again later.
cc @mmat11

link: switch tests from printk to vprintk symbol

---

elf_reader_test.go

elf_reader_test: enable test_sk_assign.o, handle iproute2 map

---

.semaphore/semaphore.yml

5.15 is the latest LTS and 5.14 is EOL.

CI: Linux 5.15 instead of 5.14

---

prog.go

Signed-off-by: ningmingxiao <ning.mingxiao@zte.com.cn>

delete useless code

---

asm/instruction_test.go

This PR adds CoW checks for all existing metadata interactions.
Based on @dylandreimerink's work, extended to include more than References.

asm: add tests for metadata CoW

---

internal/cmd/gentypes/main.go
internal/sys/types.go
prog.go
prog_test.go

This PR adds support for a new `TestWithOptions()` API
for `Program`s. The extra options are useful for more advanced
testing.

program: Add TestWithOptions() API

---

btf/btf_types.go
btf/types.go
btf/types_test.go

Replace intEncoding with a type. This allows adding setters.

btf: add btfInt

---

examples/tracepoint_in_go/main.go

sycall should be syscall.

---

link/kprobe_amd64_test.go

Closes https://github.com/cilium/ebpf/issues/715

link/kprobe: skip offset test on kernel version > 5.15

---

internal/pinning.go

Statfs_t.Type differs in size between 32 and 64 bit platforms:
type Statfs_t struct {
Type    int32
...
}
type Statfs_t struct {
Type    int64
...
}
This is a problem since the bpfFSType constant we want to compare
against is a negative number when intepreted as an int32. Therefore the
conversion to uint64 yields an invalid result due to sign extension.
Account for this difference by casting via uint32 on 32 bit arches.
Fixes #726

internal: avoid sign extension of Statfs_t.Type on 32 bit arches

---

examples/README.md

Make it more explicit how examples get built.

examples: clarify how to rebuild

---

features/misc.go

Seems like a copypasta error slipped through when writing the probe code.

features: fix incorrect lock in probeMisc

---

README.md

Signed-off-by: Dmitry Savintsev <dmitris@users.noreply.github.com>

fix bad link to GitHub Discussions

---

features/prog.go

add support for ebpf.LSM in haveProgramType

feat: support LSM prog type

---

run-tests.sh

Support running tests under a locally built kernel image.

run-tests: allow using local kernel

---

link/link.go
link/link_test.go

link: new link from fd

---

.golangci.yaml

Ensure that gofmt reports no changes in CI.

CI: enable gofmt linter

---

CONTRIBUTING.md

Write down the guidelines we've been using to decide whether a breaking change is acceptable or not.

docs: document API stability

---

internal/testutils/feature.go
internal/testutils/feature_test.go

allow skipping kernel version check for feature tests if test skipped via env variable

---

btf/core_test.go
btf/marshal_test.go
btf/traversal_test.go
examples/map_in_map/main.go
internal/testutils/seed.go

replace deprecated rand.Seed calls

---

cmd/bpf2go/main.go

This enables code generation on riscv64.

Add riscv64 Linux string

---

cmd/bpf2go/main.go
collection_test.go

This PR corrects spelling mistakes.

bpf2go,collection: fix typos in test and comment

---

.github/workflows/apidiff.yml
.github/workflows/trusted.yml

Store the result of apidiff as a json artifact.

CI: store apidiff as json artifact

---

.github/workflows/trusted.yml

The workflow runs, but doesn't add or remove labels. The ways of GHA are mysterious.

CI: add logging to trusted workflow

---

link/syscalls.go

The `BPF_LINK_CREATE` syscall code in the kernel uses the type of the program that is being attached with bpf_link to determine the actual link type, in this case TCX.
This commit ensures we pass a program of type SchedCLS to the `BPF_LINK_CREATE` syscall to actually feature test the TCX link type. Without it, the `haveTCX` feature test only probes for the availability of the `BPF_LINK_CREATE` syscall which is already covered by `haveBPFLink` and isn't sufficient here.
When passing an invalid FD to the syscall, the returned error won't actually be EBADF, but ENODEV.

link: fix tcx feature test

---

prog.go

as addressed in discussion #1329

fix minor contradiction in comments

---

docs/ebpf/contributing/index.md
docs/includes/glossary.md

Mention that we require DCO sign off, and what it means to sign off.

doc: add DCO

---

.github/dependabot.yml

gh: try to group dependabot updates

---

link/link_test.go

testLink still has the assumption that calling RawLink.Info will return an Info appropriate to the underlying link type. This is not the case anymore since a recent refactoring. Instead switch on the type of the link.
Another problem is that the test assumes that pinning and loading from a pin as well as creating a link from an FD will return the same type. This isn't the case when pinning a RawLink. Relax the assertion.

link: don't crash when calling testLink with a RawLink directly

---

README.md

README.md: add pin package to the overview

---

docs/ebpf/contributing/windows.md
docs/mkdocs.yml
scripts/windows/README.md
scripts/windows/Setup.ps1
scripts/windows/autounattend.xml
scripts/windows/setup-efw.sh
scripts/windows/setup.sh

Add a script which streamlines setting up a VM to develop ebpf-go in. Document how to develop the port in that VM.

docs: add instructions for working on the Windows port

---

Makefile
cmd/bpf2go/main.go
internal/cmd/gentypes/main.go

- Improve podman QoL by mounting the user's go module cache.
- Reduce verbosity of gentypes
- Reduce verbosity of bpf2go behind -debug flag or `V=1` env

ci: reduce bpf2go and gentypes verbosity, mount gomodcache when using podman

---

.github/workflows/ci.yml
README.md
info.go
syscalls.go

Update version strings to match reality and update the readme.

all: require eFW 0.21.0

---

cmd/bpf2go/main.go
internal/platform/platform.go

Optimize code using a more modern writing style.

refactor: replace HasPrefix+TrimPrefix with CutPrefix

---

map.go
map_test.go

Extend the optimization for batch lookups done in b89a4cb9 to PerCPUMaps as well.
It adapts the flow of the single value maps. For passed values objects that can not be used as backing memory, the behavior is the same as before.
```
goos: linux
goarch: amd64
pkg: github.com/cilium/ebpf
cpu: AMD Ryzen 5 5600G with Radeon Graphics
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
Iterate/PerCPUHash/BatchLookup-8            551.3µ ± 1%   129.7µ ± 1%  -76.47% (p=0.000 n=10)
Iterate/PerCPUHash/BatchLookupAndDelete-8   568.2µ ± 1%   148.4µ ± 1%  -73.88% (p=0.000 n=10)
geomean                                     559.7µ        138.7µ       -75.21%
│   old.txt    │              new.txt               │
│     B/op     │    B/op     vs base …
```

map: avoid allocations during PerCPUMap batch lookups
